# Generated by Django 4.2.24 on 2025-10-07 17:07

from django.db import migrations


def remove_climate_offeror(apps, schema_editor):
    """
    Remove canvas platform
    """

    LearningResourceOfferor = apps.get_model(
        "learning_resources", "LearningResourceOfferor"
    )
    LearningResourceOfferor.objects.filter(code="climate").delete()


def add_climate_offeror(apps, schema_editor):
    LearningResourceOfferor = apps.get_model(
        "learning_resources", "LearningResourceOfferor"
    )

    LearningResourceOfferor.objects.update_or_create(
        code="climate",
        defaults={
            "name": "MIT Climate Portal",
            "professional": False,
            "offerings": ["Learning Materials"],
            "audience": ["Everyone"],
            "formats": ["Online", "Downloadable"],
            "fee": ["Free"],
            "certifications": ["No Certificates"],
            "content_types": ["Academic"],
            "more_information": "https://climate.mit.edu",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("data_fixtures", "0018_add_mit_climate_platform"),
    ]

    operations = [
        migrations.RunPython(add_climate_offeror, remove_climate_offeror),
    ]
