# Generated by Django 4.2.24 on 2025-10-07 17:07

from django.db import migrations

from data_fixtures.utils import upsert_topic_data_file


def remove_climate_offeror(apps, schema_editor):
    """
    Remove canvas platform
    """

    LearningResourceTopic = apps.get_model(
        "learning_resources", "LearningResourceTopic"
    )
    LearningResourceTopic.objects.filter(
        name="Ecosystems", parent__name="Energy, Climate & Sustainability"
    ).delete()


def add_climate_offeror(apps, schema_editor):
    # read in updated yaml file and upsert ecosystems subtopic
    upsert_topic_data_file()


class Migration(migrations.Migration):
    dependencies = [
        ("data_fixtures", "0019_add_mit_climate_offerer"),
    ]

    operations = [
        migrations.RunPython(add_climate_offeror, remove_climate_offeror),
    ]
