QDRANT_PARAM_MAP = {
    "resource_type": "resource_type",
    "certification": "certification",
    "certification_type": "certification_type.code",
    "professional": "professional",
    "free": "free",
    "id": "id",
    "course_feature": "course_feature",
    "content_feature_type": "content_feature_type",
    "run_id": "run_id",
    "resource_id": "resource_id",
    "topic": "topics[].name",
    "ocw_topic": "ocw_topics",
    "level": "runs[].level.code",
    "department": "departments.department_id",
    "platform": "platform.code",
    "offered_by": "offered_by.code",
    "delivery": "delivery[].code",
    "resource_category": "resource_category",
}
