# Generated by Django 4.2.20 on 2025-03-27 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0033_alter_profile_learning_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="scim_external_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="scim_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="scim_username",
        ),
    ]
