# Generated by Django 4.2.20 on 2025-04-07 19:05

from django.db import migrations


def set_completed_onboarding(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.all().update(completed_onboarding=True)


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0035_profile_completed_onboarding"),
    ]

    operations = [migrations.RunPython(set_completed_onboarding)]
