# Generated by Django 4.2.23 on 2025-09-04 19:05

from django.db import migrations, models


def set_has_logged_in(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    for profile in Profile.objects.all():
        if profile.user.last_login is not None:
            profile.has_logged_in = True
            profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0036_set_onboarding_complete_for_existing_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_has_logged_in, reverse_code=migrations.RunPython.noop),
    ]
