# Generated by Django 5.2.16 on 2026-08-25 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0037_profile_has_logged_in"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programcertificate",
            options={"managed": True},
        ),
    ]
