# Generated by Django 5.2.17 on 2026-09-15 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0038_alter_programcertificate_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserWebsite",
        ),
    ]
