# Generated by Django 4.2.18 on 2025-02-05 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_update_user_contenttype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
        migrations.RunSQL(
            sql="CREATE VIEW auth_user AS SELECT * FROM users_user;",
            reverse_sql="DROP VIEW auth_user;",
            elidable=True,
        ),
    ]
