# Generated by Django 4.2.19 on 2025-02-19 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="scim_external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="A string that is an identifier for the resource as defined by the provisioning client.",  # noqa: E501
                max_length=254,
                null=True,
                verbose_name="SCIM External ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scim_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A unique identifier for a SCIM resource as defined by the service provider.",  # noqa: E501
                max_length=254,
                null=True,
                unique=True,
                verbose_name="SCIM ID",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scim_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="A service provider's unique identifier for the user",
                max_length=254,
                null=True,
                verbose_name="SCIM Username",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
