# Generated by Django 4.2.19 on 2025-02-19 16:16
import logging

from django.db import migrations, models

BATCH_SIZE = 10_000

log = logging.getLogger()


def _set_scim_and_timestamps(apps, schema_editor):
    User = apps.get_model("users", "User")
    Profile = apps.get_model("profiles", "Profile")

    query = User.objects.filter(
        id__in=User.objects.filter(scim_id__isnull=True).only("id")[:BATCH_SIZE]
    )

    while num_updates := query.update(
        # this uses the user.id to avoid conflicts with new users
        scim_id=models.F("id"),
        scim_external_id=models.Subquery(
            Profile.objects.filter(user_id=models.OuterRef("id")).values(
                "scim_external_id"
            )[:1]
        ),
        scim_username=models.Subquery(
            Profile.objects.filter(user_id=models.OuterRef("id")).values(
                "scim_username"
            )[:1]
        ),
        # created_on previously got a default of timestamp.now
        # so we update it with the correct date
        created_on=models.F("date_joined"),
        # this would've been null
        updated_on=models.Subquery(
            Profile.objects.filter(user_id=models.OuterRef("id")).values("updated_at")[
                :1
            ]
        ),
    ):
        log.info("Updated %s user records", num_updates)


class Migration(migrations.Migration):
    """
    This is a separate migration from 0004 because for performance reasons
    we don't want to update the entire table in a transaction but we DO
    want the schema changes in 0004 in a transaction.
    """

    atomic = False

    dependencies = [
        ("users", "0004_add_scim_and_timestamp_fields"),
    ]

    # we don't bother to undo these changes because if we're rolling back the columns
    # just get dropped in the previous migration
    operations = [
        migrations.RunPython(_set_scim_and_timestamps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
