# Generated by Django 4.2.19 on 2025-02-19 16:16
import logging

from django.db import migrations, models

BATCH_SIZE = 10_000

log = logging.getLogger()


class Migration(migrations.Migration):
    """
    This is a separate migration from 0004 because for performance reasons
    we don't want to update the entire table in a transaction but we DO
    want the schema changes in 0004 in a transaction.
    """

    atomic = False

    dependencies = [
        ("users", "0004_add_scim_and_timestamp_fields"),
    ]

    # we don't bother to undo these changes because if we're rolling back the columns
    # just get dropped in the previous migration
    operations = [
        migrations.AlterField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
