# Generated by Django 4.2.19 on 2025-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_set_user_scim_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="global_id",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
