# Generated by Django 4.2.19 on 2025-02-24 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_set_user_scim_id"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW auth_user;",
            reverse_sql="CREATE VIEW auth_user AS SELECT * FROM users_user;",
            elidable=True,
        ),
    ]
