# Generated by Django 4.2.19 on 2025-03-07 13:49

from django.db import migrations, models


def transfer_global_id(apps, schema_editor):
    UserSocialAuth = apps.get_model("social_django", "UserSocialAuth")
    User = apps.get_model("users", "User")

    users_with_uid = User.objects.annotate(
        social_uid=models.Subquery(
            UserSocialAuth.objects.filter(
                user=models.OuterRef("pk"),
            ).values("uid")[:1]
        )
    )

    users_with_uid.update(global_id=models.F("social_uid"))


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_set_user_scim_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="global_id",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.RunPython(
            transfer_global_id, reverse_code=migrations.RunPython.noop
        ),
    ]
