# Generated by Django 4.2.19 on 2025-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_global_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="global_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
