# Generated by Django 4.2.19 on 2025-03-11 12:53

import logging

from django.db import migrations, models

log = logging.getLogger(__name__)

BATCH_SIZE = 10_000


def transfer_global_id(apps, schema_editor):
    """Transfer the social uid to the user global_id field"""
    UserSocialAuth = apps.get_model("social_django", "UserSocialAuth")
    User = apps.get_model("users", "User")

    users_with_uid = (
        User.objects.filter(
            id__in=User.objects.filter(global_id__isnull=True).only("id")[:BATCH_SIZE]
        )
        .annotate(
            social_uid=models.Subquery(
                UserSocialAuth.objects.filter(
                    user=models.OuterRef("pk"),
                ).values("uid")[:1]
            )
        )
        .filter(social_uid__isnull=False)
    )

    while num_updates := users_with_uid.update(global_id=models.F("social_uid")):
        log.info("Updated %s user records", num_updates)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("users", "0006_user_global_id"),
    ]

    operations = [
        migrations.RunPython(
            transfer_global_id, reverse_code=migrations.RunPython.noop
        ),
    ]
