# Generated by Django 4.2.20 on 2025-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_global_id_assign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="global_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
