# Generated by Django 4.2.19 on 2025-03-11 12:53

import logging

from django.db import migrations, models

log = logging.getLogger(__name__)

BATCH_SIZE = 10_000


def transfer_global_id(apps, schema_editor):
    """Transfer the scim_external_id to the user global_id field"""
    User = apps.get_model("users", "User")

    users_with_uid = User.objects.filter(
        id__in=User.objects.exclude(scim_external_id__isnull=True)
        .exclude(global_id=models.F("scim_external_id"))
        .only("id")[:BATCH_SIZE]
    )

    while num_updates := users_with_uid.update(global_id=models.F("scim_external_id")):
        log.info("Updated %s user records", num_updates)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("users", "0008_alter_user_global_id"),
    ]

    operations = [
        migrations.RunPython(
            transfer_global_id, reverse_code=migrations.RunPython.noop
        ),
    ]
