# Generated by Django 4.2.30 on 2026-06-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_global_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unsubscribe_uuid",
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
