# Generated by Django 4.2.30 on 2026-08-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_unsubscribe_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_sso_user",
            field=models.BooleanField(
                default=None,
                help_text="Authenticates via an external identity provider, so cannot change their own email or password. Blank until determined from Keycloak.",  # noqa: E501
                null=True,
            ),
        ),
    ]
