# Generated by Django 4.2.25 on 2025-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='html',
        ),
        migrations.AddField(
            model_name='article',
            name='json',
            field=models.JSONField(default={}),
        ),
    ]
