# Generated by Django 4.2.25 on 2025-11-25 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import profiles.utils


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0003_remove_article_html_article_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleImageUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        editable=False,
                        max_length=2083,
                        null=True,
                        upload_to=profiles.utils.article_image_upload_uri,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
