# Generated by Django 4.2.25 on 2025-12-02 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_user"),
        ("articles", "0004_articleimageupload"),
    ]

    operations = []
