# Generated by Django 4.2.25 on 2025-12-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_merge_0004_article_user_0004_articleimageupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
