# Generated by Django 3.1 on 2021-01-28 16:27
from django.contrib.auth.models import Group
from django.db import migrations

from articles import constants


def add_staff_list_group(apps, schema_editor):
    """
    Create the staff list editors group
    """
    Group.objects.get_or_create(name=constants.GROUP_STAFF_ARTICLE_EDITORS)


def remove_staff_list_group(apps, schema_editor):
    """
    Delete the staff list editors group
    """
    Group.objects.filter(name=constants.GROUP_STAFF_ARTICLE_EDITORS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_article_is_published"),
    ]

    operations = [
        migrations.RunPython(add_staff_list_group, remove_staff_list_group),
    ]
