# Generated by Django 4.2.25 on 2025-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0007_add_editors_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
