# Generated by Django 4.2.25 on 2026-01-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
