# Generated by Django 4.2.26 on 2026-01-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0009_article_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.JSONField(default=dict),
        ),
    ]
