# Generated by Django 4.2.25 on 2026-02-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0010_fix_article_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_name",
            field=models.TextField(blank=True, default=""),
        ),
    ]
