# Generated by Django 4.2.25 on 2025-10-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoShort",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "youtube_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("published_at", models.DateTimeField()),
                ("thumbnail_height", models.IntegerField()),
                ("thumbnail_width", models.IntegerField()),
                ("thumbnail_url", models.CharField()),
                ("video_url", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
