# Generated by Django 4.2.26 on 2026-01-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_shorts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoshort",
            old_name="youtube_id",
            new_name="video_id",
        ),
        migrations.RemoveField(
            model_name="videoshort",
            name="description",
        ),
        migrations.RemoveField(
            model_name="videoshort",
            name="thumbnail_height",
        ),
        migrations.RemoveField(
            model_name="videoshort",
            name="thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="videoshort",
            name="thumbnail_width",
        ),
        migrations.AddField(
            model_name="videoshort",
            name="thumbnail_small_url",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="videoshort",
            name="thumbnail_large_url",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="videoshort",
            name="video_url",
            field=models.CharField(blank=True),
        ),
    ]
