# Generated by Django 4.2.28 on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_shorts", "0002_multi_thumbnails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VideoShort",
        ),
    ]
