compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.9.2.cjs
supportedArchitectures:
  os:
  - current
  - linux
  cpu:
  - current
  - x64
  - arm64
  libc:
  - current
  - glibc
enableScripts: false
