"""Typed django-aqueduct settings model for mit-learn.

This file was generated by `manage.py generate_aqueduct_settings` and then
hand-refined. Fields marked DERIVED below are recomputed by a
model_validator and should not be set directly except via the primitives
they are derived from.

Known gaps (left as generated / not modeled further -- see the PR/commit
description for details):
  - CELERY_BEAT_SCHEDULE / CELERY_BEAT_SCHEDULER: contain crontab objects
    and a scheduler class reference that cannot be serialised. They are
    static application config (task schedule), not environment-driven
    settings, so they are intentionally left as `None` here. Do not use
    this settings module for the Celery worker/beat processes until this
    is addressed.
  - LOGGING / NPLUSONE_LOGGER: opaque objects built by
    mitol-django-observability / stdlib logging; left as `None`.
  - ADMINS: shape depends on whether MITOL_ADMIN_EMAIL is set (empty tuple
    vs. a tuple of (name, email) pairs); left loosely typed rather than
    guessing the conditional.
"""

from __future__ import annotations

import datetime
import pathlib
from typing import Any

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class AqueductSettings(BaseSettings):
    """Typed Django settings model.

    Populate from environment variables, YAML, Vault, AWS SSM, or any
    combination by configuring ``model_config`` and the sources below.
    """

    model_config = SettingsConfigDict(
        env_prefix="",
        extra="allow",
    )

    # ===== main.settings =====
    ACCESS_TOKEN_URL: str | None = Field(default=None)
    ADMINS: tuple[Any, ...] = Field(
        default=()
    )  # shape depends on MITOL_ADMIN_EMAIL; see header note
    ADMIN_EMAIL: str = Field(default="")
    ALLOWED_HOSTS: list[Any] = Field(default_factory=lambda: ["*"])
    ALLOWED_REDIRECT_HOSTS: list[Any] = Field(
        default_factory=lambda: ["open.odl.local:8062", "ocw.mit.edu"]
    )
    ANONYMOUS_USER_NAME: Any = Field(
        default=None
    )  # static Guardian setting, not env-derived
    ANYMAIL: dict[str, Any] = Field(
        default_factory=lambda: {
            "MAILGUN_API_KEY": "fake_mailgun_key",
            "MAILGUN_SENDER_DOMAIN": "mailgun.fake.domain",
        }
    )
    APISIX_USERDATA_MAP: dict[str, Any] = Field(
        default_factory=lambda: {
            "users.User": {
                "email": "email",
                "global_id": "sub",
                "username": "preferred_username",
                "first_name": "given_name",
                "last_name": "family_name",
                "name": "name",
                "organizations": "organization",
            },
            "profiles.Profile": {"name": "name", "email_optin": "emailOptIn"},
        }
    )
    APP_BASE_URL: str = Field(default="http://localhost:8063/")
    ASK_MIT_CLIMATE_API_URL: str = Field(
        default="https://climate.mit.edu/feeds/ask-mit-climate"
    )
    AUTHENTICATION_BACKENDS: tuple[str, ...] = Field(
        default=(
            "oauth2_provider.backends.OAuth2Backend",
            "django.contrib.auth.backends.ModelBackend",
            "guardian.backends.ObjectPermissionBackend",
        )
    )
    AUTHORIZATION_URL: str | None = Field(default=None)
    AUTH_USER_MODEL: str = Field(default="users.User")
    AWS_ACCESS_KEY_ID: bool = Field(default=False)
    AWS_QUERYSTRING_AUTH: bool = Field(default=False)
    AWS_S3_CUSTOM_DOMAIN: str | None = Field(default=None)
    AWS_S3_PREFIX: str | None = Field(default=None)
    AWS_SECRET_ACCESS_KEY: bool = Field(default=False)
    AWS_STORAGE_BUCKET_NAME: bool = Field(default=False)
    BASE_DIR: str = Field(
        default_factory=lambda: str(pathlib.Path(__file__).resolve().parent.parent),
        description=(
            "DERIVED — repo root, computed relative to this file (mirrors "
            "main/settings.py's os.path.dirname(os.path.dirname(__file__)))"
        ),
    )
    BLOCKLISTED_COURSES_URL: str = Field(
        default="https://raw.githubusercontent.com/mitodl/open-resource-blocklists/master/courses.txt"
    )
    CACHES: dict[str, Any] = Field(
        default_factory=lambda: {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "external_assets": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "external_asset_cache",
            },
            "durable": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "durable_cache",
            },
            "redis": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": None,
                "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            },
            "imagekit": {
                "BACKEND": "main.cache.backends.FallbackCache",
                "LOCATION": ["imagekit_redis", "imagekit_db"],
            },
            "imagekit_redis": {
                "BACKEND": "main.cache.backends.FallbackCache",
                "LOCATION": ["redis"],
                "TIMEOUT": 3600,
            },
            "imagekit_db": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "imagekit_cache",
                "TIMEOUT": None,
            },
        }
    )
    CANVAS_COURSE_BUCKET_PREFIX: str = Field(default="canvas/course_content")
    CANVAS_TUTORBOT_FOLDER: str = Field(default="web_resources/ai/tutor/")
    CELERY_ACCEPT_CONTENT: list[Any] = Field(default_factory=lambda: ["json"])
    CELERY_BEAT_DISABLED: bool = Field(default=False)
    CELERY_BEAT_SCHEDULE: dict[str, Any] | None = Field(
        default=None
    )  # OPAQUE: original dict value is not serialisable
    CELERY_BEAT_SCHEDULER: Any = Field(
        default=None
    )  # CALLABLE DEFAULT: 'RedBeatScheduler'
    CELERY_BROKER_URL: str | None = Field(
        default=None, description="DERIVED — falls back to REDIS_URL when unset"
    )
    CELERY_RATE_LIMIT: str = Field(default="600/m")
    CELERY_RESULT_BACKEND: str | None = Field(
        default=None, description="DERIVED — falls back to REDIS_URL when unset"
    )
    CELERY_RESULT_SERIALIZER: str = Field(default="json")
    CELERY_SEARCH_RATE_LIMIT: str = Field(default="600/m")
    CELERY_TASK_ALWAYS_EAGER: bool = Field(default=False)
    CELERY_TASK_EAGER_PROPAGATES: bool = Field(default=True)
    CELERY_TASK_SEND_SENT_EVENT: bool = Field(default=True)
    CELERY_TASK_SERIALIZER: str = Field(default="json")
    CELERY_TASK_TASK_TRACK_STARTED: bool = Field(default=True)
    CELERY_TIMEZONE: str = Field(default="UTC")
    CELERY_VECTOR_SEARCH_RATE_LIMIT: str = Field(default="600/m")
    CELERY_WORKER_MAX_MEMORY_PER_CHILD: int = Field(default=250000)
    CKEDITOR_ENVIRONMENT_ID: str | None = Field(default=None)
    CKEDITOR_SECRET_KEY: str | None = Field(default=None)
    CKEDITOR_UPLOAD_URL: str | None = Field(default=None)
    CONTENT_BASE_URL_EDX: str = Field(default="https://courses.edx.org")
    CONTENT_BASE_URL_MITXONLINE: str = Field(
        default="https://courses.mitxonline.mit.edu"
    )
    CONTENT_BASE_URL_OLL: str = Field(default="https://openlearninglibrary.mit.edu")
    CONTENT_BASE_URL_XPRO: str = Field(default="https://courses.xpro.mit.edu")
    CONTENT_FILE_CLEANUP_CHUNK_SIZE: int = Field(default=1000)
    CONTENT_FILE_EMBEDDING_CHUNK_OVERLAP: int = Field(default=0)
    CONTENT_FILE_EMBEDDING_CHUNK_SIZE_OVERRIDE: int = Field(default=512)
    CONTENT_FILE_RETENTION_DAYS: int = Field(default=14)
    CONTENT_FILE_SUMMARIZER_BATCH_SIZE: int = Field(default=20)
    CONTENT_SUMMARIZER_FLASHCARD_PROMPT: str = Field(
        default='\n        You are an expert instructor creating study flashcards.\n        Generate exactly 10\n        high-quality flashcards from the transcript below.\n        \n        Rules:\n        - Use the same language as the transcript for both questions and answers.\n        - Focus ONLY on core concepts, methods, definitions,\n          reasoning, and cause-effect relationships.\n        - Questions must test understanding or application,\n          not recall of names, timestamps, or anecdotes.\n        - Avoid trivia, meta information\n        - avoid details about the speaker or course logistics.\n        - Prefer "why", "how", "compare", "explain", or "apply" style questions.\n        - Each answer should be concise but complete (1-3 sentences).\n\n        Transcript:\n        {content}\n        '  # noqa: E501
    )
    CONTENT_SUMMARIZER_FLASHCARD_QUANTITY: int = Field(default=10)
    COOKIE_TOMBSTONES: Any = Field(
        default="[]",
        description=(
            "DERIVED — raw JSON array of cookie tombstone specs; parsed into "
            "CookieTombstone objects by a model_validator below"
        ),
    )
    CORS_ALLOWED_ORIGINS: list[Any] = Field(default_factory=list)
    CORS_ALLOWED_ORIGIN_REGEXES: list[Any] = Field(default_factory=list)
    CORS_ALLOW_CREDENTIALS: bool = Field(default=True)
    CORS_ALLOW_HEADERS: tuple[str, ...] = Field(
        default=(
            "accept",
            "authorization",
            "content-type",
            "user-agent",
            "x-csrftoken",
            "x-requested-with",
            "baggage",
            "sentry-trace",
        )
    )
    COURSE_ARCHIVE_BUCKET_NAME: str = Field(
        default="ol-data-lake-landing-zone-production"
    )
    CREATE_OCW_LEARNING_MATERIALS: bool = Field(default=False)
    CSAIL_BASE_URL: str | None = Field(default=None)
    CSRF_COOKIE_DOMAIN: str | None = Field(default=None)
    CSRF_COOKIE_NAME: str = Field(default="csrftoken")
    CSRF_COOKIE_SECURE: bool = Field(default=True)
    CSRF_HEADER_NAME: str = Field(default="HTTP_X_CSRFTOKEN")
    CSRF_TRUSTED_ORIGINS: list[Any] = Field(default_factory=list)
    DATABASES: dict[str, Any] = Field(
        default_factory=dict,
        description="DERIVED from DATABASE_URL — see build_databases() below",
    )
    DATABASE_ROUTERS: list[Any] = Field(
        default_factory=lambda: ["main.routers.ExternalSchemaRouter"]
    )
    DATABASE_URL: str | None = Field(
        default=None,
        description=(
            "dj-database-url connection string; defaults to a local sqlite "
            "db under BASE_DIR when unset"
        ),
    )
    DEBUG: bool = Field(default=False)
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_DATABASE_CONFIG: dict[str, Any] = Field(
        default_factory=dict,
        description="DERIVED from DATABASE_URL — see build_databases() below",
    )
    DEFAULT_FROM_EMAIL: str = Field(default="webmaster@localhost")
    DEFAULT_SEARCH_CONTENT_FILE_SCORE_WEIGHT: int = Field(default=1)
    DEFAULT_SEARCH_MAX_INCOMPLETENESS_PENALTY: int = Field(default=90)
    DEFAULT_SEARCH_MINIMUM_SCORE_CUTOFF: int = Field(default=5)
    DEFAULT_SEARCH_MODE: str = Field(default="phrase")
    DEFAULT_SEARCH_SLOP: int = Field(default=6)
    DEFAULT_SEARCH_STALENESS_PENALTY: float = Field(default=2.5)
    DENSE_VECTOR_SEARCH_MIN_SCORE: float = Field(default=0.3)
    DEV_ENV: bool = Field(default=False)
    DISABLE_APISIX_USER_MIDDLEWARE: bool = Field(default=False)
    DJANGO_LOG_LEVEL: str = Field(default="INFO")
    DRF_NESTED_PARENT_LOOKUP_PREFIX: str = Field(default="")
    DUPLICATE_COURSES_URL: str | None = Field(default=None)
    EDX_ALT_URL: str = Field(default="https://courses.edx.org/")
    EDX_API_ACCESS_TOKEN_URL: str | None = Field(default=None)
    EDX_API_CLIENT_ID: str | None = Field(default=None)
    EDX_API_CLIENT_SECRET: str | None = Field(default=None)
    EDX_API_URL: str | None = Field(default=None)
    EDX_BASE_URL: str = Field(default="https://www.edx.org/")
    EDX_COURSE_BUCKET_PREFIX: str = Field(
        default="edxorg-raw-data/edxorg/raw_data/course_xml/"
    )
    EDX_PROGRAMS_API_URL: str | None = Field(default=None)
    EMAIL_BACKEND: str = Field(default="django.core.mail.backends.smtp.EmailBackend")
    EMAIL_HOST: str = Field(default="localhost")
    EMAIL_HOST_PASSWORD: str = Field(default="")
    EMAIL_HOST_USER: str = Field(default="")
    EMAIL_PORT: int = Field(default=25)
    EMAIL_SUPPORT: str = Field(default="support@example.com")
    EMAIL_USE_TLS: bool = Field(default=False)
    EMBEDDINGS_EXTERNAL_FETCH_USE_WEBDRIVER: bool = Field(default=False)
    EMBEDDING_SCHEDULE_MINUTES: int = Field(default=60)
    ENVIRONMENT: str = Field(default="dev")
    EXTERNAL_MODELS: list[Any] = Field(default_factory=lambda: ["programcertificate"])
    FASTLY_API_KEY: str = Field(default="")
    FASTLY_URL: str = Field(default="https://api.fastly.com")
    FEATURES: dict[str, Any] = Field(default_factory=dict)
    GA_G_TRACKING_ID: str = Field(default="")
    GA_TRACKING_ID: str = Field(default="")
    GITHUB_ACCESS_TOKEN: str | None = Field(default=None)
    HEALTH_CHECK: dict[str, Any] = Field(
        default_factory=lambda: {
            "SUBSETS": {
                "startup": [
                    "MigrationsHealthCheck",
                    "CacheBackend",
                    "RedisHealthCheck",
                    "DatabaseHeartBeatCheck",
                ],
                "liveness": ["DatabaseHeartBeatCheck"],
                "readiness": [
                    "CacheBackend",
                    "RedisHealthCheck",
                    "DatabaseHeartBeatCheck",
                ],
                "full": [
                    "MigrationsHealthCheck",
                    "CacheBackend",
                    "RedisHealthCheck",
                    "DatabaseHeartBeatCheck",
                    "CeleryPingHealthCheck",
                ],
            },
            "DISK_USAGE_MAX": 90,
            "MEMORY_MIN": 100,
            "WARNINGS_AS_ERRORS": True,
            "DISABLE_THREADING": False,
        }
    )
    HOSTNAME: str = Field(default="ikoria")
    HYBRID_VECTOR_SEARCH_MIN_SCORE: float = Field(default=0.1)
    IMAGEKIT_CACHEFILE_DIR: str = Field(default="")
    IMAGEKIT_CACHE_BACKEND: str = Field(default="imagekit")
    IMAGEKIT_SPEC_CACHEFILE_NAMER: str = Field(
        default="imagekit.cachefiles.namers.source_name_dot_hash"
    )
    INDEXING_ERROR_RETRIES: int = Field(default=1)
    INSTALLED_APPS: tuple[str, ...] = Field(
        default=(
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "django.contrib.humanize",
            "django.contrib.sites",
            "django_removals",
            "django_scim",
            "social_django",
            "server_status",
            "rest_framework",
            "corsheaders",
            "anymail",
            "guardian",
            "imagekit",
            "django_json_widget",
            "django_filters",
            "drf_spectacular",
            "mitol.observability.apps.ObservabilityConfig",
            "main",
            "users.apps.UsersConfig",
            "authentication",
            "channels",
            "profiles",
            "webhooks",
            "widgets",
            "learning_resources",
            "learning_resources_search",
            "website_content.apps.WebsiteContentConfig",
            "openapi",
            "oauth2_provider",
            "news_events",
            "testimonials",
            "data_fixtures",
            "vector_search",
            "ol_hubspot",
            "mitol.scim.apps.ScimApp",
            "health_check",
            "health_check.cache",
            "health_check.contrib.migrations",
            "health_check.contrib.celery_ping",
            "health_check.contrib.redis",
            "health_check.contrib.db_heartbeat",
        )
    )  # DERIVED — mutated below to conditionally add zeal/nplusone apps
    INTERNAL_IPS: tuple[str, ...] = Field(default=("127.0.0.1",))
    JWT_AUTH: dict[str, Any] = Field(
        default_factory=lambda: {
            "JWT_SECRET_KEY": "terribly_unsafe_default_jwt_secret_key",
            "JWT_VERIFY": True,
            "JWT_VERIFY_EXPIRATION": True,
            "JWT_EXPIRATION_DELTA": datetime.timedelta(seconds=3600),
            "JWT_ALLOW_REFRESH": True,
            "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7),
            "JWT_AUTH_COOKIE": "cookie_monster",
            "JWT_AUTH_HEADER_PREFIX": "Bearer",
        }
    )
    KEYCLOAK_BASE_URL: str = Field(default="http://mit-keycloak-base-url.edu")
    KEYCLOAK_REALM_NAME: str = Field(default="olapps")
    LANGUAGE_CODE: str = Field(default="en-us")
    LEARNING_COURSE_ITERATOR_CHUNK_SIZE: int = Field(default=20)
    LITELLM_API_BASE: str | None = Field(default=None)
    LITELLM_CUSTOM_PROVIDER: str = Field(default="openai")
    LITELLM_TOKEN_ENCODING_NAME: str | None = Field(default=None)
    LOGGING: dict[str, Any] | None = Field(
        default=None
    )  # OPAQUE: original dict value is not serialisable
    LOGIN_ERROR_URL: str = Field(default="/login")
    LOGIN_REDIRECT_URL: str = Field(default="/app")
    LOGIN_URL: str = Field(default="/login")
    LOGOUT_REDIRECT_URL: str = Field(default="/app")
    LOG_LEVEL: str = Field(default="INFO")
    MAILGUN_BCC_TO_EMAIL: str | None = Field(default=None)
    MAILGUN_FROM_EMAIL: str = Field(default="no-reply@example.com")
    MAILGUN_KEY: str = Field(default="fake_mailgun_key")
    MAILGUN_RECIPIENT_OVERRIDE: str | None = Field(default=None)
    MAILGUN_SENDER_DOMAIN: str = Field(default="mailgun.fake.domain")
    MAX_S3_GET_ITERATIONS: int = Field(default=3)
    MEDIA_ROOT: str = Field(default="/var/media/")
    MEDIA_URL: str = Field(default="/media/")
    MICROMASTERS_CATALOG_API_URL: str | None = Field(default=None)
    MICROMASTERS_CMS_API_URL: str | None = Field(default=None)
    MIDDLEWARE: tuple[str, ...] = Field(
        default=(
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "main.middleware.apisix_user.ApisixUserMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "corsheaders.middleware.CorsMiddleware",
            "authentication.middleware.BlockedIPMiddleware",
            "oauth2_provider.middleware.OAuth2TokenMiddleware",
            "django_scim.middleware.SCIMAuthCheckMiddleware",
        )
    )  # DERIVED — mutated below to conditionally add middleware
    MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS: int = Field(default=3600)
    MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME: str = Field(default="MITOL_FEATURE_FLAGS")
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: str | None = Field(default=None)
    MIGRATION_MODULES: dict[str, Any] = Field(
        default_factory=lambda: {"data_fixtures": None}
    )
    MITOL_API_BASE_URL: str = Field(default="")
    MITOL_AUTHENTICATION_PLUGINS: str = Field(
        default="learning_resources.plugins.FavoritesListPlugin,profiles.plugins.CreateProfilePlugin"
    )
    MITOL_COOKIE_DOMAIN: str = Field(default="od.fake.domain")
    MITOL_COOKIE_NAME: str = Field(default="cookie_monster")
    MITOL_DB_CONN_MAX_AGE: int = Field(default=0)
    MITOL_DB_DISABLE_SSL: bool = Field(default=False)
    MITOL_DB_DISABLE_SS_CURSORS: bool = Field(default=True)
    MITOL_FEATURES_DEFAULT: bool = Field(default=False)
    MITOL_FEATURES_PREFIX: str = Field(default="FEATURE_")
    MITOL_HUBSPOT_API_PRIVATE_TOKEN: str | None = Field(default=None)
    MITOL_JWT_SECRET: str = Field(default="terribly_unsafe_default_jwt_secret_key")
    MITOL_LEARNING_RESOURCES_PLUGINS: str = Field(
        default="learning_resources_search.plugins.SearchIndexPlugin,channels.plugins.ChannelPlugin"
    )
    MITOL_NEW_USER_LOGIN_URL: str = Field(
        default="http://open.odl.local:8062/onboarding"
    )
    MITOL_SIMILAR_RESOURCES_COUNT: int = Field(default=3)
    MITOL_TITLE: str = Field(default="MIT Learn")
    MITOL_TOS_URL: str = Field(default="http://localhost:8063/terms-and-conditions/")
    MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS: int = Field(default=604800)
    MITOL_USE_S3: bool = Field(default=False)
    MITOL_WEBSITE_CONTENT_PLUGINS: str = Field(
        default="news_events.plugins.WebsiteContentNewsPlugin"
    )
    MITPE_BASE_URL: str = Field(default="https://professional.mit.edu/")
    MITX_ONLINE_BASE_URL: str | None = Field(default=None)
    MITX_ONLINE_COURSES_API_URL: str | None = Field(default=None)
    MITX_ONLINE_COURSE_BUCKET_PREFIX: str = Field(
        default="mitxonline/openedx/raw_data/course_xml/"
    )
    MITX_ONLINE_PROGRAMS_API_URL: str | None = Field(default=None)
    MIT_CLIMATE_BASE_URL: str = Field(default="https://climate.mit.edu")
    MIT_CLIMATE_EXPLAINERS_API_URL: str = Field(
        default="https://climate.mit.edu/feeds/explainers"
    )
    MIT_WS_CERTIFICATE_FILE: str = Field(default="staticfiles/mit_x509.cert")
    MIT_WS_PRIVATE_KEY_FILE: str = Field(default="staticfiles/mit_x509.key")
    NOTIFICATION_ATTEMPT_CHUNK_SIZE: int = Field(default=100)
    NOTIFICATION_ATTEMPT_RATE_LIMIT: str = Field(default="600/m")
    NOTIFICATION_EMAIL_BACKEND: str = Field(
        default="anymail.backends.test.EmailBackend"
    )
    NPLUSONE_LOGGER: Any = Field(
        default=None
    )  # OPAQUE: original Logger value is not serialisable
    NPLUSONE_LOG_LEVEL: int = Field(default=40)
    OCR_DEBUG_DIRECTORY: str = Field(default="ocr_debug")
    OCR_MATH_DENSITY_THRESHOLD: int = Field(default=5)
    OCR_MODEL: str | None = Field(default=None)
    OCR_PDF_MAX_PAGE_THRESHOLD: int = Field(default=10)
    OCR_PROMPT: str = Field(
        default="Transcribe this image to markdown. Properly format text, formulas, tables, and code into markdown format.Include a markdown comment for elements that cannot be transcribed such as photos and other visual elements.Do not include any indications your output is the result of a transcription.Do not include extra commentary - ONLY include the resulting transcribed markdown."  # noqa: E501
    )
    OCW_BASE_URL: str = Field(default="http://ocw.mit.edu/")
    OCW_ITERATOR_CHUNK_SIZE: int = Field(default=1000)
    OCW_LIVE_BUCKET: str | None = Field(default=None)
    OCW_OFFLINE_DELIVERY: bool = Field(default=False)
    OCW_SKIP_CONTENT_FILES: bool = Field(default=False)
    OCW_WEBHOOK_KEY: str | None = Field(default=None)
    OIDC_LOGOUT_URL: str = Field(default="/logout/oidc")
    OLL_COURSE_BUCKET_PREFIX: str = Field(default="open-learning-library/courses")
    OPENAI_API_KEY: str | None = Field(default=None)
    OPENSEARCH_CONNECTIONS_PER_NODE: int = Field(default=10)
    OPENSEARCH_DEFAULT_PAGE_SIZE: int = Field(default=10)
    OPENSEARCH_DEFAULT_TIMEOUT: int = Field(default=10)
    OPENSEARCH_DOCUMENT_INDEXING_CHUNK_SIZE: int = Field(default=100)
    OPENSEARCH_HTTP_AUTH: str | None = Field(default=None)
    OPENSEARCH_INDEX: str = Field(default="some_index")
    OPENSEARCH_INDEXING_CHUNK_SIZE: int = Field(default=100)
    OPENSEARCH_MAX_REQUEST_SIZE: int = Field(default=10485760)
    OPENSEARCH_MAX_SUGGEST_HITS: int = Field(default=1)
    OPENSEARCH_MAX_SUGGEST_RESULTS: int = Field(default=1)
    OPENSEARCH_MIN_QUERY_SIZE: int = Field(default=2)
    OPENSEARCH_REPLICA_COUNT: int = Field(default=2)
    OPENSEARCH_SHARD_COUNT: int = Field(default=2)
    OPENSEARCH_URL: str = Field(default="http://localhost:9300/")
    OPENSEARCH_VECTOR_MODEL_BASE_NAME: str = Field(default="hybrid_search_model")
    OPENTELEMETRY_ENABLED: bool = Field(default=False)
    OPENTELEMETRY_ENDPOINT: str | None = Field(default=None)
    OPENTELEMETRY_EXPORT_TIMEOUT_MS: int = Field(default=5000)
    OPENTELEMETRY_INSECURE: bool = Field(default=True)
    OPENTELEMETRY_SERVICE_NAME: str = Field(default="learn")
    OPENTELEMETRY_TRACES_BATCH_SIZE: int = Field(default=512)
    OPEN_AI_EMBEDDING_MODELS: list[Any] = Field(
        default_factory=lambda: ["text-embedding-3-small", "text-embedding-3-large"]
    )
    OPEN_PODCAST_DATA_BRANCH: str = Field(default="master")
    OPEN_RESOURCES_MIN_DOC_FREQ: int = Field(default=1)
    OPEN_RESOURCES_MIN_TERM_FREQ: int = Field(default=1)
    OPEN_VIDEO_DATA_BRANCH: str = Field(default="master")
    OPEN_VIDEO_MAX_TOPICS: int = Field(default=2)
    OPEN_VIDEO_MIN_DOC_FREQ: int = Field(default=15)
    OPEN_VIDEO_MIN_TERM_FREQ: int = Field(default=1)
    OPEN_VIDEO_USER_LIST_OWNER: str | None = Field(default=None)
    OS_LOG_LEVEL: str = Field(default="INFO")
    OVS_API_BASE_URL: str | None = Field(default=None)
    POSTHOG_API_HOST: str = Field(default="https://us.posthog.com")
    POSTHOG_EVENT_S3_BUCKET: str = Field(default="None")
    POSTHOG_EVENT_S3_PREFIX: str = Field(default="None")
    POSTHOG_PERSONAL_API_KEY: str | None = Field(default=None)
    POSTHOG_PROJECT_API_KEY: str = Field(default="")
    POSTHOG_PROJECT_ID: int | None = Field(default=None)
    POSTHOG_TIMEOUT_MS: int = Field(default=3000)
    QDRANT_API_KEY: str = Field(default="")
    QDRANT_BASE_COLLECTION_NAME: str = Field(default="resource_embeddings")
    QDRANT_BATCH_SIZE_BYTES: int = Field(default=10485760)
    QDRANT_CHUNK_SIZE: int = Field(default=10)
    QDRANT_CLIENT_TIMEOUT: int = Field(default=10)
    QDRANT_DENSE_MODEL: str | None = Field(default=None)
    QDRANT_EMBEDDINGS_TASK_LOOKBACK_WINDOW: int = Field(
        default=120,
        description=(
            "DERIVED — always EMBEDDING_SCHEDULE_MINUTES + 60, see "
            "build_qdrant_lookback_window() below"
        ),
    )
    QDRANT_ENABLE_INDEXING_PLUGIN_HOOKS: bool = Field(default=False)
    QDRANT_ENCODER: str = Field(default="vector_search.encoders.gensim.GensimEncoder")
    QDRANT_HOST: str = Field(default="http://qdrant:6333")
    QDRANT_POINT_UPLOAD_BATCH_SIZE: int = Field(default=1000)
    QDRANT_QUERY_EMBEDDING_CACHE_TTL: int = Field(default=604800)
    QDRANT_SPARSE_ENCODER: str = Field(
        default="vector_search.encoders.sparse_hash.SparseHashEncoder"
    )
    QDRANT_SPARSE_MODEL: str = Field(default="sklearn/hashing_vectorizer_sparse_model")
    REACT_GA_DEBUG: bool = Field(default=False)
    RECAPTCHA_SECRET_KEY: str = Field(default="")
    RECAPTCHA_SITE_KEY: str = Field(default="")
    REDIS_URL: str | None = Field(
        default=None, description="DERIVED — falls back to REDISCLOUD_URL when unset"
    )
    REDIS_VIEW_CACHE_DURATION: int = Field(default=86400)
    REDISCLOUD_URL: str | None = Field(
        default=None,
        description="Legacy Heroku-style Redis URL; used as a REDIS_URL fallback",
    )
    REQUESTS_TIMEOUT: int = Field(default=30)
    REST_FRAMEWORK: dict[str, Any] = Field(
        default_factory=lambda: {
            "DEFAULT_PERMISSION_CLASSES": (
                "rest_framework.permissions.IsAuthenticated",
            ),
            "DEFAULT_AUTHENTICATION_CLASSES": (
                "rest_framework.authentication.SessionAuthentication",
            ),
            "DEFAULT_PAGINATION_CLASS": "main.pagination.DefaultPagination",
            "EXCEPTION_HANDLER": "main.exceptions.api_exception_handler",
            "TEST_REQUEST_DEFAULT_FORMAT": "json",
            "TEST_REQUEST_RENDERER_CLASSES": [
                "rest_framework.renderers.JSONRenderer",
                "rest_framework.renderers.MultiPartRenderer",
            ],
            "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
            "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
            "ALLOWED_VERSIONS": ["v0", "v1"],
            "ORDERING_PARAM": "sortby",
        }
    )
    REST_FRAMEWORK_EXTENSIONS: dict[str, Any] = Field(
        default_factory=lambda: {"DEFAULT_PARENT_LOOKUP_KWARG_NAME_PREFIX": ""}
    )
    ROOT_URLCONF: str = Field(default="main.urls")
    RSS_FEED_CACHE_MINUTES: int = Field(default=15)
    RSS_FEED_EPISODE_LIMIT: int = Field(default=100)
    SCIM_SERVICE_PROVIDER: dict[str, Any] = Field(
        default_factory=lambda: {
            "SCHEME": "https",
            "NETLOC": "localhost",
            "AUTHENTICATION_SCHEMES": [
                {
                    "type": "oauth2",
                    "name": "OAuth 2",
                    "description": "Oauth 2 implemented with bearer token",
                    "specUri": "",
                    "documentationUri": "",
                }
            ],
            "SERVICE_PROVIDER_CONFIG_MODEL": (
                "mitol.scim.config.LearnSCIMServiceProviderConfig"
            ),
            "USER_ADAPTER": "users.adapters.LearnUserAdapter",
            "USER_MODEL_GETTER": "mitol.scim.adapters.get_user_model_for_scim",
            "USER_FILTER_PARSER": "mitol.scim.filters.UserFilterQuery",
            "GET_IS_AUTHENTICATED_PREDICATE": (
                "mitol.scim.utils.is_authenticated_predicate"
            ),
        }
    )
    SEARCH_PROGRAM_INDEX_BOOST: int = Field(default=3)
    SECRET_KEY: str = Field(
        description="Django secret key. Required — no default; the previous "
        "hardcoded fallback ('terribly_unsafe_default_secret_key') was a "
        "security bug and is intentionally not reproduced here."
    )
    SECURE_CROSS_ORIGIN_OPENER_POLICY: str = Field(default="same-origin")
    SECURE_REDIRECT_EXEMPT: list[Any] = Field(
        default_factory=lambda: [
            "^health/startup/$",
            "^health/liveness/$",
            "^health/readiness/$",
            "^health/full/$",
        ]
    )
    SECURE_SSL_REDIRECT: bool = Field(default=True)
    SEE_API_ACCESS_TOKEN_URL: str | None = Field(default=None)
    SEE_API_CLIENT_ID: str | None = Field(default=None)
    SEE_API_CLIENT_SECRET: str | None = Field(default=None)
    SEE_API_URL: str | None = Field(default=None)
    SEE_BASE_URL: str | None = Field(default=None)
    SENTRY_DSN: str = Field(default="")
    SENTRY_LOG_LEVEL: str = Field(default="ERROR")
    SENTRY_PROFILES_SAMPLE_RATE: int = Field(default=0)
    SENTRY_TRACES_SAMPLE_RATE: int = Field(default=0)
    SESSION_COOKIE_DOMAIN: str | None = Field(default=None)
    SESSION_COOKIE_NAME: str = Field(default="sessionid")
    SESSION_ENGINE: str = Field(
        default="django.contrib.sessions.backends.signed_cookies"
    )
    SITE_ID: int = Field(default=1)
    SKIP_TIKA: bool = Field(default=False)
    SPECTACULAR_SETTINGS: dict[str, Any] = Field(
        default_factory=lambda: {
            "TITLE": "MIT Learn API",
            "DESCRIPTION": "MIT public API",
            "VERSION": "0.0.1",
            "SERVE_INCLUDE_SCHEMA": False,
            "SERVE_URLCONF": "main.urls",
            "ENUM_GENERATE_CHOICE_DESCRIPTION": True,
            "COMPONENT_SPLIT_REQUEST": True,
            "AUTHENTICATION_WHITELIST": [],
            "SCHEMA_PATH_PREFIX": "/api/v[0-9]",
            "POSTPROCESSING_HOOKS": [
                "drf_spectacular.hooks.postprocess_schema_enums",
                "openapi.hooks.postprocess_x_enum_descriptions",
            ],
        }
    )
    STATIC_ROOT: str = Field(default="staticfiles")
    STATIC_URL: str = Field(default="/static/")
    STATUS_TOKEN: str = Field(default="")
    TEMPLATES: list[Any] = Field(
        default_factory=list,
        description="DERIVED from BASE_DIR — see build_templates() below",
    )
    TIKA_ACCESS_TOKEN: str | None = Field(default=None)
    TIKA_OCR_STRATEGY: str = Field(default="no_ocr")
    TIKA_TIMEOUT: int = Field(default=60)
    TIME_ZONE: str = Field(default="UTC")
    USERINFO_URL: str | None = Field(default=None)
    USE_CELERY: bool = Field(default=True)
    USE_I18N: bool = Field(default=True)
    USE_L10N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_X_FORWARDED_HOST: bool = Field(default=False)
    USE_X_FORWARDED_PORT: bool = Field(default=False)
    VECTOR_HYBRID_SEARCH_PREFETCH_MAX_LIMIT: int = Field(default=500)
    VECTOR_HYBRID_SEARCH_PREFETCH_MULTIPLIER: int = Field(default=5)
    VECTOR_SEARCH_PAGE_MAX_LIMIT: int = Field(default=200)
    VERSION: str = Field(default="0.72.3")
    WEBDRIVER_WAIT_SECONDS: int = Field(default=10)
    WEBHOOK_SECRET: str = Field(
        description="Webhook shared secret. Required — no default; the previous "
        "hardcoded fallback ('please-change-this') was a security bug and is "
        "intentionally not reproduced here."
    )
    WIDGETS_RSS_CACHE_TTL: int = Field(default=900)
    WSGI_APPLICATION: str = Field(default="main.wsgi.application")
    XPRO_CATALOG_API_URL: str | None = Field(default=None)
    XPRO_COURSES_API_URL: str | None = Field(default=None)
    XPRO_COURSE_BUCKET_PREFIX: str = Field(default="xpro/openedx/raw_data/course_xml/")
    YOUTUBE_CONFIG_URL: str | None = Field(default=None)
    YOUTUBE_DEVELOPER_KEY: str | None = Field(default=None)
    ZEAL_ALLOWLIST: list[Any] = Field(default_factory=list)
    ZEAL_ENABLE: bool = Field(default=False)
    ZEAL_RAISE: bool = Field(default=False)

    # ===== mitol.common.envs =====
    MITOL_SCIM_KEYCLOAK_BASE_URL: str | None = Field(
        default=None, description="The base url for the upstream Keycloak service"
    )
    MITOL_SCIM_KEYCLOAK_BATCH_SIZE: int = Field(
        default=250,
        description="Number of operations to send in a single batch request",
    )
    MITOL_SCIM_KEYCLOAK_BULK_OPERATIONS_COUNT: int = Field(
        default=250, description="Number of operations to perform per bulk request"
    )
    MITOL_SCIM_KEYCLOAK_CLIENT_ID: str | None = Field(
        default=None, description="The client id for the Keycloak service"
    )
    MITOL_SCIM_KEYCLOAK_CLIENT_SECRET: str | None = Field(
        default=None, description="The client secret for the Keycloak service"
    )
    MITOL_SCIM_KEYCLOAK_SEARCH_BATCH_SIZE: int = Field(
        default=100,
        description="Number of operations to send in a single search request",
    )
    MITOL_SCIM_REQUESTS_TIMEOUT_SECONDS: int = Field(
        default=60, description="Number of seconds to timeout requests to Keycloak"
    )

    # ------------------------------------------------------------------ #
    # Derived settings                                                    #
    # ------------------------------------------------------------------ #
    # Validators run in the order they are defined below (pydantic v2
    # executes same-mode "after" validators in definition order), which
    # matters here: build_cookie_tombstones() must run before
    # build_conditional_apps_and_middleware() reads self.COOKIE_TOMBSTONES.

    @model_validator(mode="after")
    def build_redis_urls(self) -> AqueductSettings:
        """Mirror main/settings_celery.py's Redis URL fallback chain.

        ``REDIS_URL`` falls back to the legacy Heroku ``REDISCLOUD_URL``, and
        both Celery URLs fall back to ``REDIS_URL`` when not set explicitly.
        """
        self.REDIS_URL = self.REDIS_URL or self.REDISCLOUD_URL
        self.CELERY_BROKER_URL = self.CELERY_BROKER_URL or self.REDIS_URL
        self.CELERY_RESULT_BACKEND = self.CELERY_RESULT_BACKEND or self.REDIS_URL
        self.CACHES["redis"]["LOCATION"] = self.CELERY_BROKER_URL
        return self

    @model_validator(mode="after")
    def build_qdrant_lookback_window(self) -> AqueductSettings:
        """Mirror settings_celery.py: lookback is 60 min more than the schedule."""
        self.QDRANT_EMBEDDINGS_TASK_LOOKBACK_WINDOW = (
            self.EMBEDDING_SCHEDULE_MINUTES + 60
        )
        return self

    @model_validator(mode="after")
    def build_databases(self) -> AqueductSettings:
        """Mirror main/settings.py's DATABASES/DEFAULT_DATABASE_CONFIG construction."""
        import dj_database_url

        database_url = self.DATABASE_URL or f"sqlite:///{self.BASE_DIR}/db.sqlite3"
        config = dj_database_url.parse(database_url)
        config["DISABLE_SERVER_SIDE_CURSORS"] = self.MITOL_DB_DISABLE_SS_CURSORS
        config["CONN_MAX_AGE"] = self.MITOL_DB_CONN_MAX_AGE
        config["OPTIONS"] = {} if self.MITOL_DB_DISABLE_SSL else {"sslmode": "require"}
        self.DEFAULT_DATABASE_CONFIG = config
        self.DATABASES = {"default": config}
        return self

    @model_validator(mode="after")
    def build_templates(self) -> AqueductSettings:
        """Mirror main/settings.py's TEMPLATES, which references BASE_DIR."""
        self.TEMPLATES = [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [f"{self.BASE_DIR}/templates/"],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                    ]
                },
            }
        ]
        return self

    @model_validator(mode="after")
    def build_cookie_tombstones(self) -> AqueductSettings:
        """Mirror main/settings.py's ``parse_cookie_tombstones(...)`` call."""
        from main.middleware.cookie_tombstones import (
            parse_cookie_tombstones,
        )

        if isinstance(self.COOKIE_TOMBSTONES, str):
            self.COOKIE_TOMBSTONES = parse_cookie_tombstones(self.COOKIE_TOMBSTONES)
        return self

    @model_validator(mode="after")
    def build_conditional_apps_and_middleware(self) -> AqueductSettings:
        """Mirror the conditional INSTALLED_APPS/MIDDLEWARE mutations in settings.py.

        In textual order: the zeal profiler (debug or pytest), the cookie
        tombstone middleware (only when tombstones are configured), the
        nplusone profiler (debug only), and the feature-flag middleware
        (only when a query-string prefix is configured).
        """
        installed_apps = list(self.INSTALLED_APPS)
        middleware = list(self.MIDDLEWARE)

        if self.ZEAL_ENABLE or self.ENVIRONMENT == "pytest":
            installed_apps.append("zeal")
            middleware.append("zeal.middleware.zeal_middleware")

        if self.COOKIE_TOMBSTONES:
            middleware.insert(
                0, "main.middleware.cookie_tombstones.CookieTombstoneMiddleware"
            )

        if self.DEBUG:
            installed_apps.append("nplusone.ext.django")
            middleware.append("nplusone.ext.django.NPlusOneMiddleware")

        if self.MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
            middleware.append(
                "main.middleware.feature_flags.QueryStringFeatureFlagMiddleware"
            )
            middleware.append(
                "main.middleware.feature_flags.CookieFeatureFlagMiddleware"
            )

        self.INSTALLED_APPS = tuple(installed_apps)
        self.MIDDLEWARE = tuple(middleware)
        return self


class DevAqueductSettings(AqueductSettings):
    """Local-dev variant: fills missing values from Vault via OIDC, not a .env file."""

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,  # noqa: ARG003
        file_secret_settings,  # noqa: ARG003
    ):
        """Prepend a Vault OIDC source so missing values are fetched interactively."""
        import os

        from django_aqueduct.sources.vault import VaultSettingsSource

        # NOTE: VAULT_AQUEDUCT_PATH and the "mitlearn" OIDC role default below
        # are placeholders — confirm the real KV path and role against the
        # live Vault instance (e.g. `vault kv list secret-mitlearn/`) before
        # relying on this in practice. The mount point ("secret-mitlearn")
        # and kv_version ("2") come from the background note that mit-learn's
        # Vault mount is KV-v2.
        return (
            init_settings,
            env_settings,
            VaultSettingsSource(
                settings_cls,
                vault_url=os.environ["VAULT_ADDR"],
                vault_path=os.environ.get("VAULT_AQUEDUCT_PATH", ""),
                mount_point="secret-mitlearn",
                kv_version="2",
                auth_method="oidc",
                role=os.environ.get("VAULT_AQUEDUCT_ROLE", "mitlearn"),
            ),
        )
