# ruff: noqa
# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.


# >>> aqueduct:generated:imports
from __future__ import annotations

import ast
import json
import logging
import platform

from main.envs import get_int, get_list_of_str, get_string
from main.middleware.cookie_tombstones import parse_cookie_tombstones
from openapi.settings_spectacular import open_spectacular_settings
from pydantic import AliasChoices, AnyUrl, Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict
from redbeat import RedBeatScheduler
from typing import Annotated, Any
# <<< aqueduct:generated:imports

# --- Hand-written imports (outside generated regions; survive regeneration) ---
import ast
import datetime
import json
import os
from typing import Annotated
from urllib.parse import urljoin

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from django_aqueduct import derivations as dv
from django_aqueduct.sources.dev import VaultDevBase
from mitol.scim.settings.scim import SCIM_SERVICE_PROVIDER as MITOL_SCIM_SERVICE_PROVIDER
from pydantic import field_validator, model_validator
from pydantic_settings import NoDecode

from main.envs import get_bool


def _parse_env_str_list(value: object) -> object:
    """Parse a list from a JSON, Python-literal, or comma-separated env string.

    Mirrors the generator's own ``_aqueduct_decode_list_fields`` decoder — used
    for the ``get_list_of_str`` fields the generator can't cover (see the
    override block below).
    """
    if not isinstance(value, str):
        return value
    try:
        parsed = json.loads(value)
    except (ValueError, TypeError):
        try:
            parsed = ast.literal_eval(value)
        except (ValueError, SyntaxError):
            parsed = None
    if isinstance(parsed, list):
        return parsed
    return [item.strip() for item in value.split(",")]


class AqueductSettings(BaseSettings):
    """Typed Django settings model generated by django-aqueduct."""

    model_config = SettingsConfigDict(env_prefix="", extra="allow")

    # >>> aqueduct:generated:fields
    # ===== main.settings =====
    ACCESS_TOKEN_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('ACCESS_TOKEN_URL'))  # REDACTED: name looks secret-like — set via a source, not here
    ADMINS: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ADMIN_EMAIL: str = Field(default='', validation_alias=AliasChoices('MITOL_ADMIN_EMAIL'), description='e-mail configurable admins')
    ALLOWED_HOSTS: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ['*'])
    ALLOWED_REDIRECT_HOSTS: Any = Field(default_factory=lambda: get_list_of_str(
    "ALLOWED_REDIRECT_HOSTS",
    [
        "open.odl.local:8062",
        "ocw.mit.edu",
    ],
))  # TODO: refine type
    ANONYMOUS_USER_NAME: Any = Field(default=None, description='Guardian\ndisable the anonymous user creation')  # TODO: refine type
    ANYMAIL: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    APISIX_USERDATA_MAP: Annotated[dict[str, Any], NoDecode] = Field(default_factory=lambda: {'users.User': {'email': 'email', 'global_id': 'sub', 'username': 'preferred_username', 'first_name': 'given_name', 'last_name': 'family_name', 'name': 'name', 'organizations': 'organization'}, 'profiles.Profile': {'name': 'name', 'email_optin': 'emailOptIn'}})
    APP_BASE_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('MITOL_APP_BASE_URL'))  # TODO: refine type
    AUTHENTICATION_BACKENDS: tuple[Any, ...] = Field(default=('oauth2_provider.backends.OAuth2Backend', 'django.contrib.auth.backends.ModelBackend', 'guardian.backends.ObjectPermissionBackend'))  # TODO: refine type
    AUTHORIZATION_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('AUTHORIZATION_URL'))  # TODO: refine type
    AUTH_USER_MODEL: str = Field(default='users.User')
    AWS_ACCESS_KEY_ID: str | None = Field(default=None, validation_alias=AliasChoices('AWS_ACCESS_KEY_ID'))  # REDACTED: name looks secret-like — set via a source, not here
    AWS_QUERYSTRING_AUTH: str = Field(default=False, validation_alias=AliasChoices('AWS_QUERYSTRING_AUTH'))
    AWS_S3_CUSTOM_DOMAIN: str | None = Field(default=None, validation_alias=AliasChoices('AWS_S3_CUSTOM_DOMAIN'))
    AWS_S3_PREFIX: str | None = Field(default=None, validation_alias=AliasChoices('AWS_S3_PREFIX'))
    AWS_SECRET_ACCESS_KEY: str | None = Field(default=None, validation_alias=AliasChoices('AWS_SECRET_ACCESS_KEY'))  # REDACTED: name looks secret-like — set via a source, not here
    AWS_STORAGE_BUCKET_NAME: str = Field(default=False, validation_alias=AliasChoices('AWS_STORAGE_BUCKET_NAME'))
    BASE_DIR: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CACHES: Any = Field(default=None, description='django cache back-ends')  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CANVAS_TUTORBOT_FOLDER: str = Field(default='web_resources/ai/tutor/', validation_alias=AliasChoices('CANVAS_TUTORBOT_FOLDER'))
    CKEDITOR_ENVIRONMENT_ID: str | None = Field(default=None, validation_alias=AliasChoices('CKEDITOR_ENVIRONMENT_ID'), description='configuration for CKEditor token endpoint')
    CKEDITOR_SECRET_KEY: str | None = Field(default=None, validation_alias=AliasChoices('CKEDITOR_SECRET_KEY'))  # REDACTED: name looks secret-like — set via a source, not here
    CKEDITOR_UPLOAD_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('CKEDITOR_UPLOAD_URL'))  # TODO: refine type
    CONTENT_FILE_CLEANUP_CHUNK_SIZE: int = Field(default=1000, validation_alias=AliasChoices('CONTENT_FILE_CLEANUP_CHUNK_SIZE'))
    CONTENT_FILE_EMBEDDING_CHUNK_OVERLAP: int = Field(default=0, validation_alias=AliasChoices('CONTENT_FILE_EMBEDDING_CHUNK_OVERLAP'))
    CONTENT_FILE_EMBEDDING_CHUNK_SIZE_OVERRIDE: int = Field(default=512, validation_alias=AliasChoices('CONTENT_FILE_EMBEDDING_CHUNK_SIZE'))
    CONTENT_FILE_RETENTION_DAYS: int = Field(default=14, validation_alias=AliasChoices('CONTENT_FILE_RETENTION_DAYS'))
    CONTENT_FILE_SUMMARIZER_BATCH_SIZE: int = Field(default=20, validation_alias=AliasChoices('CONTENT_FILE_SUMMARIZER_BATCH_SIZE'))
    CONTENT_SUMMARIZER_FLASHCARD_PROMPT: str | None = Field(default=None, validation_alias=AliasChoices('CONTENT_SUMMARIZER_FLASHCARD_PROMPT'))  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CONTENT_SUMMARIZER_FLASHCARD_QUANTITY: int = Field(default=10, validation_alias=AliasChoices('CONTENT_SUMMARIZER_FLASHCARD_QUANTITY'), description='number of flashcards to generate')
    COOKIE_TOMBSTONES: Any = Field(default_factory=lambda: parse_cookie_tombstones(get_string("COOKIE_TOMBSTONES", "[]")))  # TODO: refine type
    CORS_ALLOWED_ORIGINS: Any = Field(default_factory=lambda: get_list_of_str("CORS_ALLOWED_ORIGINS", []), description='CORS')  # TODO: refine type
    CORS_ALLOWED_ORIGIN_REGEXES: Any = Field(default_factory=lambda: get_list_of_str("CORS_ALLOWED_ORIGIN_REGEXES", []))  # TODO: refine type
    CORS_ALLOW_CREDENTIALS: bool | None = Field(default=None, validation_alias=AliasChoices('CORS_ALLOW_CREDENTIALS'))  # REDACTED: name looks secret-like — set via a source, not here
    CORS_ALLOW_HEADERS: tuple[Any, ...] = Field(default=('accept', 'authorization', 'content-type', 'user-agent', 'x-csrftoken', 'x-requested-with', 'baggage', 'sentry-trace'))  # TODO: refine type
    CREATE_OCW_LEARNING_MATERIALS: bool = Field(default=False, validation_alias=AliasChoices('CREATE_OCW_LEARNING_MATERIALS'), description='Create all learning material resources for OCW courses\nLearning material resources are behind show_ocw_files flag in search')
    CSRF_COOKIE_DOMAIN: str | None = Field(default=None, validation_alias=AliasChoices('CSRF_COOKIE_DOMAIN'))
    CSRF_COOKIE_NAME: str = Field(default='csrftoken', validation_alias=AliasChoices('CSRF_COOKIE_NAME'))
    CSRF_COOKIE_SECURE: bool = Field(default=True, validation_alias=AliasChoices('CSRF_COOKIE_SECURE'))
    CSRF_HEADER_NAME: str = Field(default='HTTP_X_CSRFTOKEN', validation_alias=AliasChoices('CSRF_HEADER_NAME'))
    CSRF_TRUSTED_ORIGINS: Any = Field(default_factory=lambda: get_list_of_str("CSRF_TRUSTED_ORIGINS", []))  # TODO: refine type
    DATABASES: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DATABASE_ROUTERS: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ['main.routers.ExternalSchemaRouter'])
    DEBUG: bool = Field(default=False, validation_alias=AliasChoices('DEBUG'), description="SECURITY WARNING: don't run with debug turned on in production!")
    DEFAULT_AUTO_FIELD: str = Field(default='django.db.models.AutoField')
    DEFAULT_DATABASE_CONFIG: Any = Field(default=None, description='Database\nhttps://docs.djangoproject.com/en/1.8/ref/settings/#databases\nUses DATABASE_URL to configure with sqlite default:\nFor URL structure:\nhttps://github.com/kennethreitz/dj-database-url')  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEFAULT_FROM_EMAIL: str = Field(default='webmaster@localhost', validation_alias=AliasChoices('MITOL_FROM_EMAIL'))
    DEFAULT_SEARCH_CONTENT_FILE_SCORE_WEIGHT: float = Field(default=1, validation_alias=AliasChoices('DEFAULT_SEARCH_CONTENT_FILE_SCORE_WEIGHT'))
    DEFAULT_SEARCH_MAX_INCOMPLETENESS_PENALTY: float = Field(default=90, validation_alias=AliasChoices('DEFAULT_SEARCH_MAX_INCOMPLETENESS_PENALTY'))
    DEFAULT_SEARCH_MINIMUM_SCORE_CUTOFF: float = Field(default=5, validation_alias=AliasChoices('DEFAULT_SEARCH_MINIMUM_SCORE_CUTOFF'))
    DEFAULT_SEARCH_MODE: str = Field(default='phrase', validation_alias=AliasChoices('DEFAULT_SEARCH_MODE'), description='Search defaults settings - adjustable throught the admin ui')
    DEFAULT_SEARCH_SLOP: int = Field(default=6, validation_alias=AliasChoices('DEFAULT_SEARCH_SLOP'))
    DEFAULT_SEARCH_STALENESS_PENALTY: float = Field(default=2.5, validation_alias=AliasChoices('DEFAULT_SEARCH_STALENESS_PENALTY'))
    DENSE_VECTOR_SEARCH_MIN_SCORE: float = Field(default=0.3, validation_alias=AliasChoices('DENSE_VECTOR_SEARCH_MIN_SCORE'), description='the minimum similarity score for dense only search')
    DISABLE_APISIX_USER_MIDDLEWARE: bool = Field(default=False, validation_alias=AliasChoices('DISABLE_APISIX_USER_MIDDLEWARE'))
    DJANGO_LOG_LEVEL: str = Field(default='INFO', validation_alias=AliasChoices('DJANGO_LOG_LEVEL'))
    DRF_NESTED_PARENT_LOOKUP_PREFIX: str = Field(default='', validation_alias=AliasChoices('DRF_NESTED_PARENT_LOOKUP_PREFIX'), description='drf extension settings')
    EMAIL_BACKEND: str = Field(default='django.core.mail.backends.smtp.EmailBackend', validation_alias=AliasChoices('MITOL_EMAIL_BACKEND'), description='Configure e-mail settings')
    EMAIL_HOST: str = Field(default='localhost', validation_alias=AliasChoices('MITOL_EMAIL_HOST'))
    EMAIL_HOST_PASSWORD: str | None = Field(default=None, validation_alias=AliasChoices('MITOL_EMAIL_PASSWORD'))  # REDACTED: name looks secret-like — set via a source, not here
    EMAIL_HOST_USER: str = Field(default='', validation_alias=AliasChoices('MITOL_EMAIL_USER'))
    EMAIL_PORT: int = Field(default=25, validation_alias=AliasChoices('MITOL_EMAIL_PORT'))
    EMAIL_SUPPORT: str = Field(default='support@example.com', validation_alias=AliasChoices('MITOL_SUPPORT_EMAIL'))
    EMAIL_USE_TLS: bool = Field(default=False, validation_alias=AliasChoices('MITOL_EMAIL_TLS'))
    EMBEDDINGS_EXTERNAL_FETCH_USE_WEBDRIVER: bool = Field(default=False, validation_alias=AliasChoices('EMBEDDINGS_EXTERNAL_FETCH_USE_WEBDRIVER'), description='toggle to use requests (default for local) or webdriver which renders js elements')
    EMBEDDING_SCHEDULE_MINUTES: int = Field(default=60, validation_alias=AliasChoices('EMBEDDING_SCHEDULE_MINUTES'))
    ENVIRONMENT: str = Field(default='dev', validation_alias=AliasChoices('MITOL_ENVIRONMENT'))
    EXTERNAL_MODELS: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ['programcertificate'])
    FASTLY_API_KEY: str | None = Field(default=None, validation_alias=AliasChoices('FASTLY_API_KEY'), description='Fastly CDN settings')  # REDACTED: name looks secret-like — set via a source, not here
    FASTLY_URL: AnyUrl = Field(default='https://api.fastly.com', validation_alias=AliasChoices('FASTLY_URL'))  # TODO: refine type
    FEATURES: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    GA_G_TRACKING_ID: str = Field(default='', validation_alias=AliasChoices('GA_G_TRACKING_ID'))
    GA_TRACKING_ID: str = Field(default='', validation_alias=AliasChoices('GA_TRACKING_ID'))
    HEALTH_CHECK: Annotated[dict[str, Any], NoDecode] = Field(default_factory=lambda: {'SUBSETS': {'startup': ['MigrationsHealthCheck', 'CacheBackend', 'RedisHealthCheck', 'DatabaseHeartBeatCheck'], 'liveness': ['DatabaseHeartBeatCheck'], 'readiness': ['CacheBackend', 'RedisHealthCheck', 'DatabaseHeartBeatCheck'], 'full': ['MigrationsHealthCheck', 'CacheBackend', 'RedisHealthCheck', 'DatabaseHeartBeatCheck', 'CeleryPingHealthCheck']}})
    HOSTNAME: Any = Field(default_factory=lambda: platform.node().split(".")[0])  # TODO: refine type
    HYBRID_VECTOR_SEARCH_MIN_SCORE: float = Field(default=0.1, validation_alias=AliasChoices('HYBRID_VECTOR_SEARCH_MIN_SCORE'), description='the minimum similarity score for hybrid search (Reciprocal Rank Fusion)')
    IMAGEKIT_CACHEFILE_DIR: str = Field(default='', validation_alias=AliasChoices('IMAGEKIT_CACHEFILE_DIR'))
    IMAGEKIT_CACHE_BACKEND: str = Field(default='imagekit')
    IMAGEKIT_SPEC_CACHEFILE_NAMER: str = Field(default='imagekit.cachefiles.namers.source_name_dot_hash')
    INDEXING_ERROR_RETRIES: int = Field(default=1, validation_alias=AliasChoices('INDEXING_ERROR_RETRIES'))
    INSTALLED_APPS: tuple[Any, ...] = Field(default=('django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.humanize', 'django.contrib.sites', 'django_removals', 'django_scim', 'social_django', 'server_status', 'rest_framework', 'corsheaders', 'anymail', 'guardian', 'imagekit', 'django_json_widget', 'django_filters', 'drf_spectacular', 'django_aqueduct', 'mitol.observability.apps.ObservabilityConfig', 'main', 'users.apps.UsersConfig', 'authentication', 'channels', 'profiles', 'webhooks', 'widgets', 'learning_resources', 'learning_resources_search', 'website_content.apps.WebsiteContentConfig', 'openapi', 'oauth2_provider', 'news_events', 'testimonials', 'data_fixtures', 'vector_search', 'ol_hubspot', 'mitol.scim.apps.ScimApp', 'health_check', 'health_check.cache', 'health_check.contrib.migrations', 'health_check.contrib.celery_ping', 'health_check.contrib.redis', 'health_check.contrib.db_heartbeat'))  # TODO: refine type
    INTERNAL_IPS: Any = Field(default_factory=lambda: (get_string("HOST_IP", "127.0.0.1"),), description='Important to define this so DEBUG works properly')  # TODO: refine type
    IPWARE_PRIVATE_IP_PREFIX: Any = Field(default=None, description='allow for all IPs to be routable, including localhost, for testing')  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    JWT_AUTH: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    KEYCLOAK_BASE_URL: AnyUrl = Field(default='http://mit-keycloak-base-url.edu', validation_alias=AliasChoices('KEYCLOAK_BASE_URL'), description='Keycloak API settings')  # TODO: refine type
    KEYCLOAK_REALM_NAME: str = Field(default='olapps', validation_alias=AliasChoices('KEYCLOAK_REALM_NAME'))
    LANGUAGE_CODE: str = Field(default='en-us')
    LITELLM_API_BASE: str | None = Field(default=None, validation_alias=AliasChoices('LITELLM_API_BASE'))
    LITELLM_CUSTOM_PROVIDER: str = Field(default='openai', validation_alias=AliasChoices('LITELLM_CUSTOM_PROVIDER'))
    LITELLM_TOKEN_ENCODING_NAME: str | None = Field(default=None, validation_alias=AliasChoices('LITELLM_TOKEN_ENCODING_NAME'))  # REDACTED: name looks secret-like — set via a source, not here
    LOGIN_ERROR_URL: AnyUrl = Field(default='/login')  # TODO: refine type
    LOGIN_REDIRECT_URL: AnyUrl = Field(default='/app')  # TODO: refine type
    LOGIN_URL: AnyUrl = Field(default='/login')  # TODO: refine type
    LOGOUT_REDIRECT_URL: AnyUrl = Field(default='/app')  # TODO: refine type
    LOG_LEVEL: str = Field(default='INFO', validation_alias=AliasChoices('MITOL_LOG_LEVEL'), description='Logging configuration')
    MAILGUN_BCC_TO_EMAIL: str | None = Field(default=None, validation_alias=AliasChoices('MAILGUN_BCC_TO_EMAIL'))
    MAILGUN_FROM_EMAIL: str = Field(default='no-reply@example.com', validation_alias=AliasChoices('MAILGUN_FROM_EMAIL'))
    MAILGUN_KEY: str | None = Field(default=None, validation_alias=AliasChoices('MAILGUN_KEY'))
    MAILGUN_RECIPIENT_OVERRIDE: str | None = Field(default=None, validation_alias=AliasChoices('MAILGUN_RECIPIENT_OVERRIDE'))
    MAILGUN_SENDER_DOMAIN: str | None = Field(default=None, validation_alias=AliasChoices('MAILGUN_SENDER_DOMAIN'))
    MEDIA_ROOT: str = Field(default='/var/media/', validation_alias=AliasChoices('MEDIA_ROOT'))
    MEDIA_URL: AnyUrl = Field(default='/media/')  # TODO: refine type
    MICROMASTERS_CMS_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('MICROMASTERS_CMS_API_URL'))  # TODO: refine type
    MIDDLEWARE: tuple[Any, ...] = Field(default=('django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'main.middleware.apisix_user.ApisixUserMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'corsheaders.middleware.CorsMiddleware', 'authentication.middleware.BlockedIPMiddleware', 'oauth2_provider.middleware.OAuth2TokenMiddleware', 'django_scim.middleware.SCIMAuthCheckMiddleware'), description='OAuth2TokenMiddleware must be before SCIMAuthCheckMiddleware\nin order to insert request.user into the request.')  # TODO: refine type
    MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS: int = Field(default_factory=lambda: 60 * 60, validation_alias=AliasChoices('MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS'))
    MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME: str = Field(default='MITOL_FEATURE_FLAGS', validation_alias=AliasChoices('MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME'))
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: str | None = Field(default=None, validation_alias=AliasChoices('MIDDLEWARE_FEATURE_FLAG_QS_PREFIX'))
    MIGRATION_MODULES: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_API_BASE_URL: AnyUrl = Field(default='', validation_alias=AliasChoices('MITOL_API_BASE_URL'))  # TODO: refine type
    MITOL_COOKIE_DOMAIN: str | None = Field(default=None, validation_alias=AliasChoices('MITOL_COOKIE_DOMAIN'))
    MITOL_COOKIE_NAME: str | None = Field(default=None, validation_alias=AliasChoices('MITOL_COOKIE_NAME'))
    MITOL_FEATURES_DEFAULT: bool = Field(default=False, validation_alias=AliasChoices('MITOL_FEATURES_DEFAULT'))
    MITOL_FEATURES_PREFIX: str = Field(default='FEATURE_', validation_alias=AliasChoices('MITOL_FEATURES_PREFIX'))
    MITOL_HUBSPOT_API_PRIVATE_TOKEN: str | None = Field(default=None, validation_alias=AliasChoices('MITOL_HUBSPOT_API_PRIVATE_TOKEN'), description='Hubspot settings')  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_JWT_SECRET: str | None = Field(default=None, validation_alias=AliasChoices('MITOL_JWT_SECRET'), description='JWT authentication settings')  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_NEW_USER_LOGIN_URL: AnyUrl = Field(default='http://open.odl.local:8062/onboarding', validation_alias=AliasChoices('MITOL_NEW_USER_LOGIN_URL'))  # TODO: refine type
    MITOL_SIMILAR_RESOURCES_COUNT: int = Field(default=3, validation_alias=AliasChoices('MITOL_SIMILAR_RESOURCES_COUNT'), description='Similar resources settings')
    MITOL_TITLE: str = Field(default='MIT Learn', validation_alias=AliasChoices('MITOL_TITLE'))
    MITOL_TOS_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('MITOL_TOS_URL'))  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS: int | None = Field(default=None, validation_alias=AliasChoices('MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS'))  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_USE_S3: bool = Field(default=False, validation_alias=AliasChoices('MITOL_USE_S3'))
    MIT_WS_CERTIFICATE_FILE: Any = Field(default=None, description='x509 filenames')  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MIT_WS_PRIVATE_KEY_FILE: str | None = Field(default=None)  # REDACTED: name looks secret-like — set via a source, not here
    NOTIFICATION_ATTEMPT_CHUNK_SIZE: int = Field(default=100)
    NOTIFICATION_ATTEMPT_RATE_LIMIT: str = Field(default='600/m')
    NOTIFICATION_EMAIL_BACKEND: str = Field(default='anymail.backends.test.EmailBackend', validation_alias=AliasChoices('MITOL_NOTIFICATION_EMAIL_BACKEND'))
    NPLUSONE_LOGGER: Any = Field(default_factory=lambda: logging.getLogger("nplusone"), description='nplusone profiler logger configuration')  # TODO: refine type
    NPLUSONE_LOG_LEVEL: Any = Field(default_factory=lambda: logging.ERROR)  # TODO: refine type
    OIDC_LOGOUT_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('OIDC_LOGOUT_URL'))  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    OPENAI_API_KEY: str | None = Field(default=None, validation_alias=AliasChoices('OPENAI_API_KEY'))  # REDACTED: name looks secret-like — set via a source, not here
    OPENSEARCH_CONNECTIONS_PER_NODE: int = Field(default=10, validation_alias=AliasChoices('OPENSEARCH_CONNECTIONS_PER_NODE'))
    OPENSEARCH_DEFAULT_PAGE_SIZE: int = Field(default=10, validation_alias=AliasChoices('OPENSEARCH_DEFAULT_PAGE_SIZE'), description='OpenSearch')
    OPENSEARCH_DEFAULT_TIMEOUT: int = Field(default=10, validation_alias=AliasChoices('OPENSEARCH_DEFAULT_TIMEOUT'))
    OPENSEARCH_DOCUMENT_INDEXING_CHUNK_SIZE: int = Field(default_factory=lambda: get_int("OPENSEARCH_INDEXING_CHUNK_SIZE", 100), validation_alias=AliasChoices('OPENSEARCH_DOCUMENT_INDEXING_CHUNK_SIZE'))
    OPENSEARCH_HTTP_AUTH: str | None = Field(default=None, validation_alias=AliasChoices('OPENSEARCH_HTTP_AUTH'))
    OPENSEARCH_INDEX: str | None = Field(default=None, validation_alias=AliasChoices('OPENSEARCH_INDEX'))  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    OPENSEARCH_INDEXING_CHUNK_SIZE: int = Field(default=100, validation_alias=AliasChoices('OPENSEARCH_INDEXING_CHUNK_SIZE'))
    OPENSEARCH_MAX_REQUEST_SIZE: int = Field(default=10485760, validation_alias=AliasChoices('OPENSEARCH_MAX_REQUEST_SIZE'))
    OPENSEARCH_MAX_SUGGEST_HITS: int = Field(default=1, validation_alias=AliasChoices('OPENSEARCH_MAX_SUGGEST_HITS'))
    OPENSEARCH_MAX_SUGGEST_RESULTS: int = Field(default=1, validation_alias=AliasChoices('OPENSEARCH_MAX_SUGGEST_RESULTS'))
    OPENSEARCH_MIN_QUERY_SIZE: int = Field(default=2, validation_alias=AliasChoices('OPENSEARCH_MIN_QUERY_SIZE'))
    OPENSEARCH_REPLICA_COUNT: int = Field(default=2, validation_alias=AliasChoices('OPENSEARCH_REPLICA_COUNT'))
    OPENSEARCH_SHARD_COUNT: int = Field(default=2, validation_alias=AliasChoices('OPENSEARCH_SHARD_COUNT'))
    OPENSEARCH_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('OPENSEARCH_URL'))  # TODO: refine type
    OPENSEARCH_VECTOR_MODEL_BASE_NAME: str = Field(default='hybrid_search_model', validation_alias=AliasChoices('OPENSEARCH_VECTOR_MODEL_BASE_NAME'))
    OPENTELEMETRY_ENABLED: bool = Field(default=False, validation_alias=AliasChoices('OPENTELEMETRY_ENABLED'), description='OpenTelemetry configuration')
    OPENTELEMETRY_ENDPOINT: str | None = Field(default=None, validation_alias=AliasChoices('OPENTELEMETRY_ENDPOINT'))
    OPENTELEMETRY_EXPORT_TIMEOUT_MS: int = Field(default=5000, validation_alias=AliasChoices('OPENTELEMETRY_EXPORT_TIMEOUT_MS'))
    OPENTELEMETRY_INSECURE: bool = Field(default=True, validation_alias=AliasChoices('OPENTELEMETRY_INSECURE'))
    OPENTELEMETRY_SERVICE_NAME: str = Field(default='learn', validation_alias=AliasChoices('OPENTELEMETRY_SERVICE_NAME'))
    OPENTELEMETRY_TRACES_BATCH_SIZE: int = Field(default=512, validation_alias=AliasChoices('OPENTELEMETRY_TRACES_BATCH_SIZE'))
    OPEN_AI_EMBEDDING_MODELS: Any = Field(default_factory=lambda: get_list_of_str(
    "OPEN_AI_EMBEDDING_MODELS",
    [
        "text-embedding-3-small",
        "text-embedding-3-large",
    ],
))  # TODO: refine type
    OPEN_RESOURCES_MIN_DOC_FREQ: int = Field(default=1, validation_alias=AliasChoices('OPEN_RESOURCES_MIN_DOC_FREQ'))
    OPEN_RESOURCES_MIN_TERM_FREQ: int = Field(default=1, validation_alias=AliasChoices('OPEN_RESOURCES_MIN_TERM_FREQ'))
    OPTIONS: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    OS_LOG_LEVEL: str = Field(default='INFO', validation_alias=AliasChoices('OS_LOG_LEVEL'))
    POSTHOG_API_HOST: AnyUrl = Field(default='https://us.posthog.com', validation_alias=AliasChoices('POSTHOG_API_HOST'))  # TODO: refine type
    POSTHOG_EVENT_S3_BUCKET: str = Field(default='None', validation_alias=AliasChoices('POSTHOG_EVENT_S3_BUCKET'))
    POSTHOG_EVENT_S3_PREFIX: str = Field(default='None', validation_alias=AliasChoices('POSTHOG_EVENT_S3_PREFIX'))
    POSTHOG_PERSONAL_API_KEY: str | None = Field(default=None, validation_alias=AliasChoices('POSTHOG_PERSONAL_API_KEY'))  # REDACTED: name looks secret-like — set via a source, not here
    POSTHOG_PROJECT_API_KEY: str | None = Field(default=None, validation_alias=AliasChoices('POSTHOG_PROJECT_API_KEY'))  # REDACTED: name looks secret-like — set via a source, not here
    POSTHOG_PROJECT_ID: int | None = Field(default=None, validation_alias=AliasChoices('POSTHOG_PROJECT_ID'))
    POSTHOG_TIMEOUT_MS: int = Field(default=3000, validation_alias=AliasChoices('POSTHOG_TIMEOUT_MS'))
    QDRANT_API_KEY: str | None = Field(default=None, validation_alias=AliasChoices('QDRANT_API_KEY'))  # REDACTED: name looks secret-like — set via a source, not here
    QDRANT_BASE_COLLECTION_NAME: str = Field(default='resource_embeddings', validation_alias=AliasChoices('QDRANT_COLLECTION_NAME'))
    QDRANT_BATCH_SIZE_BYTES: int = Field(default_factory=lambda: 10 * 1024 * 1024, validation_alias=AliasChoices('QDRANT_BATCH_SIZE_BYTES'))
    QDRANT_CHUNK_SIZE: int = Field(default=10, validation_alias=AliasChoices('QDRANT_CHUNK_SIZE'))
    QDRANT_CLIENT_TIMEOUT: int = Field(default=10, validation_alias=AliasChoices('QDRANT_CLIENT_TIMEOUT'))
    QDRANT_DENSE_MODEL: str | None = Field(default=None, validation_alias=AliasChoices('QDRANT_DENSE_MODEL'))
    QDRANT_EMBEDDINGS_TASK_LOOKBACK_WINDOW: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    QDRANT_ENABLE_INDEXING_PLUGIN_HOOKS: bool = Field(default=False, validation_alias=AliasChoices('QDRANT_ENABLE_INDEXING_PLUGIN_HOOKS'))
    QDRANT_ENCODER: str = Field(default='vector_search.encoders.gensim.GensimEncoder', validation_alias=AliasChoices('QDRANT_ENCODER'))
    QDRANT_HOST: AnyUrl = Field(default='http://qdrant:6333', validation_alias=AliasChoices('QDRANT_HOST'))  # TODO: refine type
    QDRANT_POINT_UPLOAD_BATCH_SIZE: int = Field(default=1000, validation_alias=AliasChoices('QDRANT_POINT_UPLOAD_BATCH_SIZE'))
    QDRANT_QUERY_EMBEDDING_CACHE_TTL: int = Field(default_factory=lambda: 60 * 60 * 24 * 7, validation_alias=AliasChoices('QDRANT_QUERY_EMBEDDING_CACHE_TTL'), description='1 week default query cache ttl')
    QDRANT_SPARSE_ENCODER: str = Field(default='vector_search.encoders.sparse_hash.SparseHashEncoder', validation_alias=AliasChoices('QDRANT_SPARSE_ENCODER_V2'))
    QDRANT_SPARSE_MODEL: str = Field(default='sklearn/hashing_vectorizer_sparse_model', validation_alias=AliasChoices('QDRANT_SPARSE_MODEL_V2'))
    REACT_GA_DEBUG: bool = Field(default=False, validation_alias=AliasChoices('REACT_GA_DEBUG'))
    RECAPTCHA_SECRET_KEY: str | None = Field(default=None, validation_alias=AliasChoices('RECAPTCHA_SECRET_KEY'))  # REDACTED: name looks secret-like — set via a source, not here
    RECAPTCHA_SITE_KEY: str = Field(default='', validation_alias=AliasChoices('RECAPTCHA_SITE_KEY'))
    REDIS_VIEW_CACHE_DURATION: int = Field(default_factory=lambda: 60 * 60 * 24, validation_alias=AliasChoices('REDIS_VIEW_CACHE_DURATION'))
    REQUESTS_TIMEOUT: int = Field(default=30, validation_alias=AliasChoices('REQUESTS_TIMEOUT'))
    REST_FRAMEWORK: Annotated[dict[str, Any], NoDecode] = Field(default_factory=lambda: {'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',), 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.SessionAuthentication',), 'DEFAULT_PAGINATION_CLASS': 'main.pagination.DefaultPagination', 'EXCEPTION_HANDLER': 'main.exceptions.api_exception_handler', 'TEST_REQUEST_DEFAULT_FORMAT': 'json', 'TEST_REQUEST_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.MultiPartRenderer'], 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning', 'ALLOWED_VERSIONS': ['v0', 'v1'], 'ORDERING_PARAM': 'sortby'})
    REST_FRAMEWORK_EXTENSIONS: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ROOT_URLCONF: str = Field(default='main.urls')
    RSS_FEED_CACHE_MINUTES: int = Field(default=15, validation_alias=AliasChoices('RSS_FEED_CACHE_MINUTES'))
    RSS_FEED_EPISODE_LIMIT: int = Field(default=100, validation_alias=AliasChoices('RSS_FEED_EPISODE_LIMIT'))
    SEARCH_PROGRAM_INDEX_BOOST: float = Field(default=3, validation_alias=AliasChoices('SEARCH_PROGRAM_INDEX_BOOST'))
    SECRET_KEY: str | None = Field(default=None, validation_alias=AliasChoices('SECRET_KEY'), description='SECURITY WARNING: keep the secret key used in production secret!')  # REDACTED: name looks secret-like — set via a source, not here
    SECURE_CROSS_ORIGIN_OPENER_POLICY: str = Field(default='same-origin', validation_alias=AliasChoices('SECURE_CROSS_ORIGIN_OPENER_POLICY'))
    SECURE_REDIRECT_EXEMPT: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ['^health/startup/$', '^health/liveness/$', '^health/readiness/$', '^health/full/$'])
    SECURE_SSL_REDIRECT: bool = Field(default=True, validation_alias=AliasChoices('MITOL_SECURE_SSL_REDIRECT'))
    SENTRY_DSN: str | None = Field(default=None, validation_alias=AliasChoices('SENTRY_DSN'), description='initialize Sentry before doing anything else so we capture any config errors')  # REDACTED: name looks secret-like — set via a source, not here
    SENTRY_LOG_LEVEL: str = Field(default='ERROR', validation_alias=AliasChoices('SENTRY_LOG_LEVEL'))
    SENTRY_PROFILES_SAMPLE_RATE: float = Field(default=0, validation_alias=AliasChoices('SENTRY_PROFILES_SAMPLE_RATE'))
    SENTRY_TRACES_SAMPLE_RATE: float = Field(default=0, validation_alias=AliasChoices('SENTRY_TRACES_SAMPLE_RATE'))
    SESSION_COOKIE_DOMAIN: str | None = Field(default=None, validation_alias=AliasChoices('SESSION_COOKIE_DOMAIN'))
    SESSION_COOKIE_NAME: str = Field(default='sessionid', validation_alias=AliasChoices('SESSION_COOKIE_NAME'))
    SESSION_ENGINE: str = Field(default='django.contrib.sessions.backends.signed_cookies')
    SITE_ID: int = Field(default=1)
    SPECTACULAR_SETTINGS: Any = Field(default_factory=lambda: open_spectacular_settings)  # TODO: refine type
    STATIC_ROOT: str = Field(default='staticfiles')
    STATIC_URL: AnyUrl = Field(default='/static/', description='Serve static files with dj-static')  # TODO: refine type
    STATUS_TOKEN: str | None = Field(default=None, validation_alias=AliasChoices('STATUS_TOKEN'))  # REDACTED: name looks secret-like — set via a source, not here
    STORAGES: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    TEMPLATES: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    TIME_ZONE: str = Field(default='UTC')
    USERINFO_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('USERINFO_URL'))  # TODO: refine type
    USE_I18N: bool = Field(default=True)
    USE_L10N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_X_FORWARDED_HOST: bool = Field(default=False, validation_alias=AliasChoices('USE_X_FORWARDED_HOST'))
    USE_X_FORWARDED_PORT: bool = Field(default=False, validation_alias=AliasChoices('USE_X_FORWARDED_PORT'))
    VECTOR_HYBRID_SEARCH_PREFETCH_MAX_LIMIT: int = Field(default=500, validation_alias=AliasChoices('VECTOR_HYBRID_SEARCH_PREFETCH_MAX_LIMIT'))
    VECTOR_HYBRID_SEARCH_PREFETCH_MULTIPLIER: int = Field(default=5, validation_alias=AliasChoices('VECTOR_HYBRID_SEARCH_PREFETCH_MULTIPLIER'))
    VECTOR_SEARCH_PAGE_MAX_LIMIT: int = Field(default=200, validation_alias=AliasChoices('VECTOR_SEARCH_PAGE_MAX_LIMIT'), description='hard limit for special cases where we need to return all results without pagination')
    VERSION: str = Field(default='0.72.3')
    WEBDRIVER_WAIT_SECONDS: int = Field(default=10, validation_alias=AliasChoices('WEBDRIVER_WAIT_SECONDS'))
    WEBHOOK_SECRET: str | None = Field(default=None, validation_alias=AliasChoices('WEBHOOK_SECRET'))  # REDACTED: name looks secret-like — set via a source, not here
    WIDGETS_RSS_CACHE_TTL: int = Field(default_factory=lambda: 15 * 60, validation_alias=AliasChoices('WIDGETS_RSS_CACHE_TTL'), description='Widgets')
    WSGI_APPLICATION: str = Field(default='main.wsgi.application')
    ZEAL_ALLOWLIST: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: [])
    ZEAL_ENABLE: bool = Field(default=False, validation_alias=AliasChoices('ZEAL_ENABLE'))
    ZEAL_RAISE: bool = Field(default=False)
    # ===== main.settings_celery =====
    CELERY_ACCEPT_CONTENT: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ['json'])
    CELERY_BEAT_DISABLED: bool = Field(default=False, validation_alias=AliasChoices('CELERY_BEAT_DISABLED'))
    CELERY_BEAT_SCHEDULE: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_BEAT_SCHEDULER: Any = Field(default_factory=lambda: RedBeatScheduler)  # TODO: refine type
    CELERY_BROKER_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('CELERY_BROKER_URL'))  # REDACTED: name looks secret-like — set via a source, not here
    CELERY_RATE_LIMIT: str = Field(default='600/m', validation_alias=AliasChoices('CELERY_DEFAULT_RATE_LIMIT'))
    CELERY_RESULT_BACKEND: str | None = Field(default=None, validation_alias=AliasChoices('CELERY_RESULT_BACKEND'))  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_RESULT_SERIALIZER: str = Field(default='json')
    CELERY_SEARCH_RATE_LIMIT: str | None = Field(default=None, validation_alias=AliasChoices('CELERY_SEARCH_RATE_LIMIT'))  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_TASK_ALWAYS_EAGER: bool = Field(default=False, validation_alias=AliasChoices('CELERY_TASK_ALWAYS_EAGER'))
    CELERY_TASK_EAGER_PROPAGATES: bool = Field(default=True, validation_alias=AliasChoices('CELERY_TASK_EAGER_PROPAGATES'))
    CELERY_TASK_SEND_SENT_EVENT: bool = Field(default=True)
    CELERY_TASK_SERIALIZER: str = Field(default='json')
    CELERY_TASK_TASK_TRACK_STARTED: bool = Field(default=True)
    CELERY_TIMEZONE: str = Field(default='UTC')
    CELERY_VECTOR_SEARCH_RATE_LIMIT: str | None = Field(default=None, validation_alias=AliasChoices('CELERY_VECTOR_SEARCH_RATE_LIMIT'))  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_WORKER_MAX_MEMORY_PER_CHILD: int = Field(default=250000, validation_alias=AliasChoices('CELERY_WORKER_MAX_MEMORY_PER_CHILD'))
    DEV_ENV: bool = Field(default=False, validation_alias=AliasChoices('DEV_ENV'))
    REDIS_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('REDIS_URL'))  # REDACTED: name looks secret-like — set via a source, not here
    USE_CELERY: bool = Field(default=True)
    # ===== main.settings_course_etl =====
    ASK_MIT_CLIMATE_API_URL: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    BLOCKLISTED_COURSES_URL: AnyUrl = Field(default='https://raw.githubusercontent.com/mitodl/open-resource-blocklists/master/courses.txt', validation_alias=AliasChoices('BLOCKLISTED_COURSES_URL'))  # TODO: refine type
    CANVAS_COURSE_BUCKET_PREFIX: str = Field(default='canvas/course_content', validation_alias=AliasChoices('CANVAS_COURSE_BUCKET_PREFIX'))
    CONTENT_BASE_URL_EDX: AnyUrl = Field(default='https://courses.edx.org', validation_alias=AliasChoices('CONTENT_BASE_URL_EDX'))  # TODO: refine type
    CONTENT_BASE_URL_MITXONLINE: AnyUrl = Field(default='https://courses.mitxonline.mit.edu', validation_alias=AliasChoices('CONTENT_BASE_URL_MITXONLINE'), description='Base content URLs for different sources')  # TODO: refine type
    CONTENT_BASE_URL_OLL: AnyUrl = Field(default='https://openlearninglibrary.mit.edu', validation_alias=AliasChoices('CONTENT_BASE_URL_OLL'))  # TODO: refine type
    CONTENT_BASE_URL_XPRO: AnyUrl = Field(default='https://courses.xpro.mit.edu', validation_alias=AliasChoices('CONTENT_BASE_URL_XPRO'))  # TODO: refine type
    COURSE_ARCHIVE_BUCKET_NAME: str = Field(default='ol-data-lake-landing-zone-production', validation_alias=AliasChoices('COURSE_ARCHIVE_BUCKET_NAME'), description='Canvas course settings')
    CSAIL_BASE_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('CSAIL_BASE_URL'))  # TODO: refine type
    DUPLICATE_COURSES_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('DUPLICATE_COURSES_URL'))  # TODO: refine type
    EDX_ALT_URL: AnyUrl = Field(default='https://courses.edx.org/', validation_alias=AliasChoices('EDX_ALT_URL'))  # TODO: refine type
    EDX_API_ACCESS_TOKEN_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('EDX_API_ACCESS_TOKEN_URL'))  # REDACTED: name looks secret-like — set via a source, not here
    EDX_API_CLIENT_ID: str | None = Field(default=None, validation_alias=AliasChoices('EDX_API_CLIENT_ID'))
    EDX_API_CLIENT_SECRET: str | None = Field(default=None, validation_alias=AliasChoices('EDX_API_CLIENT_SECRET'))  # REDACTED: name looks secret-like — set via a source, not here
    EDX_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('EDX_API_URL'), description='EDX API Credentials')  # TODO: refine type
    EDX_BASE_URL: AnyUrl = Field(default='https://www.edx.org/', validation_alias=AliasChoices('EDX_BASE_URL'))  # TODO: refine type
    EDX_COURSE_BUCKET_PREFIX: str = Field(default='edxorg-raw-data/edxorg/raw_data/course_xml/', validation_alias=AliasChoices('EDX_COURSE_BUCKET_PREFIX'))
    EDX_PROGRAMS_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('EDX_PROGRAMS_API_URL'))  # TODO: refine type
    GITHUB_ACCESS_TOKEN: str | None = Field(default=None, validation_alias=AliasChoices('GITHUB_ACCESS_TOKEN'), description='Authentication for the github api')  # REDACTED: name looks secret-like — set via a source, not here
    LEARNING_COURSE_ITERATOR_CHUNK_SIZE: int = Field(default=20, validation_alias=AliasChoices('LEARNING_COURSE_ITERATOR_CHUNK_SIZE'), description='Iterator chunk size for MITx and xPRO courses')
    MAX_S3_GET_ITERATIONS: int = Field(default=3, validation_alias=AliasChoices('MAX_S3_GET_ITERATIONS'))
    MICROMASTERS_CATALOG_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('MICROMASTERS_CATALOG_API_URL'), description='Base URL for Micromasters data')  # TODO: refine type
    MITPE_BASE_URL: AnyUrl = Field(default='https://professional.mit.edu/', validation_alias=AliasChoices('MITPE_BASE_URL'))  # TODO: refine type
    MITX_ONLINE_BASE_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('MITX_ONLINE_BASE_URL'))  # TODO: refine type
    MITX_ONLINE_COURSES_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('MITX_ONLINE_COURSES_API_URL'))  # TODO: refine type
    MITX_ONLINE_COURSE_BUCKET_PREFIX: str = Field(default='mitxonline/openedx/raw_data/course_xml/', validation_alias=AliasChoices('MITX_ONLINE_COURSE_BUCKET_PREFIX'), description='MITx Online settings for course/resource ingestion')
    MITX_ONLINE_PROGRAMS_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('MITX_ONLINE_PROGRAMS_API_URL'))  # TODO: refine type
    MIT_CLIMATE_BASE_URL: AnyUrl = Field(default='https://climate.mit.edu')  # TODO: refine type
    MIT_CLIMATE_EXPLAINERS_API_URL: Any = Field(default=None)  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    OCR_DEBUG_DIRECTORY: str = Field(default='ocr_debug', validation_alias=AliasChoices('OCR_DEBUG_DIRECTORY'))
    OCR_MATH_DENSITY_THRESHOLD: int = Field(default=5, validation_alias=AliasChoices('OCR_MATH_DENSITY_THRESHOLD'), description='OCR the entire page if the density of math formulas exceeds this threshold')
    OCR_MODEL: str | None = Field(default=None, validation_alias=AliasChoices('OCR_MODEL'))
    OCR_PDF_MAX_PAGE_THRESHOLD: int = Field(default=10, validation_alias=AliasChoices('OCR_PDF_MAX_PAGE_THRESHOLD'), description='Do not OCR if the PDF has exceeds this many pages')
    OCR_PROMPT: str = Field(default='Transcribe this image to markdown. Properly format text, formulas, tables, and code into markdown format.Include a markdown comment for elements that cannot be transcribed such as photos and other visual elements.Do not include any indications your output is the result of a transcription.Do not include extra commentary - ONLY include the resulting transcribed markdown.', validation_alias=AliasChoices('OCR_PROMPT'))
    OCW_BASE_URL: AnyUrl = Field(default='http://ocw.mit.edu/', validation_alias=AliasChoices('OCW_BASE_URL'), description="Base URL's for courses")  # TODO: refine type
    OCW_ITERATOR_CHUNK_SIZE: int = Field(default=1000, validation_alias=AliasChoices('OCW_ITERATOR_CHUNK_SIZE'))
    OCW_LIVE_BUCKET: str | None = Field(default=None, validation_alias=AliasChoices('OCW_LIVE_BUCKET'), description='OCW settings')
    OCW_OFFLINE_DELIVERY: bool = Field(default=False, validation_alias=AliasChoices('OCW_OFFLINE_DELIVERY'))
    OCW_SKIP_CONTENT_FILES: bool = Field(default=False, validation_alias=AliasChoices('OCW_SKIP_CONTENT_FILES'))
    OCW_WEBHOOK_KEY: str | None = Field(default=None, validation_alias=AliasChoices('OCW_WEBHOOK_KEY'))
    OLL_COURSE_BUCKET_PREFIX: str = Field(default='open-learning-library/courses', validation_alias=AliasChoices('OLL_COURSE_BUCKET_PREFIX'), description='Open Learning Library settings')
    OPEN_PODCAST_DATA_BRANCH: str = Field(default='master', validation_alias=AliasChoices('OPEN_PODCAST_DATA_BRANCH'), description='course catalog podcast etl settings')
    OPEN_VIDEO_DATA_BRANCH: str = Field(default='master', validation_alias=AliasChoices('OPEN_VIDEO_DATA_BRANCH'), description='course catalog video etl settings')
    OPEN_VIDEO_MAX_TOPICS: int = Field(default=2, validation_alias=AliasChoices('OPEN_VIDEO_MAX_TOPICS'))
    OPEN_VIDEO_MIN_DOC_FREQ: int = Field(default=15, validation_alias=AliasChoices('OPEN_VIDEO_MIN_DOC_FREQ'))
    OPEN_VIDEO_MIN_TERM_FREQ: int = Field(default=1, validation_alias=AliasChoices('OPEN_VIDEO_MIN_TERM_FREQ'))
    OPEN_VIDEO_USER_LIST_OWNER: str | None = Field(default=None, validation_alias=AliasChoices('OPEN_VIDEO_USER_LIST_OWNER'))
    OVS_API_BASE_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('OVS_API_BASE_URL'), description='OVS (ODL Video Service) settings — public API, no auth required')  # TODO: refine type
    SEE_API_ACCESS_TOKEN_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('SEE_API_ACCESS_TOKEN_URL'))  # REDACTED: name looks secret-like — set via a source, not here
    SEE_API_CLIENT_ID: str | None = Field(default=None, validation_alias=AliasChoices('SEE_API_CLIENT_ID'))
    SEE_API_CLIENT_SECRET: str | None = Field(default=None, validation_alias=AliasChoices('SEE_API_CLIENT_SECRET'))  # REDACTED: name looks secret-like — set via a source, not here
    SEE_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('SEE_API_URL'), description='More MIT URLs')  # TODO: refine type
    SEE_BASE_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('SEE_BASE_URL'))  # TODO: refine type
    SKIP_TIKA: bool = Field(default=False, validation_alias=AliasChoices('SKIP_TIKA'))
    TIKA_ACCESS_TOKEN: str | None = Field(default=None, validation_alias=AliasChoices('TIKA_ACCESS_TOKEN'), description='Tika settings')  # REDACTED: name looks secret-like — set via a source, not here
    TIKA_OCR_STRATEGY: str = Field(default='no_ocr', validation_alias=AliasChoices('TIKA_OCR_STRATEGY'))
    TIKA_TIMEOUT: int = Field(default=60, validation_alias=AliasChoices('TIKA_TIMEOUT'))
    XPRO_CATALOG_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('XPRO_CATALOG_API_URL'))  # TODO: refine type
    XPRO_COURSES_API_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('XPRO_COURSES_API_URL'))  # TODO: refine type
    XPRO_COURSE_BUCKET_PREFIX: str = Field(default='xpro/openedx/raw_data/course_xml/', validation_alias=AliasChoices('XPRO_COURSE_BUCKET_PREFIX'), description='xPRO settings for course/resource ingestion')
    YOUTUBE_CONFIG_URL: AnyUrl | None = Field(default=None, validation_alias=AliasChoices('YOUTUBE_CONFIG_URL'))  # TODO: refine type
    YOUTUBE_DEVELOPER_KEY: str | None = Field(default=None, validation_alias=AliasChoices('YOUTUBE_DEVELOPER_KEY'))
    # ===== main.settings_pluggy =====
    MITOL_AUTHENTICATION_PLUGINS: str = Field(default='learning_resources.plugins.FavoritesListPlugin,profiles.plugins.CreateProfilePlugin', validation_alias=AliasChoices('MITOL_AUTHENTICATION_PLUGINS'))
    MITOL_LEARNING_RESOURCES_PLUGINS: str = Field(default='learning_resources_search.plugins.SearchIndexPlugin,channels.plugins.ChannelPlugin', validation_alias=AliasChoices('MITOL_LEARNING_RESOURCES_PLUGINS'))
    MITOL_WEBSITE_CONTENT_PLUGINS: str = Field(default='news_events.plugins.WebsiteContentNewsPlugin', validation_alias=AliasChoices('MITOL_WEBSITE_CONTENT_PLUGINS'))
    # ===== mitol.common.envs =====
    MITOL_SCIM_KEYCLOAK_BASE_URL: Any = Field(default=None, validation_alias=AliasChoices('MITOL_SCIM_KEYCLOAK_BASE_URL'), description='The base url for the upstream Keycloak service')  # TODO: refine type
    MITOL_SCIM_KEYCLOAK_BATCH_SIZE: int = Field(default=250, validation_alias=AliasChoices('MITOL_SCIM_KEYCLOAK_BATCH_SIZE'), description='Number of operations to send in a single batch request')
    MITOL_SCIM_KEYCLOAK_BULK_OPERATIONS_COUNT: int = Field(..., validation_alias=AliasChoices('MITOL_SCIM_KEYCLOAK_BULK_OPERATIONS_COUNT'), description='Number of operations to perform per bulk request')
    MITOL_SCIM_KEYCLOAK_CLIENT_ID: Any = Field(default=None, validation_alias=AliasChoices('MITOL_SCIM_KEYCLOAK_CLIENT_ID'), description='The client id for the Keycloak service')  # TODO: refine type
    MITOL_SCIM_KEYCLOAK_CLIENT_SECRET: Any = Field(default=None, validation_alias=AliasChoices('MITOL_SCIM_KEYCLOAK_CLIENT_SECRET'), description='The client secret for the Keycloak service')  # REDACTED: name looks secret-like — set via a source, not here
    MITOL_SCIM_KEYCLOAK_SEARCH_BATCH_SIZE: int = Field(default=100, validation_alias=AliasChoices('MITOL_SCIM_KEYCLOAK_SEARCH_BATCH_SIZE'), description='Number of operations to send in a single search request')
    MITOL_SCIM_REQUESTS_TIMEOUT_SECONDS: int = Field(default=60, validation_alias=AliasChoices('MITOL_SCIM_REQUESTS_TIMEOUT_SECONDS'), description='Number of seconds to timeout requests to Keycloak')
    # <<< aqueduct:generated:fields

    # >>> aqueduct:generated:container_decoders
    @field_validator('ALLOWED_HOSTS', 'CELERY_ACCEPT_CONTENT', 'DATABASE_ROUTERS', 'EXTERNAL_MODELS', 'SECURE_REDIRECT_EXEMPT', 'ZEAL_ALLOWLIST', mode="before")
    @classmethod
    def _aqueduct_decode_list_fields(cls, value: object) -> object:
        """Parse a list from a JSON, Python-literal, or comma-separated env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            try:
                parsed = ast.literal_eval(value)
            except (ValueError, SyntaxError):
                parsed = None
        if isinstance(parsed, list):
            return parsed
        return [item.strip() for item in value.split(",")]

    @field_validator('APISIX_USERDATA_MAP', 'HEALTH_CHECK', 'REST_FRAMEWORK', mode="before")
    @classmethod
    def _aqueduct_decode_dict_fields(cls, value: object) -> object:
        """Parse a dict from a JSON or Python-literal env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            parsed = None
        if isinstance(parsed, dict):
            return parsed
        return ast.literal_eval(value)
    # <<< aqueduct:generated:container_decoders

    # >>> aqueduct:preserved:validators
    # ------------------------------------------------------------------ #
    # Hand-maintained fields                                             #
    #                                                                    #
    # Primitives the legacy settings read inline (never assigned to a    #
    # module-level name), so static discovery cannot see them. Declaring #
    # them as fields makes them sourceable from env/Vault/SSM instead of #
    # being read straight from os.environ.                               #
    # ------------------------------------------------------------------ #
    # 0.8.0 generator gap: the auto-generated list decoder
    # (`_aqueduct_decode_list_fields`) parses JSON, Python-literal, and
    # comma-separated env strings — covering every list field mit-learn's .env
    # feeds (single-quoted regex lists, etc.). The one form it does NOT parse
    # is the bare-wildcard `ALLOWED_HOSTS=[*]` in the deployed .env: json and
    # ast.literal_eval both reject it, and the comma-split fallback keeps the
    # brackets, yielding ["[*]"] instead of the ["*"] the legacy settings
    # hardcode. Normalize just that case here (order-independent: handles both
    # the raw string and the decoder's mis-parsed single-element list).
    @field_validator("ALLOWED_HOSTS", mode="before")
    @classmethod
    def _normalize_wildcard_allowed_hosts(cls, value: object) -> object:
        """Map the bare-wildcard ALLOWED_HOSTS=[*] env form back to ["*"]."""
        if isinstance(value, str) and value.strip() in ("[*]", "[ * ]"):
            return ["*"]
        if (
            isinstance(value, list | tuple)
            and len(value) == 1
            and str(value[0]).strip() in ("[*]", "*")
        ):
            return ["*"]
        return value

    # 0.8.0 generator gap: mit-learn's list settings are read with mitol's
    # `get_list_of_str`, which static discovery does not recognize as a reader,
    # so these fields are discovered as `Any` (with a factory that reads
    # os.environ directly) rather than list — the generator's auto NoDecode +
    # list decoder therefore skips them, and as name-bound `Any` fields
    # pydantic-settings stores the raw env string instead of a parsed list.
    # Declare them explicitly as list[str] + NoDecode so they parse the same
    # env forms the generated decoder does (JSON, Python-literal single-quoted
    # lists, comma-separated) and route through the source chain (env/Vault).
    ALLOWED_REDIRECT_HOSTS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: ["open.odl.local:8062", "ocw.mit.edu"],
        validation_alias=AliasChoices("ALLOWED_REDIRECT_HOSTS"),
    )
    CORS_ALLOWED_ORIGINS: Annotated[list[str], NoDecode] = Field(
        default_factory=list, validation_alias=AliasChoices("CORS_ALLOWED_ORIGINS")
    )
    CORS_ALLOWED_ORIGIN_REGEXES: Annotated[list[str], NoDecode] = Field(
        default_factory=list,
        validation_alias=AliasChoices("CORS_ALLOWED_ORIGIN_REGEXES"),
    )
    CSRF_TRUSTED_ORIGINS: Annotated[list[str], NoDecode] = Field(
        default_factory=list, validation_alias=AliasChoices("CSRF_TRUSTED_ORIGINS")
    )
    OPEN_AI_EMBEDDING_MODELS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [
            "text-embedding-3-small",
            "text-embedding-3-large",
        ],
        validation_alias=AliasChoices("OPEN_AI_EMBEDDING_MODELS"),
    )

    @field_validator(
        "ALLOWED_REDIRECT_HOSTS",
        "CORS_ALLOWED_ORIGINS",
        "CORS_ALLOWED_ORIGIN_REGEXES",
        "CSRF_TRUSTED_ORIGINS",
        "OPEN_AI_EMBEDDING_MODELS",
        mode="before",
    )
    @classmethod
    def _decode_get_list_of_str_fields(cls, value: object) -> object:
        """Parse the env string forms for the `get_list_of_str` fields above."""
        return _parse_env_str_list(value)

    # Revert the 0.8.0 unconditional *_URL/*_URI -> AnyUrl promotion back to
    # str. This model's values are injected verbatim into Django settings
    # (the adapter does `scope.update(instance.model_dump())`), and Django
    # settings must be plain strings: several of these hold relative paths
    # ('/login', '/media/') or an empty base that AnyUrl rejects outright, and
    # this model's own validators consume others with string ops
    # (`APP_BASE_URL` via urljoin, `MITOL_API_BASE_URL` via .rstrip). AnyUrl
    # would also inject `Url` objects instead of str, changing runtime type
    # and breaking parity with the str-valued legacy settings. Keeping these
    # as str preserves the drop-in contract; the AnyUrl schema hint has no
    # payoff here.
    ACCESS_TOKEN_URL: str | None = Field(default=None, validation_alias=AliasChoices('ACCESS_TOKEN_URL'))
    APP_BASE_URL: str | None = Field(default=None, validation_alias=AliasChoices('MITOL_APP_BASE_URL'))
    AUTHORIZATION_URL: str | None = Field(default=None, validation_alias=AliasChoices('AUTHORIZATION_URL'))
    CKEDITOR_UPLOAD_URL: str | None = Field(default=None, validation_alias=AliasChoices('CKEDITOR_UPLOAD_URL'))
    FASTLY_URL: str = Field(default='https://api.fastly.com', validation_alias=AliasChoices('FASTLY_URL'))
    KEYCLOAK_BASE_URL: str = Field(default='http://mit-keycloak-base-url.edu', validation_alias=AliasChoices('KEYCLOAK_BASE_URL'))
    LOGIN_ERROR_URL: str = Field(default='/login')
    LOGIN_REDIRECT_URL: str = Field(default='/app')
    LOGIN_URL: str = Field(default='/login')
    LOGOUT_REDIRECT_URL: str = Field(default='/app')
    MEDIA_URL: str = Field(default='/media/')
    MICROMASTERS_CMS_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('MICROMASTERS_CMS_API_URL'))
    MITOL_API_BASE_URL: str = Field(default='', validation_alias=AliasChoices('MITOL_API_BASE_URL'))
    MITOL_NEW_USER_LOGIN_URL: str = Field(default='http://open.odl.local:8062/onboarding', validation_alias=AliasChoices('MITOL_NEW_USER_LOGIN_URL'))
    MITOL_TOS_URL: str | None = Field(default=None, validation_alias=AliasChoices('MITOL_TOS_URL'))
    OIDC_LOGOUT_URL: str | None = Field(default=None, validation_alias=AliasChoices('OIDC_LOGOUT_URL'))
    OPENSEARCH_URL: str | None = Field(default=None, validation_alias=AliasChoices('OPENSEARCH_URL'))
    POSTHOG_API_HOST: str = Field(default='https://us.posthog.com', validation_alias=AliasChoices('POSTHOG_API_HOST'))
    QDRANT_HOST: str = Field(default='http://qdrant:6333', validation_alias=AliasChoices('QDRANT_HOST'))
    STATIC_URL: str = Field(default='/static/')
    USERINFO_URL: str | None = Field(default=None, validation_alias=AliasChoices('USERINFO_URL'))
    CELERY_BROKER_URL: str | None = Field(default=None, validation_alias=AliasChoices('CELERY_BROKER_URL'))
    REDIS_URL: str | None = Field(default=None, validation_alias=AliasChoices('REDIS_URL'))
    BLOCKLISTED_COURSES_URL: str = Field(default='https://raw.githubusercontent.com/mitodl/open-resource-blocklists/master/courses.txt', validation_alias=AliasChoices('BLOCKLISTED_COURSES_URL'))
    CONTENT_BASE_URL_EDX: str = Field(default='https://courses.edx.org', validation_alias=AliasChoices('CONTENT_BASE_URL_EDX'))
    CONTENT_BASE_URL_MITXONLINE: str = Field(default='https://courses.mitxonline.mit.edu', validation_alias=AliasChoices('CONTENT_BASE_URL_MITXONLINE'))
    CONTENT_BASE_URL_OLL: str = Field(default='https://openlearninglibrary.mit.edu', validation_alias=AliasChoices('CONTENT_BASE_URL_OLL'))
    CONTENT_BASE_URL_XPRO: str = Field(default='https://courses.xpro.mit.edu', validation_alias=AliasChoices('CONTENT_BASE_URL_XPRO'))
    CSAIL_BASE_URL: str | None = Field(default=None, validation_alias=AliasChoices('CSAIL_BASE_URL'))
    DUPLICATE_COURSES_URL: str | None = Field(default=None, validation_alias=AliasChoices('DUPLICATE_COURSES_URL'))
    EDX_ALT_URL: str = Field(default='https://courses.edx.org/', validation_alias=AliasChoices('EDX_ALT_URL'))
    EDX_API_ACCESS_TOKEN_URL: str | None = Field(default=None, validation_alias=AliasChoices('EDX_API_ACCESS_TOKEN_URL'))
    EDX_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('EDX_API_URL'))
    EDX_BASE_URL: str = Field(default='https://www.edx.org/', validation_alias=AliasChoices('EDX_BASE_URL'))
    EDX_PROGRAMS_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('EDX_PROGRAMS_API_URL'))
    MICROMASTERS_CATALOG_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('MICROMASTERS_CATALOG_API_URL'))
    MITPE_BASE_URL: str = Field(default='https://professional.mit.edu/', validation_alias=AliasChoices('MITPE_BASE_URL'))
    MITX_ONLINE_BASE_URL: str | None = Field(default=None, validation_alias=AliasChoices('MITX_ONLINE_BASE_URL'))
    MITX_ONLINE_COURSES_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('MITX_ONLINE_COURSES_API_URL'))
    MITX_ONLINE_PROGRAMS_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('MITX_ONLINE_PROGRAMS_API_URL'))
    MIT_CLIMATE_BASE_URL: str = Field(default='https://climate.mit.edu')
    OCW_BASE_URL: str = Field(default='http://ocw.mit.edu/', validation_alias=AliasChoices('OCW_BASE_URL'))
    OVS_API_BASE_URL: str | None = Field(default=None, validation_alias=AliasChoices('OVS_API_BASE_URL'))
    SEE_API_ACCESS_TOKEN_URL: str | None = Field(default=None, validation_alias=AliasChoices('SEE_API_ACCESS_TOKEN_URL'))
    SEE_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('SEE_API_URL'))
    SEE_BASE_URL: str | None = Field(default=None, validation_alias=AliasChoices('SEE_BASE_URL'))
    XPRO_CATALOG_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('XPRO_CATALOG_API_URL'))
    XPRO_COURSES_API_URL: str | None = Field(default=None, validation_alias=AliasChoices('XPRO_COURSES_API_URL'))
    YOUTUBE_CONFIG_URL: str | None = Field(default=None, validation_alias=AliasChoices('YOUTUBE_CONFIG_URL'))

    # Overrides of generated fields: legacy uses get_string(name, False), so
    # the value is `False` when unset and a string when set — the generated
    # `str` annotation rejects the bool default under validate_default.
    AWS_STORAGE_BUCKET_NAME: str | bool = Field(
        default=False, validation_alias=AliasChoices("AWS_STORAGE_BUCKET_NAME")
    )
    AWS_QUERYSTRING_AUTH: str | bool = Field(
        default=False, validation_alias=AliasChoices("AWS_QUERYSTRING_AUTH")
    )
    DATABASE_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("DATABASE_URL"),
        description=(
            "dj-database-url connection string; defaults to a local sqlite "
            "db under BASE_DIR when unset"
        ),
    )
    MITOL_DB_DISABLE_SS_CURSORS: bool = Field(
        default=True, validation_alias=AliasChoices("MITOL_DB_DISABLE_SS_CURSORS")
    )
    MITOL_DB_CONN_MAX_AGE: int = Field(
        default=0, validation_alias=AliasChoices("MITOL_DB_CONN_MAX_AGE")
    )
    MITOL_DB_DISABLE_SSL: bool = Field(
        default=False, validation_alias=AliasChoices("MITOL_DB_DISABLE_SSL")
    )
    REDISCLOUD_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("REDISCLOUD_URL"),
        description="Legacy Heroku-style Redis URL; used as a REDIS_URL fallback",
    )
    RUN_DATA_MIGRATIONS: bool = Field(
        default=False, validation_alias=AliasChoices("RUN_DATA_MIGRATIONS")
    )
    HEROKU_APP_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("HEROKU_APP_NAME")
    )
    HEROKU_PARENT_APP_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("HEROKU_PARENT_APP_NAME")
    )
    # Celery beat schedule intervals (legacy read these env vars inline in
    # main/settings_celery.py's CELERY_BEAT_SCHEDULE dict).
    NEWS_EVENTS_MEDIUM_NEWS_SCHEDULE_SECONDS: int = Field(default=60 * 60 * 3)
    NEWS_EVENTS_MITPE_EVENTS_SCHEDULE_SECONDS: int = Field(default=60 * 60 * 3)
    NEWS_EVENTS_MITPE_NEWS_SCHEDULE_SECONDS: int = Field(default=60 * 60 * 3)
    NEWS_EVENTS_OL_EVENTS_SCHEDULE_SECONDS: int = Field(default=60 * 60 * 3)
    NEWS_EVENTS_ARTICLES_NEWS_SCHEDULE_SECONDS: int = Field(default=60 * 60 * 1)
    NEWS_EVENTS_WEBSITE_CONTENT_NEWS_SCHEDULE_SECONDS: int | None = Field(
        default=None,
        description="Falls back to NEWS_EVENTS_ARTICLES_NEWS_SCHEDULE_SECONDS",
    )
    SCRAPE_MARKETING_PAGES_SCHEDULE_SECONDS: int = Field(default=60 * 60 * 12)
    EMBED_NEW_RESOURCES_SCHEDULE_SECONDS: int | None = Field(
        default=None, description="Falls back to 60 * EMBEDDING_SCHEDULE_MINUTES"
    )
    EMBED_NEW_CONTENT_FILES_SCHEDULE_SECONDS: int | None = Field(
        default=None, description="Falls back to 60 * EMBEDDING_SCHEDULE_MINUTES"
    )
    # SCIM_SERVICE_PROVIDER comes from mitol.scim.settings.scim (a star-import
    # in the legacy settings, invisible to static discovery); the legacy
    # settings then patch USER_ADAPTER for mit-learn.
    SCIM_SERVICE_PROVIDER: dict[str, Any] = Field(
        default_factory=lambda: {
            **MITOL_SCIM_SERVICE_PROVIDER,
            "USER_ADAPTER": "users.adapters.LearnUserAdapter",
        }
    )
    # LOGGING is imported (not assigned) in the legacy settings:
    # `from mitol.observability.settings.logging import LOGGING`.
    LOGGING: dict[str, Any] | None = Field(default=None)
    # Override of the generated field: mitol's EnvParser declares this
    # `required=True` (with default=250), but mit-learn never calls
    # env.validate(), so the legacy runtime treats it as optional-with-default.
    MITOL_SCIM_KEYCLOAK_BULK_OPERATIONS_COUNT: int = Field(
        default=250,
        validation_alias=AliasChoices("MITOL_SCIM_KEYCLOAK_BULK_OPERATIONS_COUNT"),
        description="Number of operations to perform per bulk request",
    )

    # ------------------------------------------------------------------ #
    # Derived settings                                                   #
    #                                                                    #
    # Validators run in definition order; the ordering below matters     #
    # (BASE_DIR before DATABASES/TEMPLATES, redis chain before CACHES,   #
    # tombstone parsing before the conditional-middleware step).         #
    # ------------------------------------------------------------------ #

    @model_validator(mode="after")
    def check_required_settings(self) -> AqueductSettings:
        """Mirror the legacy fail-fast requirements from main/settings.py.

        SECRET_KEY and WEBHOOK_SECRET are a deliberate policy change: the
        legacy hardcoded fallbacks ('terribly_unsafe_default_secret_key',
        'please-change-this') were security bugs and are not reproduced.
        """
        required = {
            "SECRET_KEY": self.SECRET_KEY,
            "WEBHOOK_SECRET": self.WEBHOOK_SECRET,
            "MITOL_APP_BASE_URL": self.APP_BASE_URL,
            "MAILGUN_SENDER_DOMAIN": self.MAILGUN_SENDER_DOMAIN,
            "MAILGUN_KEY": self.MAILGUN_KEY,
            "MITOL_COOKIE_NAME": self.MITOL_COOKIE_NAME,
            "MITOL_COOKIE_DOMAIN": self.MITOL_COOKIE_DOMAIN,
            "OPENSEARCH_URL": self.OPENSEARCH_URL,
        }
        missing = [name for name, value in required.items() if not value]
        if missing:
            msg = f"The following settings are not set: {', '.join(missing)}"
            raise ImproperlyConfigured(msg)
        return self

    @model_validator(mode="after")
    def restore_redacted_defaults(self) -> AqueductSettings:
        """Restore legacy defaults for fields the generator redacted by name.

        Static discovery renders secret-looking names as optional-None; the
        legacy module gave several of them benign non-None defaults.
        """
        if self.SENTRY_DSN is None:
            self.SENTRY_DSN = ""
        if self.STATUS_TOKEN is None:
            self.STATUS_TOKEN = ""
        if self.FASTLY_API_KEY is None:
            self.FASTLY_API_KEY = ""
        if self.RECAPTCHA_SECRET_KEY is None:
            self.RECAPTCHA_SECRET_KEY = ""
        if self.EMAIL_HOST_PASSWORD is None:
            self.EMAIL_HOST_PASSWORD = ""
        if self.QDRANT_API_KEY is None:
            self.QDRANT_API_KEY = ""
        if self.POSTHOG_PROJECT_API_KEY is None:
            self.POSTHOG_PROJECT_API_KEY = ""
        if self.CORS_ALLOW_CREDENTIALS is None:
            self.CORS_ALLOW_CREDENTIALS = True
        if self.MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS is None:
            self.MITOL_UNSUBSCRIBE_TOKEN_MAX_AGE_SECONDS = 60 * 60 * 24 * 7
        if self.MITOL_JWT_SECRET is None:
            self.MITOL_JWT_SECRET = "terribly_unsafe_default_jwt_secret_key"
        return self

    @model_validator(mode="after")
    def build_base_dir_and_paths(self) -> AqueductSettings:
        """Mirror BASE_DIR and the x509 file paths from main/settings.py."""
        if self.BASE_DIR is None:
            self.BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.MIT_WS_CERTIFICATE_FILE = os.path.join(self.STATIC_ROOT, "mit_x509.cert")
        self.MIT_WS_PRIVATE_KEY_FILE = os.path.join(self.STATIC_ROOT, "mit_x509.key")
        return self

    @model_validator(mode="after")
    def build_templates(self) -> AqueductSettings:
        """Mirror main/settings.py's TEMPLATES, which references BASE_DIR."""
        self.TEMPLATES = [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [
                    self.BASE_DIR + "/templates/",
                ],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                        "social_django.context_processors.backends",
                        "social_django.context_processors.login_redirect",
                    ]
                },
            }
        ]
        return self

    @model_validator(mode="after")
    def build_urls(self) -> AqueductSettings:
        """Mirror the URL settings derived from other settings in main/settings.py."""
        if self.OIDC_LOGOUT_URL is None:
            # urljoin might lead to wrong outputs with url rewrites like
            # https://api.learn.mit.edu/learn/, so using rstrip('/') instead.
            self.OIDC_LOGOUT_URL = f"{self.MITOL_API_BASE_URL.rstrip('/')}/logout/oidc"
        if self.MITOL_TOS_URL is None:
            self.MITOL_TOS_URL = urljoin(self.APP_BASE_URL, "/terms-and-conditions/")
        self.MIT_CLIMATE_EXPLAINERS_API_URL = (
            f"{self.MIT_CLIMATE_BASE_URL}/feeds/explainers"
        )
        self.ASK_MIT_CLIMATE_API_URL = f"{self.MIT_CLIMATE_BASE_URL}/feeds/ask-mit-climate"
        self.REST_FRAMEWORK_EXTENSIONS = {
            "DEFAULT_PARENT_LOOKUP_KWARG_NAME_PREFIX": self.DRF_NESTED_PARENT_LOOKUP_PREFIX
        }
        return self

    @model_validator(mode="after")
    def build_flashcard_prompt(self) -> AqueductSettings:
        """Mirror main/settings.py's CONTENT_SUMMARIZER_FLASHCARD_PROMPT default."""
        if self.CONTENT_SUMMARIZER_FLASHCARD_PROMPT is None:
            self.CONTENT_SUMMARIZER_FLASHCARD_PROMPT = (
                f"""
        You are an expert instructor creating study flashcards.
        Generate exactly {self.CONTENT_SUMMARIZER_FLASHCARD_QUANTITY}
        high-quality flashcards from the transcript below.
        """
                """
        Rules:
        - Use the same language as the transcript for both questions and answers.
        - Focus ONLY on core concepts, methods, definitions,
          reasoning, and cause-effect relationships.
        - Questions must test understanding or application,
          not recall of names, timestamps, or anecdotes.
        - Avoid trivia, meta information
        - avoid details about the speaker or course logistics.
        - Prefer "why", "how", "compare", "explain", or "apply" style questions.
        - Each answer should be concise but complete (1-3 sentences).

        Transcript:
        {content}
        """
            )
        return self

    @model_validator(mode="after")
    def build_redis_and_celery(self) -> AqueductSettings:
        """Mirror main/settings_celery.py's Redis fallback chain and rate limits."""
        self.REDIS_URL = dv.first_url(self.REDIS_URL, self.REDISCLOUD_URL)
        self.CELERY_BROKER_URL = dv.first_url(self.CELERY_BROKER_URL, self.REDIS_URL)
        self.CELERY_RESULT_BACKEND = dv.first_url(
            self.CELERY_RESULT_BACKEND, self.REDIS_URL
        )
        if self.CELERY_SEARCH_RATE_LIMIT is None:
            self.CELERY_SEARCH_RATE_LIMIT = self.CELERY_RATE_LIMIT
        if self.CELERY_VECTOR_SEARCH_RATE_LIMIT is None:
            self.CELERY_VECTOR_SEARCH_RATE_LIMIT = self.CELERY_RATE_LIMIT
        self.QDRANT_EMBEDDINGS_TASK_LOOKBACK_WINDOW = (
            self.EMBEDDING_SCHEDULE_MINUTES + 60
        )
        return self

    @model_validator(mode="after")
    def build_caches(self) -> AqueductSettings:
        """Mirror main/settings.py's CACHES (redis LOCATION = CELERY_BROKER_URL)."""
        self.CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            # cache specific to widgets
            "external_assets": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "external_asset_cache",
            },
            # general durable cache (redis should be considered ephemeral)
            "durable": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "durable_cache",
            },
            "redis": dv.redis_cache(
                self.CELERY_BROKER_URL,
                CLIENT_CLASS="django_redis.client.DefaultClient",
            ),
            # imagekit caching
            "imagekit": {
                "BACKEND": "main.cache.backends.FallbackCache",
                "LOCATION": ["imagekit_redis", "imagekit_db"],
            },
            "imagekit_redis": {
                "BACKEND": "main.cache.backends.FallbackCache",
                "LOCATION": ["redis"],
                "TIMEOUT": 60 * 60,
            },
            "imagekit_db": {
                "BACKEND": "django.core.cache.backends.db.DatabaseCache",
                "LOCATION": "imagekit_cache",
                "TIMEOUT": None,
            },
        }
        return self

    @model_validator(mode="after")
    def build_celery_beat_schedule(self) -> AqueductSettings:
        """Rebuild main/settings_celery.py's CELERY_BEAT_SCHEDULE.

        The legacy dict reads its interval env vars inline; here they are
        typed fields so the model is safe to run under celery worker/beat.
        """
        website_content_news_seconds = (
            self.NEWS_EVENTS_WEBSITE_CONTENT_NEWS_SCHEDULE_SECONDS
            if self.NEWS_EVENTS_WEBSITE_CONTENT_NEWS_SCHEDULE_SECONDS is not None
            else self.NEWS_EVENTS_ARTICLES_NEWS_SCHEDULE_SECONDS
        )
        embed_new_resources_seconds = (
            self.EMBED_NEW_RESOURCES_SCHEDULE_SECONDS
            if self.EMBED_NEW_RESOURCES_SCHEDULE_SECONDS is not None
            else 60 * self.EMBEDDING_SCHEDULE_MINUTES
        )
        embed_new_content_files_seconds = (
            self.EMBED_NEW_CONTENT_FILES_SCHEDULE_SECONDS
            if self.EMBED_NEW_CONTENT_FILES_SCHEDULE_SECONDS is not None
            else 60 * self.EMBEDDING_SCHEDULE_MINUTES
        )
        self.CELERY_BEAT_SCHEDULE = (
            {}
            if self.CELERY_BEAT_DISABLED
            else {
                "update_next-start-date-every-1-days": {
                    "task": "learning_resources.tasks.update_next_start_date_and_prices",
                    "schedule": crontab(minute=0, hour=7),  # 3:00am EST
                },
                "update_edx-courses-every-1-days": {
                    "task": "learning_resources.tasks.get_mit_edx_data",
                    "schedule": crontab(minute=0, hour=5),
                },
                "update-edx-files-every-1-day": {
                    "task": "learning_resources.tasks.import_all_mit_edx_files",
                    "schedule": crontab(minute=0, hour=6),
                },
                "update-micromasters-programs-every-1-days": {
                    "task": "learning_resources.tasks.get_micromasters_data",
                    "schedule": crontab(minute=0, hour=5),  # 1:00am EST
                },
                "update-mit-climate-articles-every-1-days": {
                    "task": "learning_resources.tasks.get_mit_climate_data",
                    "schedule": crontab(minute=30, hour=5),  # 1:30am EST
                },
                "update-mitxonline-courses-every-6-hours": {
                    "task": "learning_resources.tasks.get_mitxonline_data",
                    "schedule": crontab(minute=0, hour="*/6"),
                },
                "update-mitxonline-files-every-1-day": {
                    "task": "learning_resources.tasks.import_all_mitxonline_files",
                    "schedule": crontab(minute=0, hour=7),
                },
                "update-podcasts": {
                    "task": "learning_resources.tasks.get_podcast_data",
                    "schedule": crontab(minute=0, hour="6,23"),  # 2am and 7pm EST
                },
                "update-professional-ed-resources-every-1-days": {
                    "task": "learning_resources.tasks.get_mitpe_data",
                    "schedule": crontab(minute=0, hour=21),  # 5:00pm EST
                },
                "update-xpro-courses-every-1-days": {
                    "task": "learning_resources.tasks.get_xpro_data",
                    "schedule": crontab(minute=0, hour=5),  # 1:00am EST
                },
                "update-xpro-files-every-1-day": {
                    "task": "learning_resources.tasks.import_all_xpro_files",
                    "schedule": crontab(minute=0, hour=8),
                },
                "update-youtube-videos": {
                    "task": "learning_resources.tasks.get_youtube_data",
                    "schedule": crontab(minute=30, hour=8),  # 4:30am EST
                },
                "update-ovs-videos": {
                    "task": "learning_resources.tasks.get_ovs_data",
                    "schedule": crontab(minute=0, hour=9),  # 5:00am EST
                },
                "update-ovs-transcripts": {
                    "task": "learning_resources.tasks.get_ovs_transcripts",
                    "schedule": crontab(minute=30, hour=9),  # 5:30am EST
                },
                "update_medium_mit_news": {
                    "task": "news_events.tasks.get_medium_mit_news",
                    "schedule": self.NEWS_EVENTS_MEDIUM_NEWS_SCHEDULE_SECONDS,
                },
                "update_mitpe_events": {
                    "task": "news_events.tasks.get_mitpe_events",
                    "schedule": self.NEWS_EVENTS_MITPE_EVENTS_SCHEDULE_SECONDS,
                },
                "update_mitpe_news": {
                    "task": "news_events.tasks.get_mitpe_news",
                    "schedule": self.NEWS_EVENTS_MITPE_NEWS_SCHEDULE_SECONDS,
                },
                "update_sloan_courses": {
                    "task": "learning_resources.tasks.get_sloan_data",
                    "schedule": crontab(minute=30, hour=4),  # 12:30am EST
                },
                "update_ol_events": {
                    "task": "news_events.tasks.get_ol_events",
                    "schedule": self.NEWS_EVENTS_OL_EVENTS_SCHEDULE_SECONDS,
                },
                "update_website_content_news": {
                    "task": "news_events.tasks.get_website_content_news",
                    "schedule": website_content_news_seconds,
                },
                "sync_canvas_courses-every-1-weeks": {
                    "task": "learning_resources.tasks.sync_canvas_courses",
                    "schedule": crontab(
                        minute=0, hour=5, day_of_week=0
                    ),  # 12:00 PM EST on Sundays
                    "kwargs": {"overwrite": False},
                },
                "update_posthog_events": {
                    "task": "learning_resources.tasks.get_learning_resource_views",
                    "schedule": self.NEWS_EVENTS_OL_EVENTS_SCHEDULE_SECONDS,
                },
                "send-subscription-emails-every-1-days": {
                    "task": "learning_resources_search.tasks.send_subscription_emails",
                    "schedule": crontab(minute=30, hour=18),  # 2:30pm EST
                    "kwargs": {
                        "period": "daily",
                        "subscription_type": "channel_subscription_type",
                    },
                },
                "send-search-subscription-emails-every-1-days": {
                    "task": "learning_resources_search.tasks.send_subscription_emails",
                    "schedule": crontab(minute=0, hour=19),  # 3:00pm EST
                    "kwargs": {
                        "period": "daily",
                        "subscription_type": "search_subscription_type",
                    },
                },
                "update-search-featured-ranks-1-days": {
                    "task": "learning_resources_search.tasks.update_featured_rank",
                    "schedule": crontab(minute=30, hour=7),  # 3:30am EST
                },
                "scrape-marketing-pages-every-1-days": {
                    "task": "learning_resources.tasks.scrape_marketing_pages",
                    "schedule": self.SCRAPE_MARKETING_PAGES_SCHEDULE_SECONDS,
                },
                "daily_embed_new_learning_resources": {
                    "task": "vector_search.tasks.embed_new_learning_resources",
                    "schedule": embed_new_resources_seconds,
                },
                "daily_embed_new_content_files": {
                    "task": "vector_search.tasks.embed_new_content_files",
                    "schedule": embed_new_content_files_seconds,
                },
                "daily_topic_embeddings_sync": {
                    "task": "vector_search.tasks.sync_topics",
                    "schedule": crontab(minute=0, hour="6,18,23"),  # 2am 2pm 7pm EST
                },
                "daily_tune_qdrant_collections": {
                    "task": "vector_search.tasks.tune_qdrant_collections",
                    "schedule": crontab(minute=0, hour=10),  # once per day
                },
                "weekly_check_missing_embeddings": {
                    "task": "vector_search.tasks.embeddings_healthcheck",
                    "schedule": crontab(
                        minute=0, hour=6, day_of_week=6
                    ),  # 2:00am EST on Friday
                },
                "cleanup-deleted-content-files-every-1-days": {
                    "task": "learning_resources.tasks.cleanup_deleted_content_files",
                    "schedule": crontab(
                        minute=0, hour=4
                    ),  # 04:00 UTC (midnight ET during DST, 11pm ET standard)
                },
            }
        )
        return self

    @model_validator(mode="after")
    def build_databases(self) -> AqueductSettings:
        """Mirror main/settings.py's DATABASES via the shared derivation.

        `django_aqueduct.derivations.database_config` never applies sslmode
        to SQLite URLs — a deliberate fix over the legacy code, which added
        OPTIONS={"sslmode": "require"} even to the sqlite fallback.
        """
        database_url = self.DATABASE_URL or "sqlite:///{}".format(
            os.path.join(self.BASE_DIR, "db.sqlite3")
        )
        config = dv.database_config(
            database_url,
            conn_max_age=self.MITOL_DB_CONN_MAX_AGE,
            ssl_require=not self.MITOL_DB_DISABLE_SSL,
        )
        config["DISABLE_SERVER_SIDE_CURSORS"] = self.MITOL_DB_DISABLE_SS_CURSORS
        self.DEFAULT_DATABASE_CONFIG = config
        self.DATABASES = {"default": config}
        return self

    @model_validator(mode="after")
    def build_email_and_admins(self) -> AqueductSettings:
        """Mirror ANYMAIL and ADMINS from main/settings.py."""
        self.ANYMAIL = {
            "MAILGUN_API_KEY": self.MAILGUN_KEY,
            "MAILGUN_SENDER_DOMAIN": self.MAILGUN_SENDER_DOMAIN,
        }
        self.ADMINS = (
            (("Admins", self.ADMIN_EMAIL),) if self.ADMIN_EMAIL != "" else ()
        )
        return self

    @model_validator(mode="after")
    def build_jwt_auth(self) -> AqueductSettings:
        """Mirror JWT_AUTH from main/settings.py."""
        self.JWT_AUTH = {
            "JWT_SECRET_KEY": self.MITOL_JWT_SECRET,
            "JWT_VERIFY": True,
            "JWT_VERIFY_EXPIRATION": True,
            "JWT_EXPIRATION_DELTA": datetime.timedelta(seconds=60 * 60),
            "JWT_ALLOW_REFRESH": True,
            "JWT_REFRESH_EXPIRATION_DELTA": datetime.timedelta(days=7),
            "JWT_AUTH_COOKIE": self.MITOL_COOKIE_NAME,
            "JWT_AUTH_HEADER_PREFIX": "Bearer",
        }
        return self

    @model_validator(mode="after")
    def build_features(self) -> AqueductSettings:
        """Mirror the FEATURE_* flag scan from main/settings.py.

        The legacy scan reads os.environ only; this also merges flags carried
        by the model itself (e.g. Vault-sourced extras via
        `django_aqueduct.derivations.feature_flags`), which the env scan
        cannot see.
        """
        prefix = self.MITOL_FEATURES_PREFIX
        features = {
            key[len(prefix) :]: get_bool(key, False)  # noqa: FBT003
            for key in os.environ
            if key.startswith(prefix)
        }
        # dict(self) iterates fields+extras without serializing (model_dump
        # would warn on opaque values like crontab/Logger objects).
        for flag, value in dv.feature_flags(dict(self), prefix=prefix).items():
            features[flag] = (
                value if isinstance(value, bool) else str(value).lower() == "true"
            )
        self.FEATURES = features
        return self

    @model_validator(mode="after")
    def build_opensearch_index(self) -> AqueductSettings:
        """Mirror the Heroku review-app OPENSEARCH_INDEX branch + fail-fast."""
        if self.HEROKU_PARENT_APP_NAME is not None:
            self.OPENSEARCH_INDEX = self.HEROKU_APP_NAME
        if not self.OPENSEARCH_INDEX:
            msg = "Missing OPENSEARCH_INDEX"
            raise ImproperlyConfigured(msg)
        return self

    @model_validator(mode="after")
    def build_storages(self) -> AqueductSettings:
        """Mirror the MITOL_USE_S3 storage branch from main/settings.py.

        When S3 is disabled the legacy module leaves STORAGES unset so Django
        falls back to its default; the model must carry that default
        explicitly because the adapter injects every model value.
        """
        if self.MITOL_USE_S3:
            if (
                not self.AWS_ACCESS_KEY_ID
                or not self.AWS_SECRET_ACCESS_KEY
                or not self.AWS_STORAGE_BUCKET_NAME
            ):
                msg = (
                    "You have enabled S3 support, but are missing one of "
                    "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, or "
                    "AWS_STORAGE_BUCKET_NAME"
                )
                raise ImproperlyConfigured(msg)
            storages = {
                "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
                "staticfiles": {
                    "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
                },
            }
            options = {}
            if self.AWS_S3_CUSTOM_DOMAIN:
                options["custom_domain"] = self.AWS_S3_CUSTOM_DOMAIN
            if self.AWS_S3_PREFIX:
                options["location"] = self.AWS_S3_PREFIX
            if options:
                storages["default"]["OPTIONS"] = options
            self.OPTIONS = options
            self.STORAGES = storages
        else:
            # Django 4.2's global default STORAGES.
            self.STORAGES = {
                "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
                "staticfiles": {
                    "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
                },
            }
        return self

    @model_validator(mode="after")
    def build_migration_modules(self) -> AqueductSettings:
        """Mirror the RUN_DATA_MIGRATIONS branch from main/settings.py."""
        if not self.RUN_DATA_MIGRATIONS:
            self.MIGRATION_MODULES = {"data_fixtures": None}
        else:
            self.MIGRATION_MODULES = {}
        return self

    @model_validator(mode="after")
    def build_logging(self) -> AqueductSettings:
        """Attach the structlog LOGGING config the legacy settings import."""
        if self.LOGGING is None:
            from mitol.observability.settings.logging import LOGGING  # noqa: PLC0415

            self.LOGGING = LOGGING
        if self.DEBUG:
            # allow for all IPs to be routable, including localhost, for testing
            self.IPWARE_PRIVATE_IP_PREFIX = ()
        return self

    @model_validator(mode="after")
    def build_cookie_tombstones(self) -> AqueductSettings:
        """Parse COOKIE_TOMBSTONES when a source supplied it as a JSON string."""
        if isinstance(self.COOKIE_TOMBSTONES, str):
            self.COOKIE_TOMBSTONES = parse_cookie_tombstones(self.COOKIE_TOMBSTONES)
        return self

    @model_validator(mode="after")
    def build_conditional_apps_and_middleware(self) -> AqueductSettings:
        """Mirror the conditional INSTALLED_APPS/MIDDLEWARE mutations in settings.py.

        In textual order: the zeal profiler (debug or pytest), the cookie
        tombstone middleware (only when tombstones are configured), the
        nplusone profiler (debug only), and the feature-flag middleware
        (only when a query-string prefix is configured).
        """
        installed_apps = list(self.INSTALLED_APPS)
        middleware = list(self.MIDDLEWARE)

        if self.ZEAL_ENABLE or self.ENVIRONMENT == "pytest":
            installed_apps.append("zeal")
            # this should be the first middleware so we catch any issues in
            # our own middleware — legacy appends, so mirror that.
            middleware.append("zeal.middleware.zeal_middleware")

        if self.COOKIE_TOMBSTONES:
            middleware.insert(
                0, "main.middleware.cookie_tombstones.CookieTombstoneMiddleware"
            )

        if self.DEBUG:
            installed_apps.append("nplusone.ext.django")
            middleware.append("nplusone.ext.django.NPlusOneMiddleware")

        if self.MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
            middleware.append(
                "main.middleware.feature_flags.QueryStringFeatureFlagMiddleware"
            )
            middleware.append(
                "main.middleware.feature_flags.CookieFeatureFlagMiddleware"
            )

        self.INSTALLED_APPS = tuple(installed_apps)
        self.MIDDLEWARE = tuple(middleware)
        return self
    # <<< aqueduct:preserved:validators


def init_sentry_from_model(model: AqueductSettings) -> None:
    """`pre_configure` hook: initialise Sentry from the validated model.

    Mirrors the legacy behaviour of calling init_sentry() at the top of
    main/settings.py, before the rest of the settings exist.
    """
    from main.sentry import init_sentry  # noqa: PLC0415

    init_sentry(
        dsn=model.SENTRY_DSN,
        environment=model.ENVIRONMENT,
        version=model.VERSION,
        log_level=model.SENTRY_LOG_LEVEL,
        traces_sample_rate=model.SENTRY_TRACES_SAMPLE_RATE,
        profiles_sample_rate=model.SENTRY_PROFILES_SAMPLE_RATE,
    )


class DevAqueductSettings(AqueductSettings, VaultDevBase):
    """Local-dev variant: layers an env-configured Vault source over the base.

    Source wiring comes from `django_aqueduct.sources.dev.VaultDevBase`, which
    *prepends* the Vault source (Vault values win over local env vars) and is
    configured entirely from the environment:

      VAULT_ADDR         Vault server URL (unset → run without Vault)
      VAULT_MOUNT        KV mount point, e.g. "secret-mitlearn"
      VAULT_PATH         KV secret path (required when VAULT_ADDR is set)
      VAULT_KV_VERSION   "1" or "2" (default "2")
      VAULT_AUTH_METHOD  token | oidc | kubernetes (use "oidc" for dev login)
      VAULT_ROLE         role name for oidc/kubernetes auth

    Misconfiguration raises an actionable VaultConfigError instead of the old
    bare `KeyError: 'VAULT_ADDR'`, and leaving VAULT_ADDR unset simply runs
    without Vault.
    """
