# Generated by Django 4.2.25 on 2026-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website_content", "0003_add_editors_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecontent",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
