# Generated by Django 4.2.30 on 2026-06-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website_content", "0004_alter_websitecontent_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="cover_image",
            field=models.URLField(blank=True, default="", max_length=2083),
        ),
    ]
