# Generated by Django 4.2.30 on 2026-08-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website_content", "0006_add_deleted_to_websitecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecontent",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="websitecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted__isnull", True)),
                fields=("slug",),
                name="unique_slug_among_undeleted",
            ),
        ),
    ]
