# Generated by Django 5.2.17 on 2026-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0124_credential_metadata"),
        ("website_content", "0007_slug_unique_among_undeleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="topics",
            field=models.ManyToManyField(
                blank=True,
                related_name="website_content",
                to="learning_resources.learningresourcetopic",
            ),
        ),
    ]
