# Generated by Django 5.2.17 on 2026-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website_content", "0008_add_topics_to_websitecontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="seo_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="websitecontent",
            name="seo_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
