apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: django-media
  name: django-media
  namespace: learn-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
