apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -vv -f docker-compose.yml convert --controller deployment --pvc-request-size 2000Mi --out kompose/ --profile backend --profile frontend --namespace learn-ai
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: opensearch-node-mitopen-1
  name: opensearch-node-mitopen-1
  namespace: learn-ai
spec:
  ports:
    - name: "9100"
      port: 9100
      targetPort: 9200
    - name: "9500"
      port: 9500
      targetPort: 9600
  selector:
    io.kompose.service: opensearch-node-mitopen-1
