apiVersion: v1
data:
  CSRF_COOKIE_NAME: csrftoken-local
  MITOL_API_BASE_URL: http://api.open.odl.local:8063
  MITOL_APP_BASE_URL: http://open.odl.local:8062
  MITOL_SUPPORT_EMAIL: support@localhost
  POSTHOG_TIMEOUT_MS: "1500"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: ai-shared-env
  name: shared-env
  namespace: learn-ai
