apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -vv -f docker-compose.yml convert --controller deployment --pvc-request-size 2000Mi --out kompose/ --profile backend --profile frontend --namespace learn-ai
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: tika
  name: tika
  namespace: learn-ai
spec:
  ports:
    - name: "9998"
      port: 9998
      targetPort: 9998
  selector:
    io.kompose.service: tika
