# Generated by Django 4.2.30 on 2026-07-10 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("course_id", models.CharField(max_length=255)),
                ("course_name", models.CharField(blank=True, max_length=255)),
                ("block_usage_key", models.CharField(db_index=True, max_length=255)),
                ("block_type", models.CharField(blank=True, max_length=64)),
                ("block_display_name", models.CharField(blank=True, max_length=255)),
                ("unit_title", models.CharField(blank=True, max_length=255)),
                ("url", models.TextField(blank=True)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("idea", "Idea"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["course_id", "created_on"],
                        name="content_fb_course_time_idx",
                    )
                ],
            },
        ),
    ]
