/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * MIT Learn API
 * MIT public API
 * Service version: 0.0.1 (v1)
 */
import { FormData } from "https://jslib.k6.io/formdata/0.0.2/index.js"

import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js"

import http from "k6/http"
import type { Params, Response } from "k6/http"

import type {
  ArticleImageUploadRequest,
  ArticlesListParams,
  ContentFile,
  ContentFileSearchResponse,
  ContentFileSearchRetrieveParams,
  ContentFileWebHookRequest,
  ContentFileWebHookRequestRequest,
  ContentfilesListParams,
  CourseFeaturesListParams,
  CourseResource,
  CoursesContentfilesListParams,
  CoursesListParams,
  DepartmentsListParams,
  FeaturedListParams,
  HubspotCollectionResponseFormDefinitionBaseForwardPaging,
  HubspotFormDefinition,
  HubspotFormSubmitRequestRequest,
  HubspotFormSubmitResponse,
  HubspotFormsDetailRetrieveParams,
  HubspotFormsListParams,
  LearningPathRelationship,
  LearningPathRelationshipRequest,
  LearningPathResource,
  LearningPathResourceRequest,
  LearningResource,
  LearningResourceContentTag,
  LearningResourceDepartment,
  LearningResourceDisplayInfoListParams,
  LearningResourceDisplayInfoResponse,
  LearningResourceOfferorDetail,
  LearningResourcePlatform,
  LearningResourceRelationship,
  LearningResourceSchool,
  LearningResourceTopic,
  LearningResourcesContentfilesListParams,
  LearningResourcesItemsListParams,
  LearningResourcesLearningPathsPartialUpdateParams,
  LearningResourcesListParams,
  LearningResourcesSearchResponse,
  LearningResourcesSearchRetrieveParams,
  LearningResourcesSimilarListParams,
  LearningResourcesSummaryListParams,
  LearningResourcesUserSubscriptionCheckListParams,
  LearningResourcesUserSubscriptionListParams,
  LearningResourcesUserSubscriptionSubscribeCreateParams,
  LearningResourcesUserlistsPartialUpdateParams,
  LearningResourcesVectorSimilarListParams,
  LearningpathsItemsListParams,
  LearningpathsListParams,
  MediaUpload201,
  MicroLearningPathRelationship,
  MicroUserListRelationship,
  OfferorsListParams,
  PaginatedContentFileList,
  PaginatedCourseResourceList,
  PaginatedLearningPathRelationshipList,
  PaginatedLearningPathResourceList,
  PaginatedLearningResourceContentTagList,
  PaginatedLearningResourceDepartmentList,
  PaginatedLearningResourceDisplayInfoResponseList,
  PaginatedLearningResourceList,
  PaginatedLearningResourceOfferorDetailList,
  PaginatedLearningResourcePlatformList,
  PaginatedLearningResourceRelationshipList,
  PaginatedLearningResourceSchoolList,
  PaginatedLearningResourceSummaryList,
  PaginatedLearningResourceTopicList,
  PaginatedPodcastEpisodeResourceList,
  PaginatedPodcastResourceList,
  PaginatedProgramResourceList,
  PaginatedRichTextArticleList,
  PaginatedUserListList,
  PaginatedUserListRelationshipList,
  PaginatedVideoPlaylistResourceList,
  PaginatedVideoResourceList,
  PatchedLearningPathRelationshipRequest,
  PatchedLearningPathResourceRequest,
  PatchedLearningResourceRelationshipRequest,
  PatchedRichTextArticleRequest,
  PatchedUserListRelationshipRequest,
  PatchedUserListRequest,
  PercolateQuery,
  PercolateQuerySubscriptionRequestRequest,
  PlatformsListParams,
  PodcastEpisodeResource,
  PodcastEpisodesListParams,
  PodcastResource,
  PodcastsItemsListParams,
  PodcastsListParams,
  ProgramLetter,
  ProgramResource,
  ProgramsListParams,
  RichTextArticle,
  RichTextArticleRequest,
  SchoolsListParams,
  TopicsListParams,
  UserList,
  UserListRelationship,
  UserListRelationshipRequest,
  UserListRequest,
  UserlistsItemsListParams,
  UserlistsListParams,
  VideoPlaylistResource,
  VideoPlaylistsItemsListParams,
  VideoPlaylistsListParams,
  VideoResource,
  VideoShortWebhookRequestRequest,
  VideosListParams,
  WebhookResponse,
  WebhooksContentFilesCreateParams,
  WebhooksVideoShortsCreateParams,
} from "./api.schemas"

/**
 * This is the base client to use for interacting with the API.
 */
export class MITLearnAPIClient {
  private cleanBaseUrl: string
  private commonRequestParameters: Params

  constructor(clientOptions: {
    baseUrl: string
    commonRequestParameters?: Params
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "")

    this.commonRequestParameters = clientOptions.commonRequestParameters || {}
  }

  /**
   * Get a paginated list of articles
   * @summary List
   */
  articlesList(
    params?: ArticlesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedRichTextArticleList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/articles/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "articles_list",
    }
  }

  /**
   * Create a new article
   * @summary Create
   */
  articlesCreate(
    richTextArticleRequest: RichTextArticleRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: RichTextArticle
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/articles/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(richTextArticleRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "articles_create",
    }
  }

  /**
   * Retrieve a single article
   * @summary Retrieve
   */
  articlesRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: RichTextArticle
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/articles/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "articles_retrieve",
    }
  }

  /**
   * Update an article
   * @summary Update
   */
  articlesPartialUpdate(
    id: number,
    patchedRichTextArticleRequest: PatchedRichTextArticleRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: RichTextArticle
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/articles/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedRichTextArticleRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "articles_partial_update",
    }
  }

  /**
   * Delete an article
   * @summary Destroy
   */
  articlesDestroy(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/articles/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "articles_destroy",
    }
  }

  /**
   * If the path parameter is numeric → ID, else → slug.
   * @summary Retrieve article by ID or slug
   */
  articlesDetailRetrieve(
    identifier: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: RichTextArticle
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/articles/detail/${identifier}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "articles_detail_retrieve",
    }
  }

  /**
   * Search for content files
   * @summary Search
   */
  contentFileSearchRetrieve(
    params?: ContentFileSearchRetrieveParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: ContentFileSearchResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/content_file_search/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "content_file_search_retrieve",
    }
  }

  /**
   * Viewset for ContentFiles
   * @summary List
   */
  contentfilesList(
    params?: ContentfilesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedContentFileList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/contentfiles/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "contentfiles_list",
    }
  }

  /**
   * Viewset for ContentFiles
   * @summary Retrieve
   */
  contentfilesRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: ContentFile
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/contentfiles/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "contentfiles_retrieve",
    }
  }

  /**
   * Course Features and Content Feature Types
   * @summary List
   */
  courseFeaturesList(
    params?: CourseFeaturesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceContentTagList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/course_features/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "course_features_list",
    }
  }

  /**
   * Course Features and Content Feature Types
   * @summary Retrieve
   */
  courseFeaturesRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceContentTag
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/course_features/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "course_features_retrieve",
    }
  }

  /**
   * Get a paginated list of courses
   * @summary List
   */
  coursesList(
    params?: CoursesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedCourseResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/courses/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "courses_list",
    }
  }

  /**
   * Retrieve a single course
   * @summary Retrieve
   */
  coursesRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: CourseResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/courses/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "courses_retrieve",
    }
  }

  /**
   * Show content files for a learning resource
   * @summary Learning Resource Content File List
   */
  coursesContentfilesList(
    learningResourceId: number,
    params?: CoursesContentfilesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedContentFileList
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/courses/${learningResourceId}/contentfiles/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "courses_contentfiles_list",
    }
  }

  /**
   * Show content files for a learning resource
   * @summary Learning Resource Content File Retrieve
   */
  coursesContentfilesRetrieve(
    learningResourceId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: ContentFile
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/courses/${learningResourceId}/contentfiles/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "courses_contentfiles_retrieve",
    }
  }

  /**
   * MIT academic departments
   * @summary List
   */
  departmentsList(
    params?: DepartmentsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceDepartmentList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/departments/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "departments_list",
    }
  }

  /**
   * MIT academic departments
   * @summary Retrieve
   */
  departmentsRetrieve(
    departmentId: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceDepartment
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/departments/${departmentId}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "departments_retrieve",
    }
  }

  /**
   * Get a paginated list of featured resources
   * @summary List
   */
  featuredList(
    params?: FeaturedListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/featured/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "featured_list",
    }
  }

  /**
   * Retrieve a single featured resource
   * @summary Retrieve
   */
  featuredRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/featured/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "featured_retrieve",
    }
  }

  /**
   * List HubSpot forms from the backend.
   */
  hubspotFormsList(
    params?: HubspotFormsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: HubspotCollectionResponseFormDefinitionBaseForwardPaging
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/hubspot/forms/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "hubspot_forms_list",
    }
  }

  /**
   * Get one HubSpot form by id from the backend.
   */
  hubspotFormsDetailRetrieve(
    formId: string,
    params?: HubspotFormsDetailRetrieveParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: HubspotFormDefinition
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/hubspot/forms/${formId}/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "hubspot_forms_detail_retrieve",
    }
  }

  /**
   * Submit a form to HubSpot.
   */
  hubspotFormsSubmit(
    formId: string,
    hubspotFormSubmitRequestRequest: HubspotFormSubmitRequestRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: HubspotFormSubmitResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/hubspot/forms/${formId}/submit/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(hubspotFormSubmitRequestRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "hubspot_forms_submit",
    }
  }

  /**
   * Get a paginated list of learning resource display info
   * @summary List
   */
  learningResourceDisplayInfoList(
    params?: LearningResourceDisplayInfoListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceDisplayInfoResponseList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resource_display_info/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resource_display_info_list",
    }
  }

  /**
   * Retrieve display info for a learning resource.
   * @summary Retrieve
   */
  learningResourceDisplayInfoRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceDisplayInfoResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resource_display_info/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resource_display_info_retrieve",
    }
  }

  /**
   * Get a paginated list of learning resources.
   * @summary List
   */
  learningResourcesList(
    params?: LearningResourcesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_list",
    }
  }

  /**
   * Retrieve a single learning resource.
   * @summary Retrieve
   */
  learningResourcesRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResource
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_retrieve",
    }
  }

  /**
 * Fetch similar learning resources

Args:
id (integer): The id of the learning resource

Returns:
QuerySet of similar LearningResource for the resource matching the id parameter
 * @summary Get similar resources
 */
  learningResourcesSimilarList(
    id: number,
    params?: LearningResourcesSimilarListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResource[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources/${id}/similar/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_similar_list",
    }
  }

  /**
 * Fetch similar learning resources

Args:
id (integer): The id of the learning resource

Returns:
QuerySet of similar LearningResource for the resource matching the id parameter
 * @summary Get similar resources using vector embeddings
 */
  learningResourcesVectorSimilarList(
    id: number,
    params?: LearningResourcesVectorSimilarListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResource[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources/${id}/vector_similar/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_vector_similar_list",
    }
  }

  /**
   * Show content files for a learning resource
   * @summary Learning Resource Content File List
   */
  learningResourcesContentfilesList(
    learningResourceId: number,
    params?: LearningResourcesContentfilesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedContentFileList
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learning_resources/${learningResourceId}/contentfiles/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_contentfiles_list",
    }
  }

  /**
   * Show content files for a learning resource
   * @summary Learning Resource Content File Retrieve
   */
  learningResourcesContentfilesRetrieve(
    learningResourceId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: ContentFile
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learning_resources/${learningResourceId}/contentfiles/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_contentfiles_retrieve",
    }
  }

  /**
   * Get a list of related learning resources for a learning resource.
   * @summary Nested Learning Resource List
   */
  learningResourcesItemsList(
    learningResourceId: number,
    params?: LearningResourcesItemsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceRelationshipList
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learning_resources/${learningResourceId}/items/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_items_list",
    }
  }

  /**
   * Get a singe related learning resource for a learning resource.
   * @summary Nested Learning Resource Retrieve
   */
  learningResourcesItemsRetrieve(
    learningResourceId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learning_resources/${learningResourceId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_items_retrieve",
    }
  }

  /**
   * Set Learning Path Relationships on a given Learning Resource.
   * @summary Set Learning Path Relationships
   */
  learningResourcesLearningPathsPartialUpdate(
    id: number,
    patchedLearningResourceRelationshipRequest: PatchedLearningResourceRelationshipRequest,
    params?: LearningResourcesLearningPathsPartialUpdateParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceRelationship[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources/${id}/learning_paths/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedLearningResourceRelationshipRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_learning_paths_partial_update",
    }
  }

  /**
   * Set User List Relationships on a given Learning Resource.
   * @summary Set User List Relationships
   */
  learningResourcesUserlistsPartialUpdate(
    id: number,
    patchedUserListRelationshipRequest: PatchedUserListRelationshipRequest,
    params?: LearningResourcesUserlistsPartialUpdateParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserListRelationship[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources/${id}/userlists/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedUserListRelationshipRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_userlists_partial_update",
    }
  }

  /**
   * Get a paginated list of learning resources with summary fields
   * @summary Get learning resources summary
   */
  learningResourcesSummaryList(
    params?: LearningResourcesSummaryListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceSummaryList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources/summary/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_summary_list",
    }
  }

  /**
   * Search for learning resources
   * @summary Search
   */
  learningResourcesSearchRetrieve(
    params?: LearningResourcesSearchRetrieveParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourcesSearchResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources_search/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_search_retrieve",
    }
  }

  /**
   * View for listing percolate query subscriptions for a user
   * @summary List subscribed queries
   */
  learningResourcesUserSubscriptionList(
    params?: LearningResourcesUserSubscriptionListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PercolateQuery[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learning_resources_user_subscription/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_user_subscription_list",
    }
  }

  /**
 * Unsubscribe a user from a query

Args:
pk (integer): The id of the query

Returns:
PercolateQuerySerializer: The percolate query
 * @summary Unsubscribe user from query
 */
  learningResourcesUserSubscriptionUnsubscribeDestroy(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learning_resources_user_subscription/${id}/unsubscribe/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_user_subscription_unsubscribe_destroy",
    }
  }

  /**
   * View for listing percolate query subscriptions for a user
   * @summary Check if a user is subscribed to a specific query
   */
  learningResourcesUserSubscriptionCheckList(
    params?: LearningResourcesUserSubscriptionCheckListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PercolateQuery[]
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learning_resources_user_subscription/check/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_user_subscription_check_list",
    }
  }

  /**
   * Subscribe a user to query
   * @summary Subscribe user to query
   */
  learningResourcesUserSubscriptionSubscribeCreate(
    percolateQuerySubscriptionRequestRequest: PercolateQuerySubscriptionRequestRequest,
    params?: LearningResourcesUserSubscriptionSubscribeCreateParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PercolateQuery
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learning_resources_user_subscription/subscribe/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(percolateQuerySubscriptionRequestRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_user_subscription_subscribe_create",
    }
  }

  /**
   * Get a paginated list of learning paths
   * @summary List
   */
  learningpathsList(
    params?: LearningpathsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningPathResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learningpaths/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_list",
    }
  }

  /**
   * Create a learning path
   * @summary Create
   */
  learningpathsCreate(
    learningPathResourceRequest: LearningPathResourceRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningPathResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/learningpaths/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(learningPathResourceRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_create",
    }
  }

  /**
   * Retrive a single learning path
   * @summary Retrieve
   */
  learningpathsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningPathResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/learningpaths/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_retrieve",
    }
  }

  /**
   * Update individual fields of a learning path
   * @summary Update
   */
  learningpathsPartialUpdate(
    id: number,
    patchedLearningPathResourceRequest: PatchedLearningPathResourceRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningPathResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/learningpaths/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedLearningPathResourceRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_partial_update",
    }
  }

  /**
   * Remove a learning path
   * @summary Destroy
   */
  learningpathsDestroy(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/learningpaths/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_destroy",
    }
  }

  /**
   * Viewset for LearningPath related resources
   */
  learningpathsItemsList(
    learningResourceId: number,
    params?: LearningpathsItemsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningPathRelationshipList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learningpaths/${learningResourceId}/items/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_items_list",
    }
  }

  /**
   * Viewset for LearningPath related resources
   * @summary Learning Path Resource Relationship Add
   */
  learningpathsItemsCreate(
    learningResourceId: number,
    learningPathRelationshipRequest: LearningPathRelationshipRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningPathRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learningpaths/${learningResourceId}/items/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(learningPathRelationshipRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_items_create",
    }
  }

  /**
   * Get a singe related learning resource for a learning resource.
   * @summary Nested Learning Resource Retrieve
   */
  learningpathsItemsRetrieve(
    learningResourceId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningPathRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learningpaths/${learningResourceId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_items_retrieve",
    }
  }

  /**
   * Viewset for LearningPath related resources
   * @summary Learning Path Resource Relationship Update
   */
  learningpathsItemsPartialUpdate(
    learningResourceId: number,
    id: number,
    patchedLearningPathRelationshipRequest: PatchedLearningPathRelationshipRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningPathRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learningpaths/${learningResourceId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedLearningPathRelationshipRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_items_partial_update",
    }
  }

  /**
   * Viewset for LearningPath related resources
   * @summary Learning Path Resource Relationship Remove
   */
  learningpathsItemsDestroy(
    learningResourceId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/learningpaths/${learningResourceId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_items_destroy",
    }
  }

  /**
   * Get a list of all learning path items
   * @summary List
   */
  learningpathsMembershipList(requestParameters?: Params): {
    response: Response
    data: MicroLearningPathRelationship[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/learningpaths/membership/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learningpaths_membership_list",
    }
  }

  /**
   * MIT organizations that offer learning resources
   * @summary List
   */
  offerorsList(
    params?: OfferorsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceOfferorDetailList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/offerors/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "offerors_list",
    }
  }

  /**
   * MIT organizations that offer learning resources
   * @summary Retrieve
   */
  offerorsRetrieve(
    code: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceOfferorDetail
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/offerors/${code}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "offerors_retrieve",
    }
  }

  /**
   * Platforms on which learning resources are hosted
   * @summary List
   */
  platformsList(
    params?: PlatformsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourcePlatformList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/platforms/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "platforms_list",
    }
  }

  /**
   * Platforms on which learning resources are hosted
   * @summary Retrieve
   */
  platformsRetrieve(
    code: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourcePlatform
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/platforms/${code}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "platforms_retrieve",
    }
  }

  /**
   * Get a paginated list of podcast episodes
   * @summary List
   */
  podcastEpisodesList(
    params?: PodcastEpisodesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedPodcastEpisodeResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/podcast_episodes/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "podcast_episodes_list",
    }
  }

  /**
   * Retrieve a single podcast episode
   * @summary Retrieve
   */
  podcastEpisodesRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: PodcastEpisodeResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/podcast_episodes/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "podcast_episodes_retrieve",
    }
  }

  /**
   * Get a paginated list of podcasts
   * @summary List
   */
  podcastsList(
    params?: PodcastsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedPodcastResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/podcasts/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "podcasts_list",
    }
  }

  /**
   * Retrieve a single podcast
   * @summary Retrieve
   */
  podcastsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: PodcastResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/podcasts/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "podcasts_retrieve",
    }
  }

  /**
   * Get a list of related learning resources for a learning resource.
   * @summary Nested Learning Resource List
   */
  podcastsItemsList(
    learningResourceId: number,
    params?: PodcastsItemsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceRelationshipList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/podcasts/${learningResourceId}/items/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "podcasts_items_list",
    }
  }

  /**
   * Get a singe related learning resource for a learning resource.
   * @summary Nested Learning Resource Retrieve
   */
  podcastsItemsRetrieve(
    learningResourceId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/podcasts/${learningResourceId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "podcasts_items_retrieve",
    }
  }

  /**
   * Detail only View for program letters
   */
  programLettersRetrieve(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: ProgramLetter
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/program_letters/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "program_letters_retrieve",
    }
  }

  /**
   * Get a paginated list of programs
   * @summary List
   */
  programsList(
    params?: ProgramsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedProgramResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/programs/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "programs_list",
    }
  }

  /**
   * Retrieve a single program
   * @summary Retrieve
   */
  programsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: ProgramResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/programs/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "programs_retrieve",
    }
  }

  /**
   * MIT schools
   * @summary List
   */
  schoolsList(
    params?: SchoolsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceSchoolList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/schools/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "schools_list",
    }
  }

  /**
   * MIT schools
   * @summary Retrieve
   */
  schoolsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceSchool
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/schools/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "schools_retrieve",
    }
  }

  /**
   * Topics covered by learning resources
   * @summary List
   */
  topicsList(
    params?: TopicsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceTopicList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/topics/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "topics_list",
    }
  }

  /**
   * Topics covered by learning resources
   * @summary Retrieve
   */
  topicsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceTopic
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/topics/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "topics_retrieve",
    }
  }

  /**
   * Upload an image (multipart/form-data) and return the storage URL.
   */
  mediaUpload(
    articleImageUploadRequest: ArticleImageUploadRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: MediaUpload201
    operationId: string
  } {
    const formData = new FormData()
    formData.append("image_file", articleImageUploadRequest.image_file)

    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/upload-media/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("POST", k6url.toString(), formData.body(), {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        "Content-Type": `multipart/form-data; boundary=${formData.boundary}`,
      },
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "media_upload",
    }
  }

  /**
   * Viewset for UserLists
   * @summary List
   */
  userlistsList(
    params?: UserlistsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedUserListList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/userlists/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_list",
    }
  }

  /**
   * Viewset for UserLists
   * @summary Create
   */
  userlistsCreate(
    userListRequest: UserListRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserList
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/userlists/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(userListRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_create",
    }
  }

  /**
   * Viewset for UserLists
   * @summary Retrieve
   */
  userlistsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserList
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/userlists/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_retrieve",
    }
  }

  /**
   * Viewset for UserLists
   * @summary Update
   */
  userlistsPartialUpdate(
    id: number,
    patchedUserListRequest: PatchedUserListRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserList
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/userlists/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedUserListRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_partial_update",
    }
  }

  /**
   * Viewset for UserLists
   * @summary Destroy
   */
  userlistsDestroy(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/userlists/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_destroy",
    }
  }

  /**
   * Viewset for UserListRelationships
   * @summary User List Resources List
   */
  userlistsItemsList(
    userlistId: number,
    params?: UserlistsItemsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedUserListRelationshipList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/userlists/${userlistId}/items/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_items_list",
    }
  }

  /**
   * Viewset for UserListRelationships
   * @summary User List Resource Relationship Add
   */
  userlistsItemsCreate(
    userlistId: number,
    userListRelationshipRequest: UserListRelationshipRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserListRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/userlists/${userlistId}/items/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(userListRelationshipRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_items_create",
    }
  }

  /**
   * Viewset for UserListRelationships
   * @summary User List Resources Retrieve
   */
  userlistsItemsRetrieve(
    userlistId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserListRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/userlists/${userlistId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_items_retrieve",
    }
  }

  /**
   * Viewset for UserListRelationships
   * @summary User List Resource Relationship Update
   */
  userlistsItemsPartialUpdate(
    userlistId: number,
    id: number,
    patchedUserListRelationshipRequest: PatchedUserListRelationshipRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserListRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/userlists/${userlistId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedUserListRelationshipRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_items_partial_update",
    }
  }

  /**
   * Viewset for UserListRelationships
   * @summary User List Resource Relationship Remove
   */
  userlistsItemsDestroy(
    userlistId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/userlists/${userlistId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_items_destroy",
    }
  }

  /**
   * Get a list of all userlist items for a user
   * @summary List
   */
  userlistsMembershipList(requestParameters?: Params): {
    response: Response
    data: MicroUserListRelationship[]
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/userlists/membership/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "userlists_membership_list",
    }
  }

  /**
   * Get a paginated list of video playlists
   * @summary List
   */
  videoPlaylistsList(
    params?: VideoPlaylistsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedVideoPlaylistResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/video_playlists/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "video_playlists_list",
    }
  }

  /**
   * Retrieve a single video playlist
   * @summary Retrieve
   */
  videoPlaylistsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: VideoPlaylistResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/video_playlists/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "video_playlists_retrieve",
    }
  }

  /**
   * Get a list of related learning resources for a learning resource.
   * @summary Nested Learning Resource List
   */
  videoPlaylistsItemsList(
    learningResourceId: number,
    params?: VideoPlaylistsItemsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedLearningResourceRelationshipList
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/video_playlists/${learningResourceId}/items/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "video_playlists_items_list",
    }
  }

  /**
   * Get a singe related learning resource for a learning resource.
   * @summary Nested Learning Resource Retrieve
   */
  videoPlaylistsItemsRetrieve(
    learningResourceId: number,
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourceRelationship
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v1/video_playlists/${learningResourceId}/items/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "video_playlists_items_retrieve",
    }
  }

  /**
   * Get a paginated list of videos
   * @summary List
   */
  videosList(
    params?: VideosListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedVideoResourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/videos/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "videos_list",
    }
  }

  /**
   * Retrieve a single video
   * @summary Retrieve
   */
  videosRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: VideoResource
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v1/videos/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "videos_retrieve",
    }
  }

  /**
   * Webhook handler for ContentFile updates
   */
  webhooksContentFilesCreate(
    contentFileWebHookRequestRequest: ContentFileWebHookRequestRequest,
    params: WebhooksContentFilesCreateParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: WebhookResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/webhooks/content_files/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(contentFileWebHookRequestRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "webhooks_content_files_create",
    }
  }

  /**
   * Webhook handler for ContentFile DELETE requests
   */
  webhooksContentFilesDeleteCreate(
    contentFileWebHookRequestRequest: ContentFileWebHookRequestRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: ContentFileWebHookRequest
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/webhooks/content_files/delete/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(contentFileWebHookRequestRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "webhooks_content_files_delete_create",
    }
  }

  /**
   * Webhook handler for VideoShort updates
   */
  webhooksVideoShortsCreate(
    videoShortWebhookRequestRequest: VideoShortWebhookRequestRequest,
    params: WebhooksVideoShortsCreateParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: WebhookResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v1/webhooks/video_shorts/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(videoShortWebhookRequestRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "webhooks_video_shorts_create",
    }
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    }
  }
}
