# Generated by Django 3.1 on 2021-01-28 16:27
from django.conf import settings
from django.contrib.auth.models import Group
from django.db import migrations

from ai_chat import constants


def add_ai_prompt_editor_group(apps, schema_editor):
    """
    Create the staff list editors group
    """
    Group.objects.get_or_create(name=constants.GROUP_STAFF_AI_SYTEM_PROMPT_EDITORS)


def remove_ai_prompt_editor_group(apps, schema_editor):
    """
    Delete the staff list editors group
    """
    Group.objects.filter(name=constants.GROUP_STAFF_AI_SYTEM_PROMPT_EDITORS).delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_ai_prompt_editor_group, remove_ai_prompt_editor_group),
    ]
