/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * MIT Learn API
 * MIT public API
 * Service version: 0.0.1 (v0)
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js"

import http from "k6/http"
import type { Params, Response } from "k6/http"

import type {
  Attestation,
  CKEditorSettings,
  Channel,
  ChannelCounts,
  ChannelCreateRequest,
  ChannelModerator,
  ChannelModeratorRequest,
  ChannelsListParams,
  ContentFileVectorSearchResponse,
  FeedItem,
  FeedSource,
  LearningResourcesVectorSearchResponse,
  NewsEventsListParams,
  NewsEventsSourcesListParams,
  PaginatedAttestationList,
  PaginatedChannelList,
  PaginatedFeedItemList,
  PaginatedFeedSourceList,
  PaginatedVideoShortList,
  PatchedChannelWriteRequest,
  PatchedProfileRequest,
  PatchedUserRequest,
  PatchedWidgetListRequest,
  ProblemListResponse,
  Profile,
  ProfileRequest,
  ProgramCertificate,
  ProgramCertificatesListParams,
  RetrieveProblemResponse,
  TestimonialsListParams,
  User,
  UserRequest,
  UserWebsite,
  UserWebsiteRequest,
  VectorContentFilesSearchRetrieveParams,
  VectorLearningResourcesSearchRetrieveParams,
  VideoShort,
  VideoShortsListParams,
  WidgetList,
  WidgetListRequest,
} from "./api.schemas"

/**
 * This is the base client to use for interacting with the API.
 */
export class MITLearnAPIClient {
  private cleanBaseUrl: string
  private commonRequestParameters: Params

  constructor(clientOptions: {
    baseUrl: string
    commonRequestParameters?: Params
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "")

    this.commonRequestParameters = clientOptions.commonRequestParameters || {}
  }

  /**
 * CRUD Operations related to Channels. Channels may represent groups
or organizations at MIT and are a high-level categorization of content.
 * @summary List
 */
  channelsList(
    params?: ChannelsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedChannelList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/channels/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_list",
    }
  }

  /**
 * CRUD Operations related to Channels. Channels may represent groups
or organizations at MIT and are a high-level categorization of content.
 * @summary Create
 */
  channelsCreate(
    channelCreateRequest: ChannelCreateRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: Channel
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/channels/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(channelCreateRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_create",
    }
  }

  /**
 * CRUD Operations related to Channels. Channels may represent groups
or organizations at MIT and are a high-level categorization of content.
 * @summary Retrieve
 */
  channelsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: Channel
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/channels/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_retrieve",
    }
  }

  /**
 * CRUD Operations related to Channels. Channels may represent groups
or organizations at MIT and are a high-level categorization of content.
 * @summary Update
 */
  channelsPartialUpdate(
    id: number,
    patchedChannelWriteRequest: PatchedChannelWriteRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: Channel
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/channels/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedChannelWriteRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_partial_update",
    }
  }

  /**
 * CRUD Operations related to Channels. Channels may represent groups
or organizations at MIT and are a high-level categorization of content.
 * @summary Destroy
 */
  channelsDestroy(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/channels/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_destroy",
    }
  }

  /**
   * View for listing and adding moderators
   * @summary Channel Moderators List
   */
  channelsModeratorsList(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: ChannelModerator[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/channels/${id}/moderators/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_moderators_list",
    }
  }

  /**
   * View for listing and adding moderators
   * @summary Channel Moderators Create
   */
  channelsModeratorsCreate(
    id: string,
    channelModeratorRequest: ChannelModeratorRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: ChannelModerator
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/channels/${id}/moderators/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(channelModeratorRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_moderators_create",
    }
  }

  /**
   * Remove the user from the moderator groups for this website
   * @summary Channel Moderators Destroy
   */
  channelsModeratorsDestroy(
    id: string,
    moderatorName: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/channels/${id}/moderators/${moderatorName}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_moderators_destroy",
    }
  }

  /**
   * View for retrieving an individual channel by type and name
   * @summary Channel Detail Lookup by channel type and name
   */
  channelsCountsList(
    channelType: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: ChannelCounts[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/channels/counts/${channelType}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_counts_list",
    }
  }

  /**
   * View for retrieving an individual channel by type and name
   * @summary Channel Detail Lookup by channel type and name
   */
  channelsTypeRetrieve(
    channelType: string,
    name: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: Channel
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/channels/type/${channelType}/${name}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "channels_type_retrieve",
    }
  }

  /**
   * Get the settings response
   */
  ckeditorRetrieve(requestParameters?: Params): {
    response: Response
    data: CKEditorSettings
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/ckeditor`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "ckeditor_retrieve",
    }
  }

  /**
   * Learning resource search default admin param values
   */
  learningResourcesSearchAdminParamsRetrieve(requestParameters?: Params): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/learning_resources_search_admin_params/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "learning_resources_search_admin_params_retrieve",
    }
  }

  /**
   * Get a paginated list of feed items.
   */
  newsEventsList(
    params?: NewsEventsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedFeedItemList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/news_events/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "news_events_list",
    }
  }

  /**
   * Retrieve a single feed item.
   */
  newsEventsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: FeedItem
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/news_events/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "news_events_retrieve",
    }
  }

  /**
   * Get a paginated list of news/event feed sources.
   */
  newsEventsSourcesList(
    params?: NewsEventsSourcesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedFeedSourceList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/news_events_sources/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "news_events_sources_list",
    }
  }

  /**
   * Retrieve a single news/event feed source.
   */
  newsEventsSourcesRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: FeedSource
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/news_events_sources/${id}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "news_events_sources_retrieve",
    }
  }

  /**
   * View for profile
   */
  profilesRetrieve(
    userUsername: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: Profile
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/profiles/${userUsername}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "profiles_retrieve",
    }
  }

  /**
   * View for profile
   */
  profilesUpdate(
    userUsername: string,
    profileRequest: ProfileRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: Profile
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/profiles/${userUsername}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PUT",
      k6url.toString(),
      JSON.stringify(profileRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "profiles_update",
    }
  }

  /**
   * View for profile
   */
  profilesPartialUpdate(
    userUsername: string,
    patchedProfileRequest: PatchedProfileRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: Profile
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/profiles/${userUsername}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedProfileRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "profiles_partial_update",
    }
  }

  /**
 * View for listing program certificates for a user
(includes program letter links)
 */
  programCertificatesList(
    params?: ProgramCertificatesListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: ProgramCertificate[]
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/program_certificates/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "program_certificates_list",
    }
  }

  /**
   * List all testimonials.
   * @summary List
   */
  testimonialsList(
    params?: TestimonialsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedAttestationList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/testimonials/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "testimonials_list",
    }
  }

  /**
   * Retrieve a testimonial.
   * @summary Retrieve
   */
  testimonialsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: Attestation
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/testimonials/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "testimonials_retrieve",
    }
  }

  /**
   * Retrieve a list of problem names for a course run
   * @summary Retrieve problem list
   */
  listProblems(
    runReadableId: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: ProblemListResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/tutor/problems/${runReadableId}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "list_problems",
    }
  }

  /**
   * Retrieve a specific problem and its solution for a course run
   * @summary Retrieve Problem
   */
  retrieveProblem(
    runReadableId: string,
    problemTitle: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: RetrieveProblemResponse
    operationId: string
  } {
    const k6url = new URL(
      `${
        this.cleanBaseUrl
      }/api/v0/tutor/problems/${runReadableId}/${problemTitle}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "retrieve_problem",
    }
  }

  /**
   * View for users
   */
  usersList(requestParameters?: Params): {
    response: Response
    data: User[]
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/users/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "users_list",
    }
  }

  /**
   * View for users
   */
  usersCreate(
    userRequest: UserRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: User
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/users/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(userRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "users_create",
    }
  }

  /**
   * View for users
   */
  usersRetrieve(
    username: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: User
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/users/${username}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "users_retrieve",
    }
  }

  /**
   * View for users
   */
  usersUpdate(
    username: string,
    userRequest: UserRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: User
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/users/${username}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PUT",
      k6url.toString(),
      JSON.stringify(userRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "users_update",
    }
  }

  /**
   * View for users
   */
  usersPartialUpdate(
    username: string,
    patchedUserRequest: PatchedUserRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: User
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/users/${username}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedUserRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "users_partial_update",
    }
  }

  /**
   * View for users
   */
  usersDestroy(
    username: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/users/${username}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "users_destroy",
    }
  }

  /**
   * User retrieve and update viewsets for the current user
   */
  usersMeRetrieve(requestParameters?: Params): {
    response: Response
    data: User
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/users/me/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "users_me_retrieve",
    }
  }

  /**
   * Vector Search for content
   * @summary Content File Vector Search
   */
  vectorContentFilesSearchRetrieve(
    params?: VectorContentFilesSearchRetrieveParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: ContentFileVectorSearchResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/vector_content_files_search/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "vector_content_files_search_retrieve",
    }
  }

  /**
   * Vector Search for learning resources
   * @summary Vector Search
   */
  vectorLearningResourcesSearchRetrieve(
    params?: VectorLearningResourcesSearchRetrieveParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: LearningResourcesVectorSearchResponse
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/vector_learning_resources_search/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "vector_learning_resources_search_retrieve",
    }
  }

  /**
   * Get a paginated list of video shorts.
   */
  videoShortsList(
    params?: VideoShortsListParams,
    requestParameters?: Params,
  ): {
    response: Response
    data: PaginatedVideoShortList
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/video_shorts/` +
        `?${new URLSearchParams(params).toString()}`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "video_shorts_list",
    }
  }

  /**
   * Retrieve a single video short.
   */
  videoShortsRetrieve(
    videoId: string,
    requestParameters?: Params,
  ): {
    response: Response
    data: VideoShort
    operationId: string
  } {
    const k6url = new URL(
      `${this.cleanBaseUrl}/api/v0/video_shorts/${videoId}/`,
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "video_shorts_retrieve",
    }
  }

  /**
   * View for user websites
   */
  websitesCreate(
    userWebsiteRequest: UserWebsiteRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: UserWebsite
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/websites/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(userWebsiteRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "websites_create",
    }
  }

  /**
   * View for user websites
   */
  websitesDestroy(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: void
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/websites/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "DELETE",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "websites_destroy",
    }
  }

  /**
   * API for managing widget lists
   */
  widgetListsRetrieve(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response
    data: WidgetList
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/widget_lists/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "widget_lists_retrieve",
    }
  }

  /**
   * API for managing widget lists
   */
  widgetListsUpdate(
    id: number,
    widgetListRequest: WidgetListRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: WidgetList
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/widget_lists/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PUT",
      k6url.toString(),
      JSON.stringify(widgetListRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "widget_lists_update",
    }
  }

  /**
   * API for managing widget lists
   */
  widgetListsPartialUpdate(
    id: number,
    patchedWidgetListRequest: PatchedWidgetListRequest,
    requestParameters?: Params,
  ): {
    response: Response
    data: WidgetList
    operationId: string
  } {
    const k6url = new URL(`${this.cleanBaseUrl}/api/v0/widget_lists/${id}/`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    )
    const response = http.request(
      "PATCH",
      k6url.toString(),
      JSON.stringify(patchedWidgetListRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
      operationId: "widget_lists_partial_update",
    }
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    }
  }
}
