# Generated by Django 5.2.16 on 2026-08-13 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0016_alter_channel_featured_list"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="channelgrouprole",
            new_name="channelgrouprole_ch_role_idx",
            old_fields=("channel", "role"),
        ),
    ]
