# Generated by Django 5.2.16 on 2026-08-13 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0016_alter_channel_featured_list"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="channelgrouprole",
            new_name="channels_ch_channel_ae5fc6_idx",
            old_fields=("channel", "role"),
        ),
    ]
