# Generated by Django 4.2.16 on 2024-10-21 17:33

from django.db import migrations, models

from learning_resources.constants import CURRENCY_USD


def migrate_price_values(apps, schema_editor):
    """
    Convert prices in prices field to LearningResourcePrices.
    Assumption is that all current prices are in USD.
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    LearningResourcePrice = apps.get_model(
        "learning_resources", "LearningResourcePrice"
    )

    for resource in LearningResource.objects.exclude(prices=[]):
        for price in resource.prices:
            resource_price, _ = LearningResourcePrice.objects.get_or_create(
                amount=price, currency=CURRENCY_USD
            )
            resource.resource_prices.add(resource_price)
        for run in resource.runs.exclude(prices=[]).exclude(prices__isnull=True):
            for price in run.prices:
                resource_price, _ = LearningResourcePrice.objects.get_or_create(
                    amount=price, currency=CURRENCY_USD
                )
                run.resource_prices.add(resource_price)


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0070_learningresource_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningResourcePrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
            ],
            options={
                "abstract": False,
                "ordering": ["amount"],
            },
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="resource_prices",
            field=models.ManyToManyField(
                blank=True,
                related_name="runs",
                to="learning_resources.learningresourceprice",
            ),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="resource_prices",
            field=models.ManyToManyField(
                blank=True,
                related_name="resources",
                to="learning_resources.learningresourceprice",
            ),
        ),
        migrations.RunPython(
            migrate_price_values, reverse_code=migrations.RunPython.noop
        ),
    ]
