# Generated by Django 4.2.16 on 2024-10-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0070_learningresource_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="embedding_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
