# Generated by Django 4.2.16 on 2024-10-31 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0071_learningresourceprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningresourceinstructor",
            options={},
        ),
        migrations.CreateModel(
            name="RunInstructorRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_relationships",
                        to="learning_resources.learningresourceinstructor",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_relationships",
                        to="learning_resources.learningresourcerun",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
