# Generated by Django 4.2.16 on 2024-10-21 20:16

from django.db import migrations


def unmigrate_price_values(apps, schema_editor):
    """
    Convert prices in resource_prices field to a list decimals.
    """
    LearningResource = apps.get_model("learning_resources", "LearningResource")

    for resource in LearningResource.objects.exclude(resource_prices__isnull=True):
        resource.prices = [price.amount for price in resource.resource_prices.all()]
        resource.save()
        for run in resource.runs.exclude(resource_prices__isnull=True):
            run.prices = [price.amount for price in run.resource_prices.all()]
            run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0071_learningresourceprice"),
    ]
    operations = [
        migrations.RunPython(migrations.RunPython.noop, unmigrate_price_values),
        migrations.RemoveField(
            model_name="learningresourcerun",
            name="prices",
        ),
        migrations.RemoveField(
            model_name="learningresource",
            name="prices",
        ),
    ]
