# Generated by Django 4.2.16 on 2024-10-31 19:41

from django.db import migrations


def create_through_relations(apps, schema_editor):
    """Create relations between LearningResourceRun and LearningResourceInstructor"""
    LearningResourceRun = apps.get_model("learning_resources", "LearningResourceRun")
    RunInstructorRelationship = apps.get_model(
        "learning_resources", "RunInstructorRelationship"
    )
    for idx, run in enumerate(LearningResourceRun.objects.all()):
        for instructor in run.instructors.iterator():
            RunInstructorRelationship.objects.update_or_create(
                run=run, instructor=instructor, defaults={"position": idx}
            )


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0072_alter_learningresourceinstructor_relationship"),
    ]

    operations = [
        migrations.RunPython(
            create_through_relations, reverse_code=migrations.RunPython.noop
        ),
    ]
