# Generated by Django 4.2.16 on 2024-10-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0074_remove_learningresourcerun_instructors"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourcerun",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="runs",
                through="learning_resources.RunInstructorRelationship",
                to="learning_resources.learningresourceinstructor",
            ),
        ),
        migrations.AlterModelOptions(
            name="learningresourceinstructor",
            options={
                "ordering": ["run_relationships__position", "last_name", "first_name"]
            },
        ),
    ]
