# Generated by Django 4.2.16 on 2024-11-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0075_learningresourcerun_instructors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="certification_type",
            field=models.CharField(
                choices=[
                    ("micromasters", "MicroMasters Credential"),
                    ("professional", "Professional Certificate"),
                    ("completion", "Certificate of Completion"),
                    ("none", "No Certificate"),
                ],
                default="none",
                max_length=24,
            ),
        ),
    ]
