# Generated by Django 4.2.16 on 2024-11-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0076_alter_learningresource_certification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="file_extension",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="contentfile",
            name="source_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
