# Generated by Django 4.2.16 on 2024-12-06 22:02

from django.db import migrations


def ensure_trailing_slashes(apps, schema_editor):
    LearningResource = apps.get_model("learning_resources", "LearningResource")

    for resource in LearningResource.objects.filter(
        resource_type="course", offered_by_id="ocw"
    ):
        resource.url = f"{resource.url.rstrip('/')}/"
        resource.save()
        for run in resource.runs.all():
            run.url = f"{run.url.rstrip('/')}/"
            run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0078_alter_contentfile_content_type"),
    ]

    operations = [
        migrations.RunPython(ensure_trailing_slashes, migrations.RunPython.noop),
    ]
