# Generated by Django 4.2.17 on 2024-12-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0079_ocw_pages_trailing_slash"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="duration",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="max_weekly_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="max_weeks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="min_weekly_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="min_weeks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresource",
            name="time_commitment",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="duration",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="max_weekly_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="max_weeks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="min_weekly_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="min_weeks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="time_commitment",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
