# Generated by Django 4.2.17 on 2024-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0079_ocw_pages_trailing_slash"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastepisode",
            name="audio_url",
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
