# Generated by Django 4.2.17 on 2024-12-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0081_podcastepisode_audio_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcastepisode",
            name="audio_url",
            field=models.URLField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
