# Generated by Django 4.2.17 on 2025-01-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0082_alter_podcastepisode_audio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="edx_block_id",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
