# Generated by Django 4.2.19 on 2025-03-04 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0083_contentfile_edx_block_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contentfile",
            old_name="edx_block_id",
            new_name="edx_module_id",
        ),
    ]
