# Generated by Django 4.2.19 on 2025-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0084_rename_edx_block_id_contentfile_edx_module_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="flashcards",
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.AddField(
            model_name="contentfile",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
