# Generated by Django 4.2.19 on 2025-03-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0085_contentfile_learning_resource_alter_contentfile_run",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contentfile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("learning_resource__isnull", False),
                    ("run__isnull", False),
                    _connector="OR",
                ),
                name="run_or_resource_defined",
            ),
        ),
    ]
