# Generated by Django 4.2.19 on 2025-03-13 18:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0087_add_summary_flashcard_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSummarizerConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "llm_model",
                    models.CharField(max_length=128, verbose_name="LLM Model"),
                ),
                (
                    "allowed_content_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("page", "page"),
                                ("file", "file"),
                                ("video", "video"),
                                ("pdf", "pdf"),
                            ],
                            max_length=128,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "allowed_extensions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                (".csv", ".csv"),
                                (".doc", ".doc"),
                                (".docx", ".docx"),
                                (".htm", ".htm"),
                                (".html", ".html"),
                                (".json", ".json"),
                                (".m", ".m"),
                                (".mat", ".mat"),
                                (".md", ".md"),
                                (".pdf", ".pdf"),
                                (".ppt", ".ppt"),
                                (".pptx", ".pptx"),
                                (".ps", ".ps"),
                                (".py", ".py"),
                                (".r", ".r"),
                                (".rtf", ".rtf"),
                                (".sjson", ".sjson"),
                                (".srt", ".srt"),
                                (".txt", ".txt"),
                                (".vtt", ".vtt"),
                                (".xls", ".xls"),
                                (".xlsx", ".xlsx"),
                                (".xml", ".xml"),
                                (".doc", ".doc"),
                                (".docx", ".docx"),
                                (".htm", ".htm"),
                                (".html", ".html"),
                                (".json", ".json"),
                                (".md", ".md"),
                                (".pdf", ".pdf"),
                                (".ppt", ".ppt"),
                                (".pptx", ".pptx"),
                                (".rtf", ".rtf"),
                                (".sjson", ".sjson"),
                                (".srt", ".srt"),
                                (".txt", ".txt"),
                                (".vtt", ".vtt"),
                                (".xml", ".xml"),
                            ],
                            max_length=128,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "platform",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summarizer_config",
                        to="learning_resources.learningresourceplatform",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
