# Generated by Django 4.2.20 on 2025-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0088_add_content_summarizer_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="archive_checksum",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
