# Generated by Django 4.2.20 on 2025-04-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0088_add_content_summarizer_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="test_mode",
            field=models.BooleanField(default=False),
        ),
    ]
