# Generated by Django 4.2.23 on 2025-07-18 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0091_content_file_content_view_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorProblemFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "problem_title",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("problem", "problem"), ("solution", "solution")],
                        max_length=128,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "archive_checksum",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "source_path",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "file_extension",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_files",
                        to="learning_resources.learningresourcerun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
