# Generated by Django 4.2.23 on 2025-08-14 15:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0093_tutorproblem_view_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsummarizerconfiguration",
            name="allowed_extensions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        (".csv", ".csv"),
                        (".doc", ".doc"),
                        (".docx", ".docx"),
                        (".htm", ".htm"),
                        (".html", ".html"),
                        (".json", ".json"),
                        (".m", ".m"),
                        (".mat", ".mat"),
                        (".md", ".md"),
                        (".pdf", ".pdf"),
                        (".ppt", ".ppt"),
                        (".pptx", ".pptx"),
                        (".ps", ".ps"),
                        (".py", ".py"),
                        (".r", ".r"),
                        (".rtf", ".rtf"),
                        (".sjson", ".sjson"),
                        (".srt", ".srt"),
                        (".txt", ".txt"),
                        (".vtt", ".vtt"),
                        (".xls", ".xls"),
                        (".xlsx", ".xlsx"),
                        (".xml", ".xml"),
                        (".doc", ".doc"),
                        (".docx", ".docx"),
                        (".htm", ".htm"),
                        (".html", ".html"),
                        (".json", ".json"),
                        (".md", ".md"),
                        (".pdf", ".pdf"),
                        (".tex", ".tex"),
                        (".ppt", ".ppt"),
                        (".pptx", ".pptx"),
                        (".rtf", ".rtf"),
                        (".sjson", ".sjson"),
                        (".srt", ".srt"),
                        (".txt", ".txt"),
                        (".vtt", ".vtt"),
                        (".xml", ".xml"),
                    ],
                    max_length=128,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
