# Generated by Django 4.2.23 on 2025-07-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0093_tutorproblem_view_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorproblemfile",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problem_files",
                to="learning_resources.learningresourcerun",
            ),
        ),
    ]
