# Generated by Django 4.2.23 on 2025-08-01 17:09

import django.contrib.postgres.fields
from django.db import migrations, models

import learning_resources.models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0093_tutorproblem_view_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="delivery",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("online", "Online"),
                        ("hybrid", "Hybrid"),
                        ("in_person", "In person"),
                        ("offline", "Offline"),
                        ("other", "Other"),
                    ],
                    db_index=True,
                    max_length=24,
                ),
                default=learning_resources.models.default_delivery,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="learningresourcerun",
            name="delivery",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("online", "Online"),
                        ("hybrid", "Hybrid"),
                        ("in_person", "In person"),
                        ("offline", "Offline"),
                        ("other", "Other"),
                    ],
                    db_index=True,
                    max_length=24,
                ),
                default=learning_resources.models.default_delivery,
                size=None,
            ),
        ),
    ]
