# Generated by Django 4.2.23 on 2025-08-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0094_alter_contentsummarizerconfiguration_allowed_extensions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsummarizerconfiguration",
            name="learning_resources",
            field=models.ManyToManyField(
                to="learning_resources.learningresource", blank=True
            ),
        ),
    ]
