# Generated by Django 4.2.23 on 2025-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0094_alter_contentsummarizerconfiguration_allowed_extensions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="require_summaries",
            field=models.BooleanField(default=False),
        ),
    ]
