# Generated by Django 4.2.23 on 2025-08-18 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "learning_resources",
            "0094_alter_contentsummarizerconfiguration_allowed_extensions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsummarizerconfiguration",
            name="course_readable_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, default="", max_length=512),
                blank=True,
                default=list,
                help_text="List of course readable_ids to limit summarization to.",
                null=True,
                size=None,
            ),
        ),
    ]
