# Generated by Django 4.2.24 on 2025-09-22 19:45

from django.db import migrations, models


def populate_file_name(apps, schema_editor):
    for tutor_problem_file in apps.get_model(
        "learning_resources", "TutorProblemFile"
    ).objects.all():
        if tutor_problem_file.file_name is None:
            tutor_problem_file.file_name = tutor_problem_file.source_path.split("/")[-1]
            tutor_problem_file.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0095_learningresource_require_summaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorproblemfile",
            name="file_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RunPython(populate_file_name, migrations.RunPython.noop),
    ]
