# Generated by Django 4.2.24 on 2025-10-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0096_tutorproblemfile_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorproblemfile",
            name="checksum",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
