# Generated by Django 4.2.24 on 2025-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0098_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("program", "Program"),
                    ("learning_path", "Learning Path"),
                    ("podcast", "Podcast"),
                    ("podcast_episode", "Podcast Episode"),
                    ("video", "Video"),
                    ("video_playlist", "Video Playlist"),
                    ("article", "Article"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
