# Generated by Django 4.2.25 on 2025-11-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0099_alter_learningresource_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourceofferor",
            name="display_facet",
            field=models.BooleanField(default=True),
        ),
    ]
