# Generated by Django 4.2.26 on 2026-01-22 00:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0100_learningresourceofferor_display_facet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("program", "Program"),
                    ("learning_path", "Learning Path"),
                    ("podcast", "Podcast"),
                    ("podcast_episode", "Podcast Episode"),
                    ("video", "Video"),
                    ("video_playlist", "Video Playlist"),
                    ("article", "Article"),
                    ("lecture_note", "Lecture Notes"),
                    ("readings", "Readings"),
                    ("practice", "Practice"),
                    ("open_textbook", "Open Textbooks"),
                    ("lecture_audio", "Lecture Audio"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="learningresourcerelationship",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("PROGRAM_COURSES", "Program Courses"),
                    ("LEARNING_PATH_ITEMS", "Learning Path Items"),
                    ("PODCAST_EPISODES", "Podcast Episodes"),
                    ("PLAYLIST_VIDEOS", "Playlist Videos"),
                    ("COURSE_LEARNING_MATERIALS", "Course Learning Materials"),
                ],
                default=None,
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="CourseLearningMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "content_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "content_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_material",
                        to="learning_resources.contentfile",
                    ),
                ),
                (
                    "learning_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_learning_material",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
