# Generated by Django 4.2.26 on 2026-01-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0100_learningresourceofferor_display_facet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresourcerelationship",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("PROGRAM_COURSES", "Program Courses"),
                    ("LEARNING_PATH_ITEMS", "Learning Path Items"),
                    ("PODCAST_EPISODES", "Podcast Episodes"),
                    ("PLAYLIST_VIDEOS", "Playlist Videos"),
                    ("COURSE_LEARNING_MATERIALS", "Course Learning Materials"),
                ],
                default=None,
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="CourseLearningMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("content_tag", models.TextField(blank=True, null=True)),
                (
                    "content_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Lecture Notes", "Lecture Notes"),
                            ("Readings", "Readings"),
                            ("Practice", "Practice"),
                            ("Open Textbooks", "Open Textbooks"),
                            ("Lecture Audio", "Lecture Audio"),
                            ("Videos", "Videos"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "content_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_material",
                        to="learning_resources.contentfile",
                    ),
                ),
                (
                    "learning_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_learning_material",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
