# Generated by Django 4.2.26 on 2025-11-25 14:00

from django.db import migrations

from learning_resources.constants import OfferedBy

MIT_CLIMATE_TOPIC_MAP = {
    "Climate Modeling": {
        "topic": "Climate Science",
        "subtopic": "Science & Math: Earth Science",
    },
    "Atmosphere": {
        "topic": "Climate Science",
        "subtopic": "Science & Math: Earth Science",
    },
    "Weather & Natural Disasters": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Hurricanes": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Drought": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Heatwaves": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Flooding": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Wildfires": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Sea Level Rise": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Oceans": {"topic": "Ecosystems", "subtopic": "Science & Math: Earth Science"},
    "Forests": {"topic": "Ecosystems", "subtopic": "Science & Math: Earth Science"},
    "Biodiversity": {"topic": "Ecosystems", "subtopic": "Science & Math: Biology"},
    "Arctic & Antarctic": {
        "topic": "Ecosystems",
        "subtopic": "Science & Math: Earth Science",
    },
    "Food, Water & Agriculture": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Science & Math: Earth Science",
    },
    "Humanities & Social Science": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Social Sciences",
    },
    "Climate Justice": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Social Sciences",
    },
    "Health & Medicine": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Health & Medicine: Public Health",
    },
    "Cities & Planning": {
        "topic": "Built Environment",
        "subtopic": "Social Sciences: Urban Studies",
    },
    "Buildings": {
        "topic": "Built Environment",
        "subtopic": "Art, Design & Architecture: Architecture",
    },
    "Industry & Manufacturing": {
        "topic": "Sustainable Business",
        "subtopic": "Engineering: Manufacturing",
    },
    "Energy": {"topic": "Energy", "subtopic": "Engineering"},
    "Renewable Energy": {"topic": "Energy", "subtopic": "Engineering"},
    "Fossil Fuels": {"topic": "Energy", "subtopic": "Engineering"},
    "Nuclear & Fusion Energy": {
        "topic": "Energy",
        "subtopic": "Engineering: Nuclear Engineering",
    },
    "Batteries, Storage & Transmission": {
        "topic": "Energy",
        "subtopic": "Engineering",
    },
    "Energy Efficiency": {"topic": "Energy", "subtopic": "Engineering"},
    "Electrification": {
        "topic": "Energy",
        "subtopic": "Engineering: Electrical Engineering",
    },
    "Transportation": {"topic": "Energy", "subtopic": "Engineering"},
    "Air Travel": {"topic": "Energy", "subtopic": "Engineering: Aerospace Engineering"},
    "Cars": {"topic": "Energy", "subtopic": "Engineering"},
    "Public Transportation": {
        "topic": "Energy",
        "subtopic": "Engineering: Civil Engineering",
    },
    "Freight": {"topic": "Energy", "subtopic": "Business & Management: Supply Chain"},
    "Waste": {
        "topic": "Climate and Energy Policy",
        "subtopic": "Engineering: Environmental Engineering",
    },
    "Government & Politics": {
        "topic": "Climate and Energy Policy",
        "subtopic": "Policy and Administration",
    },
    "Advocacy & Activism": {
        "topic": "Climate and Energy Policy",
        "subtopic": "Policy and Administration",
    },
    "International Agreements": {
        "topic": "Climate and Energy Policy",
        "subtopic": "Policy and Administration",
    },
    "National Security": {
        "topic": "Climate and Energy Policy",
        "subtopic": "Policy and Administration",
    },
    "Carbon Capture": {"topic": "Energy", "subtopic": "Engineering"},
    "Geoengineering": {"topic": "Adaptation and Resilience", "subtopic": "Engineering"},
    "Finance & Economics": {
        "topic": "Climate and Energy Policy",
        "subtopic": "Social Sciences: Economics",
    },
    "Carbon Pricing": {
        "topic": "Climate and Energy Policy",
        "subtopic": "Social Sciences: Economics",
    },
    "Education": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Education & Teaching",
    },
    "Adaptation": {"topic": "Adaptation and Resilience", "subtopic": "Social Sciences"},
    "Communication & Arts": {
        "topic": "Adaptation and Resilience",
        "subtopic": "Humanities",
    },
    "Carbon Removal": {
        "topic": "Climate Science",
        "subtopic": "Engineering: Environmental Engineering",
    },
    "Alternative Fuels": {"topic": "Energy", "subtopic": "Chemical Engineering"},
}


def remove_climate_topic_mapping(apps, schema_editor):
    LearningResourceTopicMapping = apps.get_model(
        "learning_resources", "LearningResourceTopicMapping"
    )
    LearningResourceTopicMapping.objects.filter(
        offered_by__code=OfferedBy.climate.name
    ).delete()


def add_climate_topic_mapping(apps, schema_editor):
    LearningResourceTopicMapping = apps.get_model(
        "learning_resources", "LearningResourceTopicMapping"
    )
    LearningResourceOfferor = apps.get_model(
        "learning_resources", "LearningResourceOfferor"
    )
    LearningResourceTopic = apps.get_model(
        "learning_resources", "LearningResourceTopic"
    )
    climate_offeror = LearningResourceOfferor.objects.get(code=OfferedBy.climate.name)
    for climate_topic_name, mapping in MIT_CLIMATE_TOPIC_MAP.items():
        topic_name = mapping["topic"]
        subtopic_name = mapping["subtopic"].split(":")[-1].strip()
        for topic in LearningResourceTopic.objects.filter(
            name__in=[topic_name, subtopic_name]
        ):
            LearningResourceTopicMapping.objects.get_or_create(
                offeror=climate_offeror, topic_name=climate_topic_name, topic=topic
            )


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0100_learningresourceofferor_display_facet"),
    ]

    operations = [
        migrations.RunPython(add_climate_topic_mapping, remove_climate_topic_mapping),
    ]
