# Generated by Django 4.2.26 on 2025-12-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0100_learningresourceofferor_display_facet"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="auto_checksum_content",
            field=models.BooleanField(default=True),
        ),
    ]
