# Generated by Django 4.2.26 on 2025-11-25 15:32

from django.db import migrations


def add_theater_subtopic(apps, schema_editor):
    LearningResourceTopic = apps.get_model(
        "learning_resources", "LearningResourceTopic"
    )
    if LearningResourceTopic.objects.filter(name="Humanities").exists():
        LearningResourceTopic.objects.get_or_create(
            name="Theater", parent=LearningResourceTopic.objects.get(name="Humanities")
        )


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0101_add_climate_topic_mapping"),
    ]

    operations = [migrations.RunPython(add_theater_subtopic, migrations.RunPython.noop)]
