# Generated by Django 4.2.27 on 2026-02-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0101_add_learning_material"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningresource",
            old_name="content_tags",
            new_name="resource_tags",
        ),
        migrations.AddField(
            model_name="learningresource",
            name="resource_category",
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
