# Generated by Django 4.2.26 on 2025-11-25 15:32

from django.db import migrations


def add_natural_climate_subtopic(apps, schema_editor):
    LearningResourceTopic = apps.get_model(
        "learning_resources", "LearningResourceTopic"
    )
    parent = LearningResourceTopic.objects.filter(
        name="Energy, Climate & Sustainability"
    )
    if parent.exists():
        LearningResourceTopic.objects.get_or_create(
            name="Natural Climate Systems",
            parent=parent.first(),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0102_add_theater_topic"),
    ]

    operations = [
        migrations.RunPython(add_natural_climate_subtopic, migrations.RunPython.noop)
    ]
