# Generated by Django 4.2.28 on 2026-02-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0102_learning_resources_resource_category"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentfile",
            name="run_or_resource_defined",
        ),
        migrations.AlterUniqueTogether(
            name="contentfile",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contentfile",
            name="duration",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="contentfile",
            name="learning_material_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_material_content_files",
                to="learning_resources.learningresource",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentfile",
            unique_together={
                ("key", "run", "learning_resource", "learning_material_resource")
            },
        ),
        migrations.AddConstraint(
            model_name="contentfile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("learning_resource__isnull", False), ("run__isnull", True)
                    ),
                    models.Q(
                        ("learning_resource__isnull", True), ("run__isnull", False)
                    ),
                    models.Q(
                        ("learning_material_resource__isnull", False),
                        ("learning_resource__isnull", True),
                        ("run__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="learning_material_resource_run_or_resource_defined",
                violation_error_message=(
                    "One of learning_resource, learning_material_resource, or run "
                    "must be defined. Both learning_resource and run cannot be "
                    "defined atthe same time.",
                ),
            ),
        ),
    ]
