# Generated by Django 4.2.28 on 2026-02-17 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0103_contentfilechanges"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LearningMaterial",
        ),
    ]
