# Generated by Django 4.2.28 on 2026-03-10 16:41

from django.db import migrations


def update_article_resources(apps, schema_editor):
    LearningResource = apps.get_model("learning_resources", "LearningResource")
    for resource in LearningResource.objects.filter(resource_type="article"):
        resource.resource_type = "document"
        resource.save()


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0104_delete_learningmaterial"),
    ]

    operations = [
        migrations.RunPython(update_article_resources, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
