# Generated by Django 4.2.28 on 2026-03-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0105_delete_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresource",
            name="resource_category",
            field=models.CharField(
                db_index=True,
                help_text="The display category for this resource.",
                max_length=256,
            ),
        ),
    ]
