# Generated by Django 4.2.28 on 2026-03-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0106_resource_category_choices_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningresourcerelationship",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("PROGRAM_COURSES", "Program Courses"),
                    ("PROGRAM_PROGRAMS", "Program Programs"),
                    ("LEARNING_PATH_ITEMS", "Learning Path Items"),
                    ("PODCAST_EPISODES", "Podcast Episodes"),
                    ("PLAYLIST_VIDEOS", "Playlist Videos"),
                    ("COURSE_LEARNING_MATERIALS", "Course Learning Materials"),
                ],
                default=None,
                max_length=256,
            ),
        ),
    ]
