# Generated by Django 4.2.28 on 2026-03-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0109_add_program_programs_relation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="view_count",
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
