# Generated by Django 4.2.28 on 2026-04-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0110_add_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentfile",
            name="edx_module_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=1024, null=True
            ),
        ),
    ]
