# Generated by Django 4.2.29 on 2026-04-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0111_add_edx_module_id_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfile",
            name="youtube_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
