# Generated by Django 4.2.30 on 2026-04-27 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0112_contentfile_youtube_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningresourcerelationship",
            options={"ordering": ["position", "id"]},
        ),
    ]
