# Generated by Django 4.2.30 on 2026-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0113_alter_learningresourcerelationship_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="videochannel",
            name="etl_source",
            field=models.CharField(default="", max_length=12),
        ),
    ]
