# Generated by Django 4.2.30 on 2026-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0113_alter_learningresourcerelationship_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credits_earned",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
