# Generated by Django 4.2.30 on 2026-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0114_course_credits_earned"),
    ]

    operations = [
        migrations.AddField(
            model_name="videochannel",
            name="etl_source",
            field=models.CharField(default="", max_length=12),
        ),
    ]
