# Generated by Django 4.2.30 on 2026-06-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0114_videochannel_etl_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoplaylist",
            name="parent_learning_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_video_playlists",
                to="learning_resources.learningresource",
            ),
        ),
    ]
