# Generated by Django 4.2.30 on 2026-07-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0115_videoplaylist_parent_learning_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETLSourceOwnership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("etl_source", models.CharField(max_length=32)),
                ("resource_type", models.CharField(max_length=32)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("pull", "Pull (Celery ETL)"),
                            ("push", "Push (webhook/event pipeline)"),
                        ],
                        default="pull",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "ETL source ownership",
                "verbose_name_plural": "ETL source ownerships",
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="etlsourceownership",
            unique_together={("etl_source", "resource_type")},
        ),
    ]
