# Generated by Django 4.2.30 on 2026-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0118_delete_micromasters_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresourcerun",
            name="archive_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
