# Generated by Django 4.2.30 on 2026-08-12 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0121_learningresourcerun_archive_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningresourcetopic",
            options={"ordering": ["name"]},
        ),
    ]
