# Generated by Django 5.2.16 on 2026-08-26 15:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0123_contentfile_dedupe_partial_unique_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialMetadataConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("description", "Description"),
                            ("criteria", "Criteria"),
                            ("learning_goals", "Learning Goals"),
                        ],
                        help_text="The metadata field this row configures.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        help_text="Add any OpenAI LLM model.",
                        max_length=128,
                        verbose_name="LLM Model",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Appended to the assembled course context."
                    ),
                ),
                ("temperature", models.FloatField(default=0.0)),
                (
                    "max_context_tokens",
                    models.PositiveIntegerField(
                        default=16000,
                        help_text="Maximum context tokens sent with this prompt.",
                    ),
                ),
                ("max_output_tokens", models.PositiveIntegerField(default=2048)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CredentialMetadataGeneration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("description", "Description"),
                            ("criteria", "Criteria"),
                            ("learning_goals", "Learning Goals"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        blank=True,
                        help_text="The structured response, or null on failure.",
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The error message, if generation failed.",
                    ),
                ),
                ("prompt_text", models.TextField()),
                ("llm_model", models.CharField(max_length=128)),
                ("temperature", models.FloatField(blank=True, null=True)),
                (
                    "context_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The full context sent to the model.",
                    ),
                ),
                ("context_tokens", models.PositiveIntegerField(default=0)),
                (
                    "retrieved_point_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learning_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_metadata_generations",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["learning_resource", "field", "-created_on"],
                        name="learning_re_learnin_91ce37_idx",
                    )
                ],
            },
        ),
    ]
