# Generated by Django 5.2.17 on 2026-09-14 20:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0124_credential_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The Open Badges 3.0 description, 1-2 sentences.",
                    ),
                ),
                (
                    "criteria",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="Open Badges 3.0 criteria, one skill per bullet.",
                        size=None,
                    ),
                ),
                (
                    "learning_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_metadata",
                        to="learning_resources.learningresource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
