# Generated by Django 5.2.17 on 2026-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0126_credential_metadata_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialmetadataconfiguration",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("course", "Course"),
                    ("program", "Program"),
                    ("learning_path", "Learning Path"),
                    ("podcast", "Podcast"),
                    ("podcast_episode", "Podcast Episode"),
                    ("video", "Video"),
                    ("video_playlist", "Video Playlist"),
                    ("document", "Document"),
                ],
                default="course",
                help_text="The kind of resource this row's prompt is written for.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="credentialmetadataconfiguration",
            name="field",
            field=models.CharField(
                choices=[("description", "Description"), ("criteria", "Criteria")],
                help_text="The metadata field this row configures.",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialmetadataconfiguration",
            constraint=models.UniqueConstraint(
                fields=("field", "resource_type"),
                name="unique_credential_metadata_configuration_field_resource_type",
            ),
        ),
    ]
