# Generated by Django 5.2.17 on 2026-09-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0128_credential_metadata_configuration_resource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETLSourceOwnership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("etl_source", models.CharField(max_length=32)),
                ("resource_type", models.CharField(max_length=32)),
                (
                    "owner",
                    models.CharField(
                        choices=[
                            ("legacy", "Legacy (Celery ETL)"),
                            ("warehouse", "Warehouse pull (StarRocks)"),
                            ("webhook", "Webhook push (data platform)"),
                        ],
                        default="legacy",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "ETL source ownership",
                "verbose_name_plural": "ETL source ownerships",
                "unique_together": {("etl_source", "resource_type")},
            },
        ),
    ]
