# Generated by Django 5.2.17 on 2026-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_resources", "0129_etlsourceownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="etlsourceownership",
            name="shadow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("warehouse", "Warehouse pull (StarRocks)"),
                    ("webhook", "Webhook push (data platform)"),
                ],
                default="",
                help_text="Pipeline that runs for this pair as a reported dry run",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ETLShadowRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("etl_source", models.CharField(max_length=32)),
                ("resource_type", models.CharField(max_length=32)),
                (
                    "pipeline",
                    models.CharField(
                        choices=[
                            ("legacy", "Legacy (Celery ETL)"),
                            ("warehouse", "Warehouse pull (StarRocks)"),
                            ("webhook", "Webhook push (data platform)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("counts", models.JSONField(default=dict)),
                ("details", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "ETL shadow run",
                "ordering": ["-created_on"],
                "indexes": [
                    models.Index(
                        fields=["etl_source", "resource_type", "pipeline"],
                        name="learning_re_etl_sou_b01aa1_idx",
                    )
                ],
            },
        ),
    ]
