// Server-side Sentry + OpenTelemetry initialization for the Node.js runtime.
//
// Imported by instrumentation.ts in the "nodejs" runtime block. This replaces
// the separate sentry.server.config.ts that was generated by the Sentry wizard.

import * as Sentry from "@sentry/nextjs"
import type { Context, Span } from "@opentelemetry/api"
import {
  BatchSpanProcessor,
  ConsoleSpanExporter,
  SimpleSpanProcessor,
} from "@opentelemetry/sdk-trace-base"
import type { ReadableSpan, SpanProcessor } from "@opentelemetry/sdk-trace-base"
import type { DetectedResourceAttributes } from "@opentelemetry/resources"
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http"
import diagnosticsChannel from "node:diagnostics_channel"
import type { IncomingMessage, ServerResponse } from "node:http"
import {
  applyResourceOverrides,
  createRequestLogEntry,
  detectResourceOverrides,
  hasOtlpEndpointConfig,
} from "./otel-utils"
import { parseSampleRate } from "./sentry-utils"

// Inject service.version into OTEL_RESOURCE_ATTRIBUTES so the OTEL SDK's
// EnvDetector picks it up alongside any other attributes set via env.
// Simpler than interpolating OTEL_RESOURCE_ATTRIBUTES in ol-infrastructure.
if (process.env.NEXT_PUBLIC_VERSION) {
  const prefix = `service.version=${encodeURIComponent(process.env.NEXT_PUBLIC_VERSION)}`
  const existing = process.env.OTEL_RESOURCE_ATTRIBUTES
  process.env.OTEL_RESOURCE_ATTRIBUTES = existing
    ? `${prefix},${existing}`
    : prefix
}

/**
 * Build the list of extra span processors injected into Sentry's OTEL provider.
 *
 * Sentry's own SentrySpanProcessor is always first in the chain (managed by
 * Sentry internally). These processors are appended after it, so they receive
 * every span that passes the OTEL sampler — independently of whether Sentry
 * chooses to report that span to its backend via beforeSendTransaction.
 *
 * LOCAL TESTING (no Grafana Alloy required):
 * Set OTEL_TRACES_EXPORTER=console and OTEL_TRACES_SAMPLER_ARG=1.0 to print
 * completed spans as JSON to stdout. See env/frontend.env for details.
 */
function buildSpanProcessors(): SpanProcessor[] {
  const processors: SpanProcessor[] = []

  const overrides = detectResourceOverrides()
  if (Object.keys(overrides).length > 0) {
    processors.push(new ResourceAttributeOverrideSpanProcessor(overrides))
  }

  if (hasOtlpEndpointConfig(process.env)) {
    processors.push(new BatchSpanProcessor(new OTLPTraceExporter()))
  } else if (process.env.OTEL_TRACES_EXPORTER === "console") {
    processors.push(new SimpleSpanProcessor(new ConsoleSpanExporter()))
  }

  return processors
}

/**
 * Apply resource attributes from OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES
 * to every span at end time. Sentry hard-codes service.name to "node" and
 * ignores OTEL_RESOURCE_ATTRIBUTES on its internal resource, so without this
 * the spans we ship to Alloy/Tempo would be misattributed.
 *
 * See https://github.com/getsentry/sentry-javascript/issues/20502
 */
class ResourceAttributeOverrideSpanProcessor implements SpanProcessor {
  private readonly overrides: DetectedResourceAttributes

  constructor(overrides: DetectedResourceAttributes) {
    this.overrides = overrides
  }

  onStart(_span: Span, _parentContext: Context): void {
    // no-op
  }

  onEnd(span: ReadableSpan): void {
    applyResourceOverrides(span, this.overrides)
  }

  shutdown(): Promise<void> {
    return Promise.resolve()
  }

  forceFlush(): Promise<void> {
    return Promise.resolve()
  }
}

declare global {
  // eslint-disable-next-line no-var
  var __NEXT_REQUEST_LOGGER_SUBSCRIBED__: boolean | undefined
}

/**
 * Subscribe to Node's built-in HTTP server diagnostics channels and emit a
 * structured JSON log line per completed request. This runs independently of
 * the OTEL sampler — every request is logged regardless of OTEL_TRACES_SAMPLER_ARG
 * — so the logs can be used as ground truth for verifying OTEL trace coverage.
 *
 * Enabled by default; set NEXT_SERVER_REQUEST_LOGGING=false to disable.
 *
 * The channels (`http.server.request.start`, `http.server.response.finish`)
 * are marked Experimental in Node 24 and 25, but are the same surface that
 * Sentry/OTEL/Datadog subscribe to internally; the API has been stable in
 * practice for years.
 *
 * Guarded against double-subscription via a globalThis flag — instrumentation
 * hooks can be re-evaluated on dev reloads or worker restarts, and stacked
 * subscriptions would duplicate every log line.
 */
function subscribeRequestLogger(): void {
  if (globalThis.__NEXT_REQUEST_LOGGER_SUBSCRIBED__) return
  globalThis.__NEXT_REQUEST_LOGGER_SUBSCRIBED__ = true

  const startTimes = new WeakMap<IncomingMessage, bigint>()

  diagnosticsChannel.subscribe("http.server.request.start", (message) => {
    const { request } = message as { request: IncomingMessage }
    startTimes.set(request, process.hrtime.bigint())
  })

  diagnosticsChannel.subscribe("http.server.response.finish", (message) => {
    const { request, response } = message as {
      request: IncomingMessage
      response: ServerResponse
    }
    const start = startTimes.get(request)
    if (start === undefined) return
    startTimes.delete(request)
    const durationMs = Number((process.hrtime.bigint() - start) / 1_000_000n)
    console.info(
      JSON.stringify(createRequestLogEntry({ request, response, durationMs })),
    )
  })
}

if (process.env.NEXT_SERVER_REQUEST_LOGGING !== "false") {
  subscribeRequestLogger()
}

// OTEL_TRACES_SAMPLER_ARG controls the OTEL sampler rate — i.e. what fraction
// of requests create spans at all. All sampled spans flow to both Sentry's
// internal processor AND the OTLP processor (→ Alloy/Tempo).
// Defaults to 1.0 (100%) so that Alloy receives every trace in production.
//
// NOTE: OTEL_TRACES_SAMPLER is intentionally NOT read here. Sentry manages its
// own OTEL provider via SentrySampler, which already implements parent-based
// sampling as a built-in rule: when an incoming request carries a sampled
// traceparent header, that decision is inherited before tracesSampleRate is
// consulted — equivalent to parentbased_traceidratio.
const otelSampleRate = parseSampleRate(process.env.OTEL_TRACES_SAMPLER_ARG, 1)

// NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE is a secondary, Sentry-only filter.
// Of the spans that reach Sentry's processor, only this fraction are actually
// sent to the Sentry backend. Defaults to 1.0 when unset.
// This lets you run Alloy at 100% while keeping Sentry costs/quota lower.
const sentrySampleRate = parseSampleRate(
  process.env.NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE,
  1,
)

Sentry.init({
  dsn: process.env.NEXT_PUBLIC_SENTRY_DSN,
  release: process.env.NEXT_PUBLIC_VERSION,
  environment: process.env.NEXT_PUBLIC_SENTRY_ENV,

  // Controls the OTEL sampler — spans not sampled here never reach any
  // processor. Set via OTEL_TRACES_SAMPLER_ARG at runtime (K8s/Helm).
  tracesSampleRate: otelSampleRate,

  // Inject our OTLP exporter (and console fallback) into Sentry's OTEL
  // provider. These processors run in parallel with Sentry's own
  // SentrySpanProcessor and are unaffected by beforeSendTransaction.
  openTelemetrySpanProcessors: buildSpanProcessors(),

  // Secondary Sentry-only downsampler: drop transactions before they are
  // sent to the Sentry backend, without affecting the OTLP/Alloy pipeline.
  // Controlled by NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE.
  beforeSendTransaction: (transaction) => {
    return Math.random() < sentrySampleRate ? transaction : null
  },

  debug: false,
})
