// Server-side Sentry + OpenTelemetry initialization for the Node.js runtime.
//
// Imported by instrumentation.ts in the "nodejs" runtime block. This replaces
// the separate sentry.server.config.ts that was generated by the Sentry wizard.

import * as Sentry from "@sentry/nextjs"
import {
  BatchSpanProcessor,
  ConsoleSpanExporter,
  SimpleSpanProcessor,
} from "@opentelemetry/sdk-trace-base"
import type { SpanProcessor } from "@opentelemetry/sdk-trace-base"
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http"
import diagnosticsChannel from "node:diagnostics_channel"
import type { IncomingMessage, ServerResponse } from "node:http"
import { createRequestLogEntry, hasOtlpEndpointConfig } from "./otel-utils"
import { SPAN_CREATION_SAMPLE_RATE, installOpenTelemetry } from "./otel-setup"
import { parseSampleRate } from "./sentry-utils"
import { env } from "@/env"
import { validateEnv } from "../validateEnv"
import { ValidationError } from "yup"

// Validate the full environment schema once at server startup (Node runtime).
// validateEnv() is skipped in next.config.js during Docker builds
// (NEXT_BUILD_CI=1) because NEXT_PUBLIC_* values are injected at runtime, not
// present at build — so this startup check is where deployed pods get validated
// (presence AND format). `abortEarly: false` means a single failure reports
// every bad var at once. On failure we log and exit so the pod crash-loops with
// a clear message instead of silently serving broken pages — an uncaught throw
// here is not guaranteed to terminate the process (Next may log and continue),
// hence the explicit process.exit(1).
try {
  validateEnv()
} catch (err) {
  const detail =
    err instanceof ValidationError ? err.errors.join("\n  - ") : String(err)
  console.error(
    `[startup] Environment validation failed:\n  - ${detail}\n` +
      "Exiting to prevent broken deployment.",
  )
  process.exit(1)
}

// Inject service.version into OTEL_RESOURCE_ATTRIBUTES so the OTEL SDK's
// EnvDetector picks it up alongside any other attributes set via env.
// Simpler than interpolating OTEL_RESOURCE_ATTRIBUTES in ol-infrastructure.
const appVersion = env("NEXT_PUBLIC_VERSION")
if (appVersion) {
  const prefix = `service.version=${encodeURIComponent(appVersion)}`
  const existing = process.env.OTEL_RESOURCE_ATTRIBUTES
  process.env.OTEL_RESOURCE_ATTRIBUTES = existing
    ? `${prefix},${existing}`
    : prefix
}

// NEXT_OTEL_FETCH_DISABLED is deliberately NOT set here. Sentry sets it only
// `if (!options.skipOpenTelemetrySetup)`, which is easy to read as an omission
// to correct -- but nativeNodeFetchIntegration's _shouldInstrumentSpans is
// `!clientOptions.skipOpenTelemetrySetup && hasSpansEnabled(clientOptions)`,
// so under skipOpenTelemetrySetup Sentry emits no fetch spans at all. There is
// nothing to de-duplicate, and setting it would leave server-side fetch with no
// spans from anyone. Next's patch-fetch is the only source, so it stays on.

/**
 * Span processors that export to Alloy/Tempo, appended after Sentry's own.
 *
 * There is no resource-rewriting processor here any more. The provider is
 * built with the real Resource (see otel-setup.ts), so spans carry the right
 * service.name from birth rather than having it patched on at export.
 *
 * LOCAL TESTING (no Grafana Alloy required):
 * Set OTEL_TRACES_EXPORTER=console to print completed spans as JSON to stdout.
 * See env/frontend.env for details.
 */
function buildSpanProcessors(): SpanProcessor[] {
  if (hasOtlpEndpointConfig(process.env)) {
    return [new BatchSpanProcessor(new OTLPTraceExporter())]
  }
  if (process.env.OTEL_TRACES_EXPORTER === "console") {
    return [new SimpleSpanProcessor(new ConsoleSpanExporter())]
  }
  return []
}

declare global {
  // eslint-disable-next-line no-var
  var __NEXT_REQUEST_LOGGER_SUBSCRIBED__: boolean | undefined
}

// Skip Next-internal paths (static chunks, HMR, dev endpoints) and the
// favicon. These never get OTEL traces (Sentry's HttpInstrumentation already
// filters them) so they're noise for the OTEL-coverage diagnostic, and in
// prod they mostly hit the CDN anyway. RSC fetches go to real route paths
// (e.g. /courses?_rsc=...) and are not filtered.
const NEXT_INTERNAL_PATH = /^\/(_next\/|__nextjs_|favicon\.ico)/

/**
 * Subscribe to Node's built-in HTTP server diagnostics channels and emit a
 * structured JSON log line per completed request. This runs independently of
 * the OTEL sampler — every request is logged regardless of any sampling
 * decision — so the logs can be used as ground truth for verifying OTEL trace
 * coverage.
 *
 * Enabled by default; set NEXT_SERVER_REQUEST_LOGGING=false to disable.
 *
 * The channels (`http.server.request.start`, `http.server.response.finish`)
 * are marked Experimental in Node 24 and 25, but are the same surface that
 * Sentry/OTEL/Datadog subscribe to internally; the API has been stable in
 * practice for years.
 *
 * Guarded against double-subscription via a globalThis flag — instrumentation
 * hooks can be re-evaluated on dev reloads or worker restarts, and stacked
 * subscriptions would duplicate every log line.
 */
function subscribeRequestLogger(): void {
  if (globalThis.__NEXT_REQUEST_LOGGER_SUBSCRIBED__) return
  globalThis.__NEXT_REQUEST_LOGGER_SUBSCRIBED__ = true

  const startTimes = new WeakMap<IncomingMessage, bigint>()

  diagnosticsChannel.subscribe("http.server.request.start", (message) => {
    const { request } = message as { request: IncomingMessage }
    startTimes.set(request, process.hrtime.bigint())
  })

  diagnosticsChannel.subscribe("http.server.response.finish", (message) => {
    const { request, response } = message as {
      request: IncomingMessage
      response: ServerResponse
    }
    const start = startTimes.get(request)
    if (start === undefined) return
    startTimes.delete(request)
    if (request.url && NEXT_INTERNAL_PATH.test(request.url)) return
    const durationMs = Number((process.hrtime.bigint() - start) / 1_000_000n)
    console.info(
      JSON.stringify(createRequestLogEntry({ request, response, durationMs })),
    )
  })
}

if (process.env.NEXT_SERVER_REQUEST_LOGGING !== "false") {
  subscribeRequestLogger()
}

// Sentry's own rate, independent of span creation. Applied to transactions
// that already exist, so lowering it costs Tempo nothing.
const sentrySampleRate = parseSampleRate(
  env("NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE"),
  1,
)

Sentry.init({
  dsn: env("NEXT_PUBLIC_SENTRY_DSN"),
  release: env("NEXT_PUBLIC_VERSION"),
  environment: env("NEXT_PUBLIC_SENTRY_ENV"),

  // We build the provider, resource, propagator and context manager ourselves
  // in installOpenTelemetry() below. See otel-setup.ts for why -- and for why
  // the sampler is deliberately still Sentry's.
  skipOpenTelemetrySetup: true,

  // Governs span creation, so it stays at 1: a span never created is a span
  // Tempo never sees. Not Sentry's volume knob. See otel-setup.ts.
  tracesSampleRate: SPAN_CREATION_SAMPLE_RATE,

  // Sentry's volume knob: the fraction of already-created transactions Sentry
  // keeps. Independent of what reaches Tempo, which is why the rate above can
  // stay pinned at 1.
  beforeSendTransaction: (transaction) => {
    return Math.random() < sentrySampleRate ? transaction : null
  },

  debug: false,
})

// After Sentry.init: SentrySampler and SentrySpanProcessor both need a client,
// and Sentry has by then declined to register its own globals.
installOpenTelemetry({ spanProcessors: buildSpanProcessors() })
